Agregando el log de clonar cursos en la tabla de actividad de curso
omegaup/omegaup pull request #4637
Opened 2020-09-10 23:53 UTC by pabo99

# Descripción

Se agregan los logs de clonar cursos en la tabla de reporte e actividades del
curso.

![CourseCloneLog](https://user-images.githubusercontent.com/3230352/92826156-fee02300-f395-11ea-981d-d2eca4c4f51f.gif)

Fixes: #4630 

# Comentarios

En este cambio agregué toda la migración de `ActivityReport` a plantilla
unificada. Al ver el tamaño del PR, será necesario partir este cambio, al
menos en dos partes más:

- [ ] Migración de vista`ActivityReport` a plantilla unificada.
- [ ] Cambios en el servidor para agregar logs de clonar curso.

# Checklist:

- [x] El código sigue la [guía de estilo](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) de omegaUp.
- [x] Se corrieron todas las pruebas y pasaron.
- [x] Si se está agregando funcionalidad nueva, se agregaron pruebas.
- [ ] Si el cambio es grande (> 200 líneas), hay que intentar partirlo en
      varios pull requests. De preferencia uno para los controladores + phpunit
      y luego otro para la interfaz.

2020-09-14 23:03 UTC, lhchavez requested changes
welp 470 líneas!!! se puede partir este cambio?

2020-09-14 23:36 UTC, pabo99 commented
> welp 470 líneas!!! se puede partir este cambio?

Si, ya está la primera parte en el PR #4638 

Aún faltará otro cambio para la migración y que este PR sea para agregar el log de clonar cursos a la tabla de actividades ahora si

2020-09-24 02:08 UTC, pabo99 commented
Ya bajó a 204 líneas. Aún así, todavía lo voy a partir, porque de acuerdo a los cambios que se realizaron en PR #4638, este cambio podría crecer un poco más, además de que faltaría agregar pruebas.

2020-09-26 20:41 UTC, pabo99 commented
Listo, ya está más pequeño el cambio.

2020-09-26 22:39 UTC, lhchavez commented on frontend/server/src/ActivityReport.php
> +            }
me gusta más `null` que el valor mágico `''` para representar que algo no existe.

2020-09-26 22:39 UTC, lhchavez commented on frontend/server/src/DAO/Courses.php
> +                ccl.result,
se puede llamar esto `clone_result` y `token_payload` `clone_token_payload`? así sin prefijo me cuesta trabajo adivinar a qué se refieren sin ver la implementación.

2020-09-27 04:42 UTC, pabo99 commented on frontend/server/src/ActivityReport.php
> +            }
Listo

2020-09-27 04:42 UTC, pabo99 commented on frontend/server/src/DAO/Courses.php
> +                ccl.result,
Listo.

2020-09-27 15:39 UTC, lhchavez approved these changes

2020-09-27 15:39 UTC, merged