Permitir los parameteros `start` y `end` en `iframe`s
omegaup/omegaup pull request #6368
Opened 2022-02-13 22:59 UTC by heduenas

Esto necesario porque el curso de C++ se grabó en videos de 1 hora cada uno y cada lección require sólo un clip pequeño de algunos minutos.

2022-02-14 02:27 UTC, lhchavez commented on frontend/www/js/omegaup/markdown.ts
> +    const whitelist = /^<\/?(a(?:\s+(?:(?:href="(?:(?:mailto:[-A-Za-z0-9+&@#/%?=~_|!:,.;()*[\]$]+)|(?:[a-z/_-]+))")|(?:target="[a-z/_-]+")|(?:class="[a-zA-Z0-9 _-]+")|(?:title="[^"<>]*")))*|details|s
se ve bien, sólo que al momento de separar los dos nuevos codepaths _tiene_ que haber un caracter y ahí está opcional, entonces aceptaría urls malformados. también faltan un montón de `?:` para evitar capturar esos grupos.


```suggestion
    const whitelist = /^<\/?(a(?:\s+(?:(?:href="(?:(?:mailto:[-A-Za-z0-9+&@#/%?=~_|!:,.;()*[\]$]+)|(?:[a-z/_-]+))")|(?:target="[a-z/_-]+")|(?:class="[a-zA-Z0-9 _-]+")|(?:title="[^"<>]*")))*|details|summary|figure|figcaption|code|i|table|tbody|thead|tr|th(?: align="\w+")?|td(?: align="\w+")?|iframe(?: (?:src="https:\/\/www\.youtube\.com\/embed\/[\w-]+(?:[&?](?:(?:start=[0-9]+)|(?:end=[0-9]+)))*"|(?:width|height|allowfullscreen|frameborder|allow|title)(?:="[^"]+")?))*|iframe(?: (?:src="https:\/\/www\.facebook\.com\/plugins\/video.php\?[\w\d%-_]+"|(?:width|height|scrolling|allowTransparency|allowFullScreen|frameborder)(?:="[^"]+")?))*|div|h3|span|form(?: role="\w+")*|label|select|option(?: (value|selected)="\w+")*|strong|span|button(?: type="\w+")?)(\s+class="[a-zA-Z0-9 _-]+")?>$/i;
```

2022-11-04 05:28 UTC, pabloaguilar requested changes

2022-11-04 05:28 UTC, pabloaguilar commented on frontend/www/js/omegaup/markdown.test.ts
> +    it('Should handle iframe with youtube with start and end timestamp flags', () => {
Qué tal agregar una prueba de los parámetros en orden inverso:
`end=X&start=Y`

2022-11-04 05:28 UTC, pabloaguilar commented on frontend/www/js/omegaup/markdown.test.ts
> +    it('Should handle iframe with youtube with start and end timestamp flags', () => {
Qué tal un par de pruebas más una con solo `start` y una con solo `end`

2023-03-17 19:58 UTC, closed without merging