feat score-mode
omegaup/omegaup pull request #6458
Opened 2022-03-22 22:03 UTC by marleneharms

# Descripción

Se añadió el nuevo campo `score-mode` en la tabla `Contest` de tipo enum con los valores `{'partial', 'all_or_nothing', 'max_per_group'}
`
Fixes: #6418

# Checklist:

- [x] El código sigue la [guía de
      estilo](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) de
      omegaUp.
- [x] Se corrieron todas las pruebas y pasaron.

2022-03-23 11:08 UTC, lhchavez commented on frontend/database/00001_initial_schema.sql
> +  `score_mode` enum('partial', 'all_or_nothing', 'max_per_group') NOT NULL COMMENT 'Indica el tipo de evaluación para el concurso',
estos archivos de migración no se deben tocar, porque una vez aplicados en producción ya no se vuelven a tocar. eso causaría que este cambio jamás sea visible en producción!

la manera correcta de hacer este cambio es mediante un script de migración nuevo donde se agregue esa columna. checa la historia de este directorio para ver cómo se ha hecho en otros PRs. (hacer eso es buena idea en cualquier repositorio!)

2022-03-24 07:18 UTC, pabo99 commented
Parece que los errores son legítimos. Habrá que agregar un valor por defecto en este campo, para que no tengas que agregarlo explícitamente en todas las pruebas que están fallando.

2022-03-24 08:15 UTC, pabo99 commented
Ahh, también va a ser necesario agregar ese campo en `Contest::apiCreate`:
https://github.com/omegaup/omegaup/blob/0840454399cbe247e52142ea3bbc9dbc363ce523/frontend/server/src/Controllers/Contest.php#L2490-L2509
, debido a que esta API crea un objeto con todos los campos de la tabla, y al no pasarle este nuevo campo, se está asumiendo que es nulo.

Antes de agregarlo al objeto, valida que el valor que se reciba pertenezca al set de opciones disponibles, puedes basarte en este ejemplo:
https://github.com/omegaup/omegaup/blob/0840454399cbe247e52142ea3bbc9dbc363ce523/frontend/server/src/Controllers/Contest.php#L4604-L4607.

Y por último vas a tener que agregar la declaración del tipo en esta sección:
https://github.com/omegaup/omegaup/blob/0840454399cbe247e52142ea3bbc9dbc363ce523/frontend/server/src/Controllers/Contest.php#L2430-L2451

En este caso, se recibiría una cadena o nulo.

Puedes revisar que las pruebas pasen correctamente si ejecutas el script:
```bash
./stuff/runtests.sh
```

2022-03-26 06:46 UTC, pabo99 commented on frontend/server/src/Controllers/Contest.php
> +     * @omegaup-request-param null|string $score_mode
Ahh, entonces eso es lo que estaba haciendo que se revirtiera el cambio en los archivos autogenerados al ejecutar el linter.

Entonces, @marleneharms: Sólo tendrías que dejar en este PR los cambios en los archivos:
- `frontend/database/00200_new_grader.sql`
- `frontend/database/schema.sql`

y el resto de cambios en un nuevo PR.

O si se te hace más fácil, crear otro PR con los cambios en los dos archivos arriba mencionados y una vez que ese PR sea aprobado, en este otro puedes combinar los cambios con la rama `main` de `upstream` con los siguientes comandos:
```bash
$ git fetch upstream main:main
$ git merge upstream/main
```

2022-03-28 07:49 UTC, marleneharms commented on frontend/server/src/Controllers/Contest.php
> +     * @omegaup-request-param null|string $score_mode
Excelente, de hecho justamente hay otro issue para editar la parte de controllers y el dao. Solamente investigaré cómo editar este pr de forma que queden solo esos archivos y en mi local no perder los cambios ya hechos a lo otro. Muchas gracias a los dos

2022-03-28 12:42 UTC, lhchavez commented on frontend/server/src/Controllers/Contest.php
> +     * @omegaup-request-param null|string $score_mode
`git switch -c nuevobranch` crea un segundo branch a partir del actual (con todos los contenidos). luego te puedes regresar con `git switch feat/score-mode/6418` y usar `git restore --source=origin/main ...` con los archivos que quieres darle revert.

2022-03-29 02:51 UTC, lhchavez commented on frontend/server/src/Controllers/Contest.php
> +     * @omegaup-request-param null|string $score_mode
ya tiene un valor default, con eso debe bastar.

2022-03-29 03:31 UTC, marleneharms commented on frontend/server/src/Controllers/Contest.php
> +     * @omegaup-request-param null|string $score_mode
Listo, en teoria ahora, solo quedaron los archivos:
- frontend/database/00200_new_grader.sql
- frontend/database/schema.sql
Y quedaron los cambios de los controllers y daos en otra rama.
Gracias por la ayuda

2022-03-30 00:01 UTC, lhchavez commented on frontend/server/src/DAO/Contests.php
> -           COUNT(c.contest_id) as total
se le puede dar revert a todo lo que no tenga que ver con el cambio? la intención es que todos los PRs deben intentar cambiar lo menos posible. así la historia de git no muestra cambios que no son relevantes en las líneas tocadas por si alguna vez necesitamos ver en qué commit se introdujo algún cambio.

2022-03-31 02:44 UTC, lhchavez reviewed
según [el error](https://github.com/omegaup/omegaup/runs/5761817590?check_suite_focus=true#step:15:126), lo único que falta es el `c.*` de L139 y el `*` de L221!

2022-04-04 20:28 UTC, tvanessa commented on frontend/server/src/DAO/Contests.php
>          /** @var list<array{acl_id: int, admission_mode: string, alias: string, archived: bool, certificate_cutoff: int|null, certificates_status: string, contest_for_teams: bool|null, contest_id: in
Aún falta la linea 139 para que pasen las pruebas.

2022-04-06 06:39 UTC, tvanessa requested changes

2022-04-06 06:39 UTC, tvanessa commented on frontend/server/src/DAO/Contests.php
> +                    join(', ', array_keys(\OmegaUp\DAO\VO\Contests::FIELD_NAMES)),
El problema con esta parte es que `join(....)` es código de PHP y la variable `$sql` es una cadena. Entonces necesitamos concatenar lo que regresa el `join()`. Adicionalmente le concatene la variable `c` para no afectar el resto del código.

```suggestion
                    'c.' . join(', c.', array_keys(\OmegaUp\DAO\VO\Contests::FIELD_NAMES)) .  ' ' . ',' .
```

2022-04-06 06:39 UTC, tvanessa commented on frontend/server/src/DAO/Contests.php
>                  SELECT
Acá también falta cerrar la cadena y concatenar
```suggestion
                SELECT' .
```

2022-04-06 06:39 UTC, tvanessa commented on frontend/server/src/DAO/Contests.php
>                      p.scoreboard_url,
Y también acá (la concatenación se quedó en L139)
```suggestion
                    'p.scoreboard_url,
```

2022-04-06 12:39 UTC, lhchavez commented on frontend/server/src/DAO/Contests.php
> +        'FROM Contests ' . 'WHERE problemset_id = ? LIMIT 0, 1;';
```suggestion
        join(', ', array_keys(\OmegaUp\DAO\VO\Contests::FIELD_NAMES)) . 
        ' FROM Contests ' . 'WHERE problemset_id = ? LIMIT 0, 1;';
```

acá nos podemos ahorrar una concatenación

2022-04-06 12:39 UTC, lhchavez commented on frontend/server/src/DAO/Contests.php
> +                join(', ', array_keys(\OmegaUp\DAO\VO\Contests::FIELD_NAMES))
```suggestion
                ' . join(', ', array_keys(\OmegaUp\DAO\VO\Contests::FIELD_NAMES)) . '
```

2022-04-11 14:48 UTC, pabo99 reviewed
Hice algunas sugerencias para que el código quede más legible en las tres consultas que faltan arreglar. Me avisas si tienes alguna duda y la revisamos

2022-04-11 14:48 UTC, pabo99 commented on frontend/server/src/DAO/Contests.php
> +                    join(', ', array_keys(\OmegaUp\DAO\VO\Contests::FIELD_NAMES)),
Para que sea un poco más legible el código, pudieras utilizar una variable extra que se encargue de armar la cadena con los campos, para que después sólo sea necesario concatenarla. Por ejemplo:
```php
        $fields = join(
            '',
            array_map(
                fn (string $field): string => "c.{$field}, ",
                array_keys(
                    \OmegaUp\DAO\VO\Contests::FIELD_NAMES
                )
            )
        );
        $sql = '
                SELECT
                    ' . $fields . '
                    p.scoreboard_url,
                    p.scoreboard_url_admin
                FROM
                    Contests c
                INNER JOIN
                    Problemsets p
                ON
                    p.problemset_id = c.problemset_id
                WHERE
                    c.alias = ?
                LIMIT 1;';
```

2022-04-11 14:48 UTC, pabo99 commented on frontend/server/src/DAO/Contests.php
> +        'FROM Contests ' . 'WHERE problemset_id = ? LIMIT 0, 1;';
También en esta consulta podrías agregar la variable extra, para poder concatenar de manera más clara. Por ejemplo:
```php
        $fields = join(', ', array_keys(\OmegaUp\DAO\VO\Contests::FIELD_NAMES));
        $sql = 'SELECT 
                    ' . $fields . '
                FROM
                    Contests
                WHERE
                    problemset_id = ?
                LIMIT 0, 1;';
```

2022-04-11 14:48 UTC, pabo99 commented on frontend/server/src/DAO/Contests.php
> +                join(', ', array_keys(\OmegaUp\DAO\VO\Contests::FIELD_NAMES))
Acá aún habría una falla. Porque en la consulta original se obtienen todos los campos de todas las tablas (`*`). Quiere decir que al aplicar este `join` sólo estamos tomando en cuenta los campos de la tabla de `Contests`. Revisando la consulta, resulta que también tendríamos que obtener la información de la tabla `Problemsets`. Así que habría que agregar `p.*`. 

De la misma forma que en las otras dos consultas, podemos agregar la variable con los campos para hacer más legible el código:
```php
        $fields = join(
            '',
            array_map(
                fn (string $field): string => "c.{$field}, ",
                array_keys(
                    \OmegaUp\DAO\VO\Contests::FIELD_NAMES
                )
            )
        );
        $sql = '
            SELECT
                ' . $fields .
                ' p.*
            FROM
                Contests c
            INNER JOIN
                Problemsets p
            ON
                p.problemset_id = c.problemset_id
            WHERE c.contest_id IN (
                SELECT DISTINCT
                    c2.contest_id
                FROM
                    Submissions s
                INNER JOIN
                    Contests c2
                ON
                    c2.problemset_id = s.problemset_id
                WHERE
                    s.identity_id = ?
                    AND s.type= \'normal\'
                    AND s.problemset_id IS NOT NULL
                    AND archived = 0
            )
            ORDER BY
                c.contest_id DESC;'; 
```

2022-04-18 23:08 UTC, tvanessa approved these changes

2022-04-19 02:27 UTC, lhchavez reviewed
le damos merge el domingo en la mañana para no bloquear el deployment del sábado. gracias!

2022-04-19 03:10 UTC, heduenas commented
@lhchavez le podemos dar merge de una vez aunque nos quedemos sin deployment el sabado? Los siguientes PRs de Marlene y de Jorge dependen de este cambio cambio al schema.

2022-04-19 03:11 UTC, lhchavez commented
> @lhchavez le podemos dar merge de una vez aunque nos quedemos sin deployment el sabado? Los siguientes PRs de Marlene y de Jorge dependen de este cambio cambio al schema.

igual no se pueden hacer cambios que dependan del esquema la misma semana que se hace merge. hay que esperarnos hasta el domingo.

2022-04-20 02:55 UTC, marleneharms commented
> Hice algunas sugerencias para que el código quede más legible en las tres consultas que faltan arreglar. Me avisas si tienes alguna duda y la revisamos

Super claras Juan Pablo, muchisimas gracias me sirvieron mucho para poder cerrar el PR y entenderlo  mejor

2022-04-21 15:43 UTC, lhchavez commented
> > @lhchavez le podemos dar merge de una vez aunque nos quedemos sin deployment el sabado? Los siguientes PRs de Marlene y de Jorge dependen de este cambio cambio al schema.
> 
> igual no se pueden hacer cambios que dependan del esquema la misma semana que se hace merge. hay que esperarnos hasta el domingo.

corrección: no se pueden mergear cambios a producción, pero los cambios se pueden hacer localmente y se pueden mandar PRs (aunque fallen en github)

2022-04-24 03:33 UTC, merged