fix: disable birthday later than today
omegaup/omegaup pull request #6525
Opened 2022-04-07 14:02 UTC by denllx

# Description

In the _edit profile_ page, I added limitation to the birth date pick so that it won't display dates later than today.

![Screenshot from 2022-04-07 22-00-24](https://user-images.githubusercontent.com/42374096/162217343-2986b98d-4aef-43e5-9c0f-566d6d16b3eb.png)

Fix: #6521 

# Check list:

- [x] The code follows the [guidance
      style](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) from
      omegaUp.
- [x] All tests were run and passed.
- [x] If new functionality is being added, tests have been added.
- [x] If the change is large (> 200 lines), try to split it into
      several pull requests. Preferably one for controllers + phpunit
      and then another for the interface.

2022-04-10 18:47 UTC, lhchavez requested changes

2022-04-10 18:47 UTC, lhchavez commented on frontend/www/js/omegaup/components/user/BasicInformationEdit.vue
> +        :max="new Date().toISOString().split('T')[0]"
```suggestion
        :max="new Date()"
```

the parameter must be a `Date` object according to the declaration in `DatePicker.vue` L32. the provided expression is not one, so the only possible thing that is a `Date` object is just `new Date()`.

2022-04-10 18:47 UTC, lhchavez commented on frontend/www/js/omegaup/components/DatePicker.vue
> +  max!: Date;
```suggestion
  @Prop({ default: null }) max!: Date | null;
```

it's probably better to disable the maximum by explicitly using `null` instead of a magic constant if nothing was passed.

2022-04-10 18:47 UTC, lhchavez commented on frontend/www/js/omegaup/components/DatePicker.vue
> +    :max="max"
can this be omitted if the max is `null`? since the value of this needs to convert the date to an ISO date and the `max` property is declared to be a `Date` object, the `.toISOString().split('T')[0]` part can exist in a [computed property](https://vuejs.org/guide/essentials/computed.html) instead of in L31.

2022-04-11 04:05 UTC, denllx commented on frontend/www/js/omegaup/components/DatePicker.vue
> +  max!: Date;
In fact, I used `new Date()` at first, but it doesn't work. It turns out that the <input type="date"> element only accepts dates in **ISO format**. That's why I intentionally convert it to ISOString.
A blog on [stackoverflow.com](https://stackoverflow.com/questions/38638424/html5-input-type-date-disable-dates-before-today) also explains this.

2022-04-11 04:06 UTC, denllx commented on frontend/www/js/omegaup/components/user/BasicInformationEdit.vue
> +        :max="new Date().toISOString().split('T')[0]"
In fact, I used new Date() at first, but it doesn't work. It turns out that the element only accepts dates in ISO format. That's why I intentionally convert it to ISOString.
A blog on [stackoverflow.com](https://stackoverflow.com/questions/38638424/html5-input-type-date-disable-dates-before-today) also explains this.

2022-04-11 04:15 UTC, denllx commented on frontend/www/js/omegaup/components/DatePicker.vue
> +  max!: Date;
ok. I changed the data type of _max_ to string, and use max='' to disable maximum.

2022-04-11 12:40 UTC, lhchavez requested changes

2022-04-11 12:40 UTC, lhchavez commented on frontend/www/js/omegaup/components/user/BasicInformationEdit.vue
> +        :max="new Date().toISOString().split('T')[0]"
this still needs to happen.

2022-04-11 12:41 UTC, lhchavez commented on frontend/www/js/omegaup/components/DatePicker.vue
> +  max!: Date;
can this please be kept as `Date | null`? I left another comment with a bit more explanation.

2022-04-19 10:22 UTC, denllx commented on frontend/www/js/omegaup/components/DatePicker.vue
> +  @Prop({ default: '' }) max!: string;
I understand. I'll modify it.

2022-04-19 12:03 UTC, denllx commented on frontend/www/js/omegaup/components/DatePicker.vue
> +  @Prop({ default: '' }) max!: string;
I fixed.

2022-04-20 01:56 UTC, lhchavez approved these changes
thanks for the fix!

2022-04-20 02:05 UTC, merged