[Plagiarism Detector] `apiCreate` and `apiUpdate` updated for plagiarism_threshold . Fixes #6696
omegaup/omegaup pull request #6697
Opened 2022-07-24 13:13 UTC by MohitOhlyan

# Descripción
Adding fields and validations for plagiarism_threshold in `apiCreate` and `apiUpdate` in Contest Controller. 
@carlosabcs 

## Comments

Not yet ready to publish. This is draft PR for now and more commits will be added. 

Fixes: #6696 

# Checklist:

- [ ] El código sigue la [guía de
      estilo](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) de
      omegaUp.
- [ ] Se corrieron todas las pruebas y pasaron.
- [ ] Si se está agregando funcionalidad nueva, se agregaron pruebas.
- [ ] Si el cambio es grande (> 200 líneas), hay que intentar partirlo en
      varios pull requests. De preferencia uno para los controladores + phpunit
      y luego otro para la interfaz.

2022-07-24 13:50 UTC, carlosabcs commented on frontend/server/src/Controllers/Contest.php
> +            'plagiarims_threshold'
```suggestion
            'plagiarism_threshold'
```

2022-07-25 14:49 UTC, pabo99 reviewed
Could you add a test to validate whether `plagiarism_treshold` field has been stored correctly?

2022-07-25 14:49 UTC, pabo99 commented on frontend/server/src/Controllers/Contest.php
> +            $check_plagiarism = $r->ensureOptionalBool(
nit:
```suggestion
            $checkPlagiarism = $r->ensureOptionalBool(
```

2022-07-25 14:49 UTC, pabo99 commented on frontend/server/src/Controllers/Contest.php
> +            ) ? 90 : 0;
You already created a variable with this value, so you can use it.
```suggestion
            'plagiarism_threshold' => $checkPlagiarism ? 90 : 0,
```

2022-07-25 20:29 UTC, MohitOhlyan commented
> Could you add a test to validate whether `plagiarism_treshold` field has been stored correctly?

Sure. I will try and add asap.

2022-07-25 20:31 UTC, MohitOhlyan commented on frontend/server/src/Controllers/Contest.php
> +        $check_plagiarism = $r->ensureOptionalBool('check_plagiarism') ?? false;
> nit:

Thanks!! I will update the PR with `checkPlagiarism` instead and the test.

2022-07-25 22:34 UTC, MohitOhlyan commented on frontend/server/src/Controllers/Contest.php
> +        $check_plagiarism = $r->ensureOptionalBool('check_plagiarism') ?? false;
Thanks.

2022-07-28 05:07 UTC, pabo99 reviewed
Before you start creating the unit tests, it would be necessary apply the following suggestions.

2022-07-28 05:07 UTC, pabo99 commented on frontend/server/src/Controllers/Contest.php
> +        $checkPlagiarism = $r->ensureOptionalBool('checkPlagiarism') ?? false;
The function `validateCreate` function should declare this type too:
```php
     * @omegaup-request-param bool|null $check_plagiarism
```

2022-07-28 05:07 UTC, pabo99 commented on frontend/server/src/Controllers/Contest.php
> +     * @omegaup-request-param bool $checkPlagiarism
```suggestion
     * @omegaup-request-param bool|null $check_plagiarism
```

2022-07-28 05:07 UTC, pabo99 commented on frontend/server/src/Controllers/Contest.php
> +     * @omegaup-request-param bool checkPlagiarism
```suggestion
     * @omegaup-request-param bool|null $check_plagiarism
```

2022-07-28 05:07 UTC, pabo99 commented on frontend/server/src/Controllers/Contest.php
> +            ) ?? false;
```suggestion
        $checkPlagiarism = $r->ensureOptionalBool('check_plagiarism') ?? false;
```

2022-07-28 05:07 UTC, pabo99 commented on frontend/server/src/Controllers/Contest.php
> +            'plagiarism_threshold' => $checkPlagiarism ? 90 : 0,
```suggestion
            'plagiarism_threshold',
```

2022-07-28 22:00 UTC, MohitOhlyan commented
> Before you start creating the unit tests, it would be necessary apply the following suggestions.

Thanks!!

2022-07-29 00:11 UTC, pabo99 reviewed
It seems that you will have to wait for PR #6702 to be approved

2022-07-29 00:11 UTC, pabo99 commented on frontend/server/src/Controllers/Contest.php
> +        $checkPlagiarism = $r->ensureOptionalBool('check_plagiarism') ?? false;
At the moment this line could be removed :
```suggestion
```

2022-07-29 00:11 UTC, pabo99 commented on frontend/server/src/Controllers/Contest.php
> + * @psalm-type ContestAdminDetails=array{admin: bool, admission_mode: string, alias: string, archived: bool, available_languages: array<string, string>, contest_for_teams: bool, description: string,
Nit:
```suggestion
 * @psalm-type ContestAdminDetails=array{admin: bool, admission_mode: string, alias: string, archived: bool, available_languages: array<string, string>, contest_for_teams: bool, description: string, director: string, feedback: string, finish_time: \OmegaUp\Timestamp, has_submissions: bool, languages: list<string>, needs_basic_information: bool, opened: bool, original_contest_alias: null|string, original_problemset_id: int|null, partial_score: bool, penalty: int, penalty_calc_policy: string, penalty_type: string, points_decay_factor: float, problems?: list<ProblemsetProblem>, problemset_id: int, requests_user_information: string, rerun_id?: int, scoreboard: int, scoreboard_url?: string, scoreboard_url_admin?: string, show_penalty: bool, default_show_all_contestants_in_scoreboard: bool, show_scoreboard_after: bool, start_time: \OmegaUp\Timestamp, submission_deadline?: \OmegaUp\Timestamp|null, submissions_gap: int, title: string, window_length: int|null}
```

2022-07-29 20:18 UTC, pabo99 reviewed
Syntax errors are not being reported in the output I don't know why.

Anyways, with the suggestions below the tests now should pass

2022-07-29 20:18 UTC, pabo99 commented on frontend/tests/Factories/Contest.php
> +    public $checkPlagiarism;
For consistency between arguments, could you add a blank line here:
```suggestion

    /**
     * @readonly
     * @var bool
     */
    public $checkPlagiarism;
```
?

2022-07-29 20:18 UTC, pabo99 commented on frontend/tests/controllers/ContestCloneTest.php
> +     * contest.
nit:
```suggestion

    /**
     * A PHPUnit data provider for all the plagiarism threshold values in a
     * contest.
```

2022-07-29 20:18 UTC, pabo99 commented on frontend/tests/controllers/ContestCloneTest.php
> +     */
Nit:
```suggestion

    /**
     * Check if the plagiarism value is stored correctly in the database.
     *
     * @dataProvider plagiarismThresholdProvider
     */
```

2022-07-29 20:18 UTC, pabo99 commented on frontend/tests/controllers/ContestCloneTest.php
> +        bool $checkPlagiarism
Nit:
```suggestion
        bool $checkPlagiarism,
```

2022-07-29 20:18 UTC, pabo99 commented on frontend/tests/controllers/ContestCloneTest.php
> +        )
Maybe you mean `checkPlagiarism` here:
```suggestion
        $contestData = \OmegaUp\Test\Factories\Contest::createContest(
            new \OmegaUp\Test\Factories\ContestParams([
                'checkPlagiarism' => $checkPlagiarism,
            ])
        );
```
because it is the argument you added in `ContestParams` class. 

Please notice the right place where semicolon should be.

2022-07-29 20:18 UTC, pabo99 commented on frontend/tests/controllers/ContestCloneTest.php
> +        this->assertEquals(
Nit:
```suggestion
        $this->assertEquals(
```

2022-07-29 20:18 UTC, pabo99 commented on frontend/tests/controllers/ContestCloneTest.php
> +     * Check if the plagiarism value is stored correctly in the database.
```suggestion

    /**
     * Check if the plagiarism value is stored correctly in the database.
```
just for consistency between functions

2022-07-29 20:49 UTC, MohitOhlyan commented on frontend/tests/Factories/Contest.php
> +    public $checkPlagiarism;
Sure.

2022-07-29 20:51 UTC, MohitOhlyan commented on frontend/tests/controllers/ContestCloneTest.php
> +        )
Thanks. I think I got confused.

2022-07-29 20:53 UTC, MohitOhlyan commented
> Syntax errors are not being reported in the output I don't know why.
> 
> Anyways, with the suggestions below the tests now should pass



> Syntax errors are not being reported in the output I don't know why.
> 
> Anyways, with the suggestions below the tests now should pass

Also, I can't seem to run the test now in my local environment. Maybe I will pull and try again.

2022-07-29 23:22 UTC, pabo99 commented on frontend/tests/controllers/ContestCreateTest.php
> +        this->assertEquals(
```suggestion
        $this->assertEquals(
```

2022-07-29 23:23 UTC, pabo99 commented on frontend/tests/controllers/ContestDetailsTest.php
> +        this->assertEquals(
```suggestion
        $this->assertEquals(
```

2022-07-30 00:31 UTC, carlosabcs requested changes

2022-07-30 00:31 UTC, carlosabcs commented on frontend/tests/controllers/ContestCreateTest.php
> +    public function testToValidatePlagiarismThresholdValue(
Please rename this to `testValidatePlagiarismThresholdValue`.

2022-07-30 00:31 UTC, carlosabcs commented on frontend/tests/controllers/ContestDetailsTest.php
> +    public function testToValidatePlagiarismThresholdValue(
Rename this to `validatePlagiarismThresholdValue`.

2022-07-30 02:34 UTC, pabo99 reviewed
Bad news, the field `plagiarism_threshold` in `Contests` table was defined as a boolean, so doesn't matter what number you want to store, the table stores only 1's and 0's.

You need to create a new script to fix that field, you can use the same script to fix the filelds `score_1` and `score_2` in the `Plagiarisms` table.

Sorry for not realizing this earlier.

2022-07-30 02:34 UTC, pabo99 commented on frontend/tests/controllers/ContestCloneTest.php
> +
This test is great to validate the plagiarism threshold value when user creates a contest, but here we need to test when user clones that contest. So, you can use the following test:
```suggestion
    /**
     * A PHPUnit data provider for all the plagiarism threshold values in a
     * contest.
     *
     * @return list<array{0:bool, 1:int}>
     */
    public function plagiarismThresholdProvider(): array {
        return [
            [true, 90],
            [false, 0],
        ];
    }

    /**
     * Check if the plagiarism value is stored correctly in the database when
     * the contest is cloned.
     *
     * @dataProvider plagiarismThresholdProvider
     */
    public function testToValidatePlagiarismThresholdValueInClonedContest(
        bool $checkPlagiarism,
        int $plagiarismThresholdExpected
    ) {
        // Create a contest
        $contestData = \OmegaUp\Test\Factories\Contest::createContest(
            new \OmegaUp\Test\Factories\ContestParams([
                'checkPlagiarism' => $checkPlagiarism,
            ])
        );

        $clonedContestAlias = \OmegaUp\Test\Utils::createRandomString();

        // Login with director to clone the contest
        $login = self::login($contestData['director']);

        \OmegaUp\Controllers\Contest::apiClone(
            new \OmegaUp\Request([
                'auth_token' => $login['auth_token'],
                'contest_alias' => $contestData['request']['alias'],
                'title' => $clonedContestAlias,
                'description' => $clonedContestAlias,
                'alias' => $clonedContestAlias,
                'start_time' => \OmegaUp\Time::get(),
            ])
        );

        $response = \OmegaUp\DAO\Contests::getByAlias($clonedContestAlias);

        $this->assertSame(
            $response->plagiarism_threshold,
            $plagiarismThresholdExpected
        );
    }

```

2022-07-30 02:34 UTC, pabo99 commented on frontend/tests/controllers/ContestDetailsTest.php
> +    public function testToValidatePlagiarismThresholdValue(
[Test functions' name ](https://phpunit.readthedocs.io/en/9.5/writing-tests-for-phpunit.html)should start with the prefix `test`, otherwise we need add  the annotation `@test`

2022-07-30 02:34 UTC, pabo99 commented on frontend/tests/controllers/ContestDetailsTest.php
> +     /**
I'm not sure if we are getting the `plagiarism_threshold` value in `Contest::apiDetails`, so you can move the test to the file `ContestUpdateTest`. The test should be as follows:
```suggestion
    /**
     * A PHPUnit data provider for all the plagiarism threshold values in a
     * contest.
     *
     * @return list<array{0:bool, 1:int}>
     */
    public function plagiarismThresholdProvider(): array {
        return [
            [true, 90, 0],
            [false, 0, 90],
        ];
    }

    /**
     * Check if the plagiarism value is stored correctly in the database when a
     * contest is updated.
     *
     * @dataProvider plagiarismThresholdProvider
     */
    public function testToValidatePlagiarismThresholdValueInUpdatedContest(
        bool $checkPlagiarism,
        int $plagiarismThresholdExpected,
        int $plagiarismThresholdExpectedAfterUpdate
    ) {
        // Create a contest
        $contestData = \OmegaUp\Test\Factories\Contest::createContest(
            new \OmegaUp\Test\Factories\ContestParams([
                'checkPlagiarism' => $checkPlagiarism,
            ])
        );

        $response = \OmegaUp\DAO\Contests::getByAlias(
            $contestData['request']['alias']
        );

        $this->assertSame(
            $response->plagiarism_threshold,
            $plagiarismThresholdExpected
        );

        // Login with director to update the contest
        $login = self::login($contestData['director']);

        \OmegaUp\Controllers\Contest::apiUpdate(new \OmegaUp\Request([
            'auth_token' => $login->auth_token,
            'contest_alias' => $contestData['request']['alias'],
            'check_plagiarism' => !$checkPlagiarism,
        ]));

        $response = \OmegaUp\DAO\Contests::getByAlias(
            $contestData['request']['alias']
        );

        $this->assertEquals(
            $response->plagiarism_threshold,
            $plagiarismThresholdExpectedAfterUpdate
        );
    }

     /**
```

2022-07-30 02:34 UTC, pabo99 commented on frontend/tests/controllers/ContestCreateTest.php
> +        bool $checkPlagiarism
nit:
```suggestion
        bool $checkPlagiarism,
```

2022-07-30 02:34 UTC, pabo99 commented on frontend/tests/controllers/ContestCreateTest.php
> +        )
nit:
```suggestion
        $contestData = \OmegaUp\Test\Factories\Contest::createContest(
            new \OmegaUp\Test\Factories\ContestParams([
                'checkPlagiarism' => $checkPlagiarism,
            ])
        );
```

2022-07-30 02:34 UTC, pabo99 commented on frontend/tests/controllers/ContestCreateTest.php
> +        );
It seems like `assertEquals` function is evaluating the expressions as boolean, The way to fix that is using [`assertSame` ](https://phpunit.de/manual/6.5/en/appendixes.assertions.html#appendixes.assertions.assertSame) function. It evaluates the type and the value:
```suggestion
        $this->assertSame(
            $checkPlagiarismDuplicate->plagiarism_threshold,
            $plagiarismThresholdExpected
        );
```

2022-07-30 19:59 UTC, MohitOhlyan commented
> Bad news, the field `plagiarism_threshold` in `Contests` table was defined as a boolean, so doesn't matter what number you want to store, the table stores only 1's and 0's.
> 
> You need to create a new script to fix that field, you can use the same script to fix the filelds `score_1` and `score_2` in the `Plagiarisms` table.
> 
> Sorry for not realizing this earlier.

But it shows `tinyint` for plagiarism_threshold in `schema.sql` and `dao_schema.sql`. Also, in my migration file for `plagiarism_threshold` it is `tinyint`.

2022-07-30 20:05 UTC, MohitOhlyan commented on frontend/tests/controllers/ContestCreateTest.php
> +    public function testToValidatePlagiarismThresholdValue(
Done.

2022-07-30 20:05 UTC, MohitOhlyan commented on frontend/tests/controllers/ContestDetailsTest.php
> +    public function testToValidatePlagiarismThresholdValue(
Done.

2022-07-30 20:33 UTC, MohitOhlyan commented
> > Bad news, the field `plagiarism_threshold` in `Contests` table was defined as a boolean, so doesn't matter what number you want to store, the table stores only 1's and 0's.
> > You need to create a new script to fix that field, you can use the same script to fix the filelds `score_1` and `score_2` in the `Plagiarisms` table.
> > Sorry for not realizing this earlier.
> 
> But it shows `tinyint` for plagiarism_threshold in `schema.sql` and `dao_schema.sql`. Also, in my migration file for `plagiarism_threshold` it is `tinyint`.

Got your point. Carlos updated me on this, that MySQL translates tinyint to boolean.

2022-07-30 22:00 UTC, pabo99 commented
> > > Bad news, the field `plagiarism_threshold` in `Contests` table was defined as a boolean, so doesn't matter what number you want to store, the table stores only 1's and 0's.
> > > You need to create a new script to fix that field, you can use the same script to fix the filelds `score_1` and `score_2` in the `Plagiarisms` table.
> > > Sorry for not realizing this earlier.
> > 
> > 
> > But it shows `tinyint` for plagiarism_threshold in `schema.sql` and `dao_schema.sql`. Also, in my migration file for `plagiarism_threshold` it is `tinyint`.
> 
> Got your point. Carlos updated me on this, that MySQL translates tinyint to boolean.

That's right. So, if you create the script now, maybe tomorrow will be approved and merged with main branch. And this PR don't stay blocked so long

2022-07-30 22:09 UTC, pabo99 commented on frontend/tests/controllers/ContestCloneTest.php
> +                'auth_token' => $login['auth_token'],
Nit:
```suggestion
                'auth_token' => $login->auth_token,
```

2022-07-30 22:12 UTC, pabo99 commented on frontend/tests/controllers/ContestCreateTest.php
> +            'plagiarism_threshold'
```suggestion
```
This field is optional, so you can remove it from this array

2022-07-30 22:34 UTC, MohitOhlyan commented
> > > > Bad news, the field `plagiarism_threshold` in `Contests` table was defined as a boolean, so doesn't matter what number you want to store, the table stores only 1's and 0's.
> > > > You need to create a new script to fix that field, you can use the same script to fix the filelds `score_1` and `score_2` in the `Plagiarisms` table.
> > > > Sorry for not realizing this earlier.
> > > 
> > > 
> > > But it shows `tinyint` for plagiarism_threshold in `schema.sql` and `dao_schema.sql`. Also, in my migration file for `plagiarism_threshold` it is `tinyint`.
> > 
> > 
> > Got your point. Carlos updated me on this, that MySQL translates tinyint to boolean.
> 
> That's right. So, if you create the script now, maybe tomorrow will be approved and merged with main branch. And this PR don't stay blocked so long

I have asked @carlosabcs on this and decided that we can leave the database change for now. Instead we can keep the `plagiarism_threshold` as tinyint in the database for now and on the bases of it's value being `1` we can hardcode the `90` value in the python script. This is because we are not actually providing the functionality to the contest creator with setting the threshold itself. Maybe in the future.

2022-08-04 22:12 UTC, carlosabcs commented on frontend/tests/controllers/ContestDetailsTest.php
> +        $this->assertTrue($response->plagiarism_threshold);
Previously you're stating "`'checkPlagiarism' => false,`", so you must assert that this value is `False`, not `true`.

2022-08-04 22:14 UTC, MohitOhlyan commented on frontend/tests/controllers/ContestDetailsTest.php
> +        $this->assertTrue($response->plagiarism_threshold);
I was testing it and forgot to revert it back to assertFalse. On it.

2022-08-04 22:16 UTC, MohitOhlyan commented on frontend/tests/controllers/ContestDetailsTest.php
> +        $this->assertTrue($response->plagiarism_threshold);
Why don't I remove this section as it is supposed to go in `updateContestTest`

2022-08-05 19:54 UTC, carlosabcs requested changes

2022-08-05 19:54 UTC, carlosabcs commented on frontend/tests/Factories/Contest.php
>       * @param array{title?: string, admissionMode?: string, basicInformation?: bool, contestForTeams?: bool, teamsGroupAlias?: string, requestsUserInformation?: string, contestDirector?: \OmegaUp\DAO
Please add here the type: `plagiarismThreshold?: boolean`

2022-08-12 04:35 UTC, carlosabcs requested changes

2022-08-12 04:35 UTC, carlosabcs commented on frontend/tests/Factories/Contest.php
> +    public $plagiarismThreshold;
Rename this to `$checkPlagiarism` too.

2022-08-12 04:35 UTC, carlosabcs commented on frontend/tests/controllers/ContestCloneTest.php
> +                'plagiarismThreshold' => true,
Use `checkPlagiarism`

2022-08-12 04:35 UTC, carlosabcs commented on frontend/tests/controllers/ContestCreateTest.php
> +                'plagiarismThreshold' => true,
Same here

2022-08-12 05:21 UTC, MohitOhlyan commented on frontend/tests/Factories/Contest.php
> +    public $plagiarismThreshold;
Done.

2022-08-12 05:21 UTC, MohitOhlyan commented on frontend/tests/controllers/ContestCloneTest.php
> +                'plagiarismThreshold' => true,
Done.

2022-08-12 05:21 UTC, MohitOhlyan commented on frontend/tests/controllers/ContestCreateTest.php
> +                'plagiarismThreshold' => true,
Done.

2022-08-16 23:31 UTC, carlosabcs commented
@MohitOhlyan fix unit tests and update the branch.

2022-08-17 13:26 UTC, carlosabcs requested changes

2022-08-17 13:26 UTC, carlosabcs commented on frontend/server/src/Controllers/Contest.php
> +            'check_plagiarism' => $checkPlagiarism ? true : false,
Here, you only need to use `'check_plagiarism' => $checkPlagiarism`. You don't need to assert if a boolean is true to assign the `true` value or `false` instead.

2022-08-17 13:26 UTC, carlosabcs commented on frontend/server/src/Controllers/Contest.php
> +            'check_plagiarism' => $originalContest->check_plagiarism,
Seems like the `check_plagiarism` field is not present in the Contest DAO Class. You need to make sure that it is present, try running `./stuff/update_dao.sh`.

2022-08-17 15:35 UTC, MohitOhlyan commented on frontend/server/src/Controllers/Contest.php
> +            'check_plagiarism' => $originalContest->check_plagiarism,
When I run the `./stuff/update_dao.sh` the local tests are passing but when pushing the changes, the dao files that are modified doesn't get changed.

2022-08-17 15:52 UTC, carlosabcs commented on frontend/server/src/Controllers/Contest.php
> +            'check_plagiarism' => $originalContest->check_plagiarism,
@pabo99 do you know what we can do in this case?

2022-08-17 22:46 UTC, pabo99 commented on frontend/server/src/Controllers/Contest.php
> +            'check_plagiarism' => $originalContest->check_plagiarism,
Yes, I do. Probably you need to copy the content of this file:
- https://github.com/omegaup/omegaup/blob/main/frontend/database/schema.sql
to this one:
- https://github.com/omegaup/omegaup/blob/main/frontend/database/dao_schema.sql

I have already created a PR with that changes: #6724

2022-08-22 20:33 UTC, MohitOhlyan commented
@lhchavez I think the PR is ready to be merged.

2022-08-26 13:55 UTC, lhchavez commented on frontend/tests/controllers/ContestCreateTest.php
> +        $this->assertTrue($checkPlagiarismDuplicate->check_plagiarism);
```suggestion
        $contest = \OmegaUp\DAO\Contests::getByAlias(
            $contestData['request']['alias']
        );
        $this->assertTrue($contest->check_plagiarism);
```

this is not a duplicate of a plagiarism check, but a contest.

2022-08-26 13:56 UTC, lhchavez approved these changes

2022-08-26 14:43 UTC, merged