Plagiarism detector script
omegaup/omegaup pull request #6720
Opened 2022-08-09 22:54 UTC by MohitOhlyan

# Descripción

Plagiarism Detector Script. 

Fixes: #6717 

# Comentarios

Draft PR for now. 
This remaining to do:-
1. Getting submissions from S3. 
2. Releasing results to the database. 
3. 
Needs to be updated. 

# Checklist:

- [x] El código sigue la [guía de
      estilo](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) de
      omegaUp.
- [x] Se corrieron todas las pruebas y pasaron.
- [ ] Si se está agregando funcionalidad nueva, se agregaron pruebas.
- [ ] Si el cambio es grande (> 200 líneas), hay que intentar partirlo en
      varios pull requests. De preferencia uno para los controladores + phpunit
      y luego otro para la interfaz.

2022-08-11 03:11 UTC, carlosabcs requested changes

2022-08-11 03:11 UTC, carlosabcs commented on stuff/cron/copydetect_1.py
> +''' Main Plagiairism Detector Script.
Rename this file to `plagiarism_detection.py`.

2022-08-11 03:11 UTC, carlosabcs commented on stuff/cron/copydetect_1.py
> +
There are many linter error messages, fix those errors.

2022-08-11 03:11 UTC, carlosabcs commented on stuff/cron/copydetect_1.py
> +                                """
Unnecesary code. Please remove this.

2022-08-11 03:11 UTC, carlosabcs commented on stuff/cron/copydetect_1.py
> +    now = datetime.now()
You can use MySQL `CURDATE()` instead of Python's date.

2022-08-11 03:11 UTC, carlosabcs commented on stuff/cron/copydetect_1.py
> +    return content
This is unnecessary too. In the future, it will be added, but now just makes it harder to review the code.

2022-08-11 03:11 UTC, carlosabcs commented on stuff/cron/copydetect_1.py
> +        detector(dbconn,contests[i])
Remove this code too.

2022-08-16 23:30 UTC, carlosabcs commented
@MohitOhlyan merge this branch with the base branch and let's see if the error doesn't appear anymore.

2022-08-17 13:15 UTC, MohitOhlyan commented
> @MohitOhlyan merge this branch with the base branch and let's see if the error doesn't appear anymore.

Done but the error didn't get resolved.

2022-09-04 19:43 UTC, carlosabcs requested changes
Just small errors and I think this can be approved.

2022-09-04 19:43 UTC, carlosabcs commented on stuff/cron/check_plagiarisms.py
> +                                INNER JOIN Contests ON Contests.problemset_id = s.problemset_id
You can avoid using the `Contests` prefix, by using an alias. For example, in this line:
```mysql
INNER JOIN Contests c ON c.problemset_id = s.problemset_id 
```

2022-09-04 19:43 UTC, carlosabcs commented on stuff/cron/check_plagiarisms.py
> +def get_submission_id(dbconn: lib.db.Connection, contest: int) -> None:
A better name for this function can be `get_submissions_ids`

2022-09-04 21:07 UTC, MohitOhlyan commented on stuff/cron/check_plagiarisms.py
> +def get_submission_id(dbconn: lib.db.Connection, contest: int) -> None:
Done.

2022-09-04 21:20 UTC, MohitOhlyan commented
> Just small errors to fix and I think this can be approved.

Done.!! Thanks. I totally forgot about those check_plagiarism flag to be added.

2022-09-06 22:27 UTC, MohitOhlyan commented on stuff/cron/check_plagiarisms.py
> +            /stuff/cron/Submissions/Contest_id/problem_id/language
Understood I will give it a try asap!.

2022-09-06 22:28 UTC, MohitOhlyan commented on stuff/cron/check_plagiarisms.py
> +#!/usr/bin/env python3
Sure!! Thats sounds much better.

2022-10-06 14:25 UTC, lhchavez reviewed
time to add some Python tests to evict all of the testing code from the plagiarism detector file! create a file called `stuff/cron/testing/test_plagiarism_detector.py` and run `pytest stuff/cron/testing/` to invoke it. 

Reference to test in https://docs.pytest.org/en/7.1.x/how-to/usage.html

2022-10-06 14:25 UTC, lhchavez commented on frontend/tests/Utils.php
> +             ' --password ' . escapeshellarg(OMEGAUP_DB_PASS))
```suggestion
             ' --password ' . escapeshellarg(OMEGAUP_DB_PASS)) .
             ' --local-downloader-dir ' . escapeshellarg(OMEGAUP_TEST_ROOT)
```

see the comments in the Python file for an explanation of this.

2022-10-06 14:25 UTC, lhchavez commented on stuff/cron/test_files/test1.cpp
> +#include "extremos.h"
note that the test files should be all named `stuff/cron/testing/testdata/submissions/{guid[0:2]}/{guid[2:]}` so that the `LocalSubmissionDownloader` can find it.

2022-10-06 17:44 UTC, MohitOhlyan commented
> time to add some Python tests to evict all of the testing code from the plagiarism detector file! create a file called `stuff/cron/testing/test_plagiarism_detector.py` and run `pytest stuff/cron/testing/` to invoke it. 
> 
> Reference to test in https://docs.pytest.org/en/7.1.x/how-to/usage.html

Okay. On it.

2022-10-07 16:15 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        detector_result = list(detector.get_copied_code_list())
I believe the result we are getting from detector is actually Tuple and not a list and when we try to iterate the tuple, it gives errors in linters. That's why I just converted into a list.

2022-10-07 16:16 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        run_copy_detect(dbconn, submission_ids, contest, str(problem_ids[i]))
Thanks. That's looks much cleaner to read as well. I'll update the script soon with this as a reference.

2022-10-09 04:06 UTC, MohitOhlyan commented on frontend/tests/Utils.php
> +             ' --password ' . escapeshellarg(OMEGAUP_DB_PASS))
Understood and Done.

2022-10-12 06:10 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +#!/usr/bin/env python3
To test the LocalSubmissionDownloader:-
`python3 stuff/cron/plagiarism_detector.py --local-downloader-dir="/opt/omegaup/stuff/cron/testing/testdata/"`
Can you suggest a better way to call this? I tried adding `testdata` alone but there were type errors when concatenating.

2022-10-12 06:11 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +                                        c.`check_plagiarism` = 1 AND
Will add another condition here for time.

2022-10-12 06:14 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        shutil.copyfile(os.path.join(self._dir, "test1.cpp"), destination_path)
The `test1.cpp` is just a normal file for testing purposes. I can't find a way to access the local submission file so instead we copy the details of `test1.cpp`. 
Here you can see that I have added 9 files in the testing/testdata. I want to copy different data to different files. I can use a random number generator to select which file to copy to which submission. Should I do it? And maybe increase the samples also?

2022-10-12 06:15 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +def run_copy_detect(dir: str, contest_id: int, submissions: Iterable[Mapping[str, Any]]) -> Iterable[[Tuple[Any]]]:
The result we get from `detector` is acutally type Tuple.

2022-10-13 09:11 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        submission_path = os.path.join(dir, str(submission[3]), f'{submission[5]}.{submission[6]}')
This submission path will be different for S3 and LocalSubmissionDownloader. Should I just compare the content of download( if it is Local or S3) and create different path accordingly?

2022-10-13 19:28 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +    if os.path.exists("/opt/omegaup/stuff/cron/temp_directory/problem"+problem_id+"/"):
Done.

2022-10-13 19:28 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        run_copy_detect(dbconn, submission_ids, contest, str(problem_ids[i]))
Done.

2022-10-13 19:29 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +            os.mkdir(current_directory + '/temp_directory/problem'+ str(problem_ids[i])+"/")
Done.

2022-10-13 19:29 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +                        + str(submission_ids[j][5])+'.cpp')
Done.

2022-10-13 19:30 UTC, MohitOhlyan commented on stuff/cron/test_files/test1.cpp
> +#include "extremos.h"
For the `LocalSubmissionDownloader` we would want to have access to the files. But instead for now we are having a some files stored in `stuff/cron/testing/testdata`. I would like to use a list of filenames to pick from it and copy the data of those files into the files with the guid names. Will that be alright?

2022-10-13 19:31 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        submission_path = os.path.join(dir, str(submission[3]), f'{submission[5]}.{submission[6]}')
Done.

2022-10-15 13:37 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +#!/usr/bin/env python3
avoid concatenating paths using string operations. [`os.path.join`](https://docs.python.org/3/library/os.path.html#os.path.join) is there for that!

2022-10-15 14:00 UTC, lhchavez commented on frontend/tests/controllers/PlagiarismTest.php
> +        \OmegaUp\Test\Utils::runCheckPlagiarisms();
good unit tests should use the [Arrange, Act, Assert](https://automationpanda.com/2020/07/07/arrange-act-assert-a-pattern-for-writing-good-tests/) pattern. This line is "Act", and the code before it is "Arrange".

"Assert" is missing!

2022-10-15 14:03 UTC, lhchavez commented on stuff/cron/test_files/test1.cpp
> +#include "extremos.h"
it wouldn't. we really need to use that pattern, otherwise the PHP tests won't work :'(

2022-10-15 14:03 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +#!/usr/bin/env python3
Got it.

2022-10-15 21:32 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        shutil.copyfile(os.path.join(self._dir, "test1.cpp"), destination_path)
Okay. But so what should I name those test files because it doesn't matter what there name is as we are just copying the contents of the test files to the files that we are running plagiarism on. And as we cannot directly access the local files.

2022-10-15 21:33 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +def get_range(code: Sequence[str]) -> Sequence[int]:
Yes. Adding.

2022-10-15 22:10 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +    for i in range(0,len(code)):
done.

2022-10-15 22:10 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        if START_RED in code[i]:
Done.

2022-10-15 22:10 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        if( START_GREEN in code[i]):
Done.

2022-10-15 22:10 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        if END in code[i]:
Done.

2022-10-15 22:12 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +def filter_and_format_result(dbconn: lib.db.Connection, contest_id: int, submissions: Iterable[Tuple[Any, ...]], result: Sequence[Any]) -> None:
submissions contains a contest_id, problemset_id, problem_id, verdict, submission_id. If I write Int or Str instead of Any, it gives errors in linters. Basically the value at that index can be a int or a string.

2022-10-15 22:14 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +def filter_and_format_result(dbconn: lib.db.Connection, contest_id: int, submissions: Iterable[Tuple[Any, ...]], result: Sequence[Any]) -> None:
For result as well, the values inside are [(float, float, string, string, string, string, int), (float, .. and so on)]

2022-10-15 22:26 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +    d = {}
Sorry about that. I have now added the comments. I'll be including them from henceforth.

2022-10-15 22:26 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        d[i[5][2:]] = i[1]
Got it. Done.

2022-10-15 22:27 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        update.append((contest_id, int(100*r[0]), int(100*r[1]),
I have to look up the cursor for having a result in a dict format. I'll have it updated soon.

2022-10-15 22:29 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +                                    'file2': get_range(r[4].split('\n'))})
that was a typo. It should be '5' in second one.

2022-10-15 22:31 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        (filter_and_format_result(dbconn, contest_id, submissions, detector.get_copied_code_list()))
We need `contest_id` for inserting it into the database. We can make a dict of `submission_id and guid` in a separate function and for the `detector.get_copied_code_list()` it is necessary.

2022-10-15 22:31 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        download(submission[5], submission_path)
yes. Looking into cursor right now.

2022-10-15 22:32 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        download= S3SubmissionDownloader()
Done.

2022-10-15 22:59 UTC, MohitOhlyan commented on frontend/tests/controllers/PlagiarismTest.php
> +        \OmegaUp\Test\Utils::runCheckPlagiarisms();
Yes. Working on those!

2022-10-16 02:16 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +def filter_and_format_result(dbconn: lib.db.Connection, contest_id: int, submissions: Iterable[Tuple[Any, ...]], result: Sequence[Any]) -> None:
left a comment below to convert these to `NamedTuple` / `TypedDict`. that way we avoid both having to use indices _and_ `Any`.

2022-10-16 02:16 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +    d = {}
good variable names is preferable to comments. comments are still good though

2022-10-16 02:18 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +def filter_and_format_result(dbconn: lib.db.Connection, contest_id: int, submissions: Iterable[Tuple[Any, ...]], result: Sequence[Any]) -> None:
Yes. I actually use the `dictionary=True` in cursor for that for submissions. For results, I am working in making the `NamedTuple`/ `TypeDict`

2022-10-16 02:19 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +    d = {}
Okay. I updated the names too. I will be pushing the code shortly.

2022-10-16 02:19 UTC, MohitOhlyan commented on frontend/tests/controllers/PlagiarismTest.php
> +// phpcs:disable VariableAnalysis.CodeAnalysis.VariableAnalysis.UnusedVariable
Done.

2022-10-16 02:40 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        shutil.copyfile(os.path.join(self._dir, "test1.cpp"), destination_path)
Can I use the `/tests/runfile/submissions` for this? It already have a directory structure as you described? Or should I just make a new one?

2022-10-16 03:03 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +        shutil.copyfile(os.path.join(self._dir, "test1.cpp"), destination_path)
sure, let's name them `00/0000000...00`, `00/000000...01`< etc (the same length of the guids in other parts of the system)

2022-10-16 03:05 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        shutil.copyfile(os.path.join(self._dir, "test1.cpp"), destination_path)
Okay. And the contents of those files? Should I keep them same?

2022-10-16 03:06 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +        shutil.copyfile(os.path.join(self._dir, "test1.cpp"), destination_path)
yeah, that works.

2022-10-16 03:08 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +        (filter_and_format_result(dbconn, contest_id, submissions, detector.get_copied_code_list()))
no need to make the arrays separate. the code is fine as-is, it's just that it's surrounded by parentheses that are not doing anything

2022-10-16 03:10 UTC, MohitOhlyan commented on stuff/cron/test_files/test1.cpp
> +#include "extremos.h"
Understood.

2022-10-16 03:11 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        (filter_and_format_result(dbconn, contest_id, submissions, detector.get_copied_code_list()))
Okay got it.

2022-10-16 03:11 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +def get_submissions_for_contest(dbconn: lib.db.Connection, contest_id: int) -> Iterable[Tuple[Any, ...]]:
I did this for the INSERT queries. For the submission_ids, I did not because I managed to get a `dict` from the cursor.

2022-10-16 03:33 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        shutil.copyfile(os.path.join(self._dir, "test1.cpp"), destination_path)
Or can we do something like this:- Create a string with `\n` characters to match the code and just copy the string to the `tests/runfile/submissions/problem_id/guid[2:]`? And then we can copy the using the shutil. We don't have to make so many files. Instead only those that we need.

2022-10-16 03:34 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +    d = {}
Done.

2022-10-16 03:35 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        download(submission[5], submission_path)
Done. Not the cursor return dict so I removed the indexing with keys.

2022-10-16 03:36 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        update.append((contest_id, int(100*r[0]), int(100*r[1]),
I updated the code.

2022-10-16 14:13 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +import boto3  # type: ignore
```suggestion
import boto3  # type: ignore
import copydetect  # type: ignore
```

we should put all the third-party imports together.

2022-10-16 14:13 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +#Constants
```suggestion
# Constants
```

2022-10-16 14:13 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +            code_range.append(line_number)
```suggestion
        if START_RED in line or START_GREEN in line:
            code_range.append(line_number)
```

2022-10-16 14:13 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +    code_range = []
```suggestion
    code_range: List[int] = []
```

let's type all local declarations that assign to `[]` or `{}`.

2022-10-16 14:13 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +    guid_and_submission_id_dict = {}
```suggestion
    guid_and_submission_id_dict: Dict[str, str] = {}
```

2022-10-16 14:13 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +        self._bucket.download_file(f'omegaup/submissions/{guid[:2]}/{guid[2:]}', destination_path)
```suggestion
    def __call__(self, guid: str, destination_dir: str) -> None:
        self._bucket.download_file(f'omegaup/submissions/{guid[:2]}/{guid[2:]}', os.path.join(destination_dir, guid))
```

this way we get the full guid as the filename to avoid the awkward mapping shenanigans below.

2022-10-16 14:13 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +        shutil.copyfile(os.path.join(self._dir, f'submissions/{guid[:2]}/{guid[2:]}'), destination_path)
```suggestion
    def __call__(self, guid: str, destination_dir: str) -> None:
        shutil.copyfile(os.path.join(self._dir, f'submissions/{guid[:2]}/{guid[2:]}'), os.path.join(destination_dir, guid))
```

2022-10-16 14:13 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +        results: Sequence[Any]) -> None:
```suggestion
        results: Iterable[CopyDetectorResult]) -> None:
```

we don't access `results` by index, so we can use `Iterable` (which only allows for `for x in r:`). this general idea is called [Postel's Law](https://en.wikipedia.org/wiki/Robustness_principle): always have parameters that imposes the least amount of requirements for what needs to be achieved in the function, and always return results that have the most flexibility for the caller.

2022-10-16 14:16 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +        shutil.copyfile(os.path.join(self._dir, "test1.cpp"), destination_path)
let's keep them as files named with that pattern.

when we do unit testing in Python, we shouldn't refer to these files by name (like `test1.cpp`), but rather by guid (`0000000...00`). so by having the files be named like `test1.cpp`, we'll need to map them to a guid anyways. and for tests from PHP, the files already have this pattern!

2022-10-16 14:37 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        shutil.copyfile(os.path.join(self._dir, "test1.cpp"), destination_path)
Okay.

2022-10-16 23:14 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        shutil.copyfile(os.path.join(self._dir, "test1.cpp"), destination_path)
I am sorry but should I create 1 file in each `testing/testdata/submissions/00/`  named `0000...00000` or should I create all the possible permutations? If all the permutations, should I add them in the same PR?

2022-10-16 23:27 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        """
Understood. Done.

2022-10-16 23:27 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        contest_id: int) -> Iterable[Mapping[str, Any]]:
Done for all such appearances.

2022-10-16 23:28 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +                    )
Done. Thanks, I didn't knew about `os.path.splittext` and `os.path.basename`.

2022-10-16 23:28 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +from mysql.connector import errorcode
Got it.

2022-10-16 23:29 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        filter_and_format_result(dbconn, contest_id, submissions, detector.get_copied_code_list())
Done. Even for Contests query.

2022-10-16 23:29 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +#!/usr/bin/env python3
Done.

2022-10-16 23:30 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +            code_range.append(line_number)
Done.

2022-10-16 23:30 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +    code_range = []
Done for all. I also included List in typing module.

2022-10-16 23:33 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        self._bucket.download_file(f'omegaup/submissions/{guid[:2]}/{guid[2:]}', destination_path)
Then I should also change the destination_dir in the `download` functions to just have the dir and not the guid. Also, we would need language so the 
 ``def __call__(self, guid: str, destination_dir: str, language: str) -> None:
        self._bucket.download_file(f'omegaup/submissions/{guid[:2]}/{guid[2:]}', os.path.join(destination_dir, guid, ".", language))``

2022-10-16 23:34 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        shutil.copyfile(os.path.join(self._dir, f'submissions/{guid[:2]}/{guid[2:]}'), destination_path)
Same here. In the `download`  we will only be creating the `destination_dir` till problem_id.

2022-10-16 23:34 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        results: Sequence[Any]) -> None:
Done.

2022-10-17 13:40 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +            test_dirs=[(os.path.join(dir, problem))],
```suggestion
            test_dirs=[os.path.join(dir, problem)],
```

there's a superfluous extra set of parens.

2022-10-17 13:42 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +        self._dir = os.path.join(SUBMISSION_PATH, dir)
```suggestion
        self._dir = os.path.join(self._dir, dir)
```

let's avoid hardcoded paths

2022-10-17 13:44 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +SUBMISSION_PATH = os.path.abspath(
let's remove this constant. this code shouldn't assume anything about the layout of the repository. the caller can pass in a local submission path if needed.

2022-10-17 13:44 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +        #If the color is red, then it will be the same for the entire 'code'.
```suggestion
        # If the color is red, then it will be the same for the entire 'code'.
```

nit: always use one space between the `#` and the comment.

2022-10-17 13:45 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +    """
this should use `#`. but it also is no longer needed, so we can remove it altogether.

2022-10-17 13:46 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +                                    [2:]] = submission['submission_id']
```suggestion
                                    ] = submission['submission_id']
```

the files are now using the full guid

2022-10-17 13:47 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +    updated_result = []
```suggestion
    updated_result: List[Results] = []
```

for consistency with the other places where the type is annotated.

2022-10-17 13:49 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +        self._bucket.download_file(f'omegaup/submissions/{guid[:2]}/{guid[2:]}', destination_path)
sounds good!

2022-10-18 18:34 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +        shutil.copyfile(os.path.join(self._dir, "test1.cpp"), destination_path)
in other words, we should rename:

* `stuff/cron/testing/testdata/test1.cpp` to `testing/testdata/submissions/00/00000000000000000000000000000000000001`
* `stuff/cron/testing/testdata/test2.cpp` to `testing/testdata/submissions/00/00000000000000000000000000000000000002`
* `stuff/cron/testing/testdata/test3.cpp` to `testing/testdata/submissions/00/00000000000000000000000000000000000003`
* ...
* `stuff/cron/testing/testdata/test9.cpp` to `testing/testdata/submissions/00/00000000000000000000000000000000000009`

and then use the guids `0000000000000000000000000000000000000001`-`0000000000000000000000000000000000000009`

2022-10-18 18:45 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +    updated_result = []
Done.

2022-10-18 18:45 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +                                    [2:]] = submission['submission_id']
Done.

2022-10-18 18:53 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        shutil.copyfile(os.path.join(self._dir, "test1.cpp"), destination_path)
Understood. So, I should include the 9 files in each `/submissions/00` to `submission/ff`?

2022-10-18 19:01 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +        shutil.copyfile(os.path.join(self._dir, "test1.cpp"), destination_path)
no, only in the 00 directory. the other directories shouldn't exist.

2022-10-18 19:03 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +    """
Done.

2022-10-18 19:03 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +SUBMISSION_PATH = os.path.abspath(
got it.

2022-10-18 19:05 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        shutil.copyfile(os.path.join(self._dir, "test1.cpp"), destination_path)
got it. I updated the branch.

2022-10-18 19:06 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +            test_dirs=[(os.path.join(dir, problem))],
Done.

2022-10-18 19:06 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +                        os.path.join(destination_dir, guid))
done.

2022-10-18 19:26 UTC, MohitOhlyan commented
> time to add some Python tests to evict all of the testing code from the plagiarism detector file! create a file called `stuff/cron/testing/test_plagiarism_detector.py` and run `pytest stuff/cron/testing/` to invoke it.
> 
> Reference to test in https://docs.pytest.org/en/7.1.x/how-to/usage.html


> 

So, in the pytest file we should check if we are generating plagiarism table and verify it with the database. Also, we were trying the do this test in PHP earlier so we won't be needing those or we still need to implement these. 

I also found some python test implemented in our repo but they are all UI. And I can't seem to find a reference. I found this `from unittest import TestCase

class TryTesting(TestCase):
    def test_always_passes(self):
        self.assertTrue(True)

    def test_always_fails(self):
        self.assertTrue(False)` . 
Should the python test follow a similar pattern?

2022-10-18 19:50 UTC, lhchavez commented
> > time to add some Python tests to evict all of the testing code from the plagiarism detector file! create a file called `stuff/cron/testing/test_plagiarism_detector.py` and run `pytest stuff/cron/testing/` to invoke it.
> > Reference to test in https://docs.pytest.org/en/7.1.x/how-to/usage.html
> 
> > 
> 
> So, in the pytest file we should check if we are generating plagiarism table and verify it with the database. Also, we were trying the do this test in PHP earlier so we won't be needing those or we still need to implement these.

that's correct!

the ones in PHP are more of integration tests. they are still valuable, but can be implemented in a different PR so that this one doesn't grow too much.

> I also found some python test implemented in our repo but they are all UI. And I can't seem to find a reference. I found this
> 
> ```
>  from unittest import TestCase
> 
> class TryTesting(TestCase):
>     def test_always_passes(self):
>         self.assertTrue(True)
> 
>     def test_always_fails(self):
>         self.assertTrue(False) . 
> ```
> 
> Should the python test follow a similar pattern?

yes!

2022-10-18 19:50 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +"""
this should go inside the function. `"""` delimited text are not comments, they are docstrings.

2022-10-18 19:50 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +    # dbconn.conn.commit()
```suggestion
    dbconn.conn.commit()
```

we should probably commit this.

2022-10-18 19:50 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +        #that's why we don't really make a distinction between them.
```suggestion
        # that's why we don't really make a distinction between them.
```

2022-10-18 19:50 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +        # detector.get_copied_code_list() return a list.
```suggestion
```

this comment is no longer providing any value since we're converting that to something more useful.

2022-10-18 19:50 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +from mysql.connector import errorcode
```suggestion
```

this is not being used.

2022-10-18 20:07 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        # detector.get_copied_code_list() return a list.
Done.

2022-10-18 20:08 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        #that's why we don't really make a distinction between them.
Done.

2022-10-18 20:08 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +    # dbconn.conn.commit()
Done.

2022-10-18 20:08 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +"""
Done and Understood!!!

2022-10-18 20:11 UTC, MohitOhlyan commented
Also, Will the S3 be taken care of? It gives error when no arguments are passed.

2022-10-19 15:15 UTC, MohitOhlyan commented
For test_plagiarism_detector.py. I am thinkin of something like this:-
    ```
     # create a contest 
         # from creating the contest we will need make a contest specific to our needs using SQL queries!
         # add 3 different problems to the contest. 
         # add 3 different users to the contest. 
         # for each user add 3 submission to each problem. 
         # for all of this we will need to manually call a SQL query unlike how we do this is PHP using DAO's. 
    # run the plagiarism_detector.py using the --local-downloader-dir
    # then check if there are correct amount of entries in the database for each contest
          # will again use SQL queries. 
    # then check if there are all values correctly in the database.
```
I had a talk with @carlosabcs on this and this python test are something not previously implemented in the codebase. 
Should we proceed with the above structure and the queries @lhchavez . If you have suggestions please let me know. Thanks. 

Also, can we remove the `PlagiarismTest.php` from this PR and add it in a different PR.

2022-10-19 15:29 UTC, lhchavez commented
> For test_plagiarism_detector.py. I am thinkin of something like this:-
> 
> ```
> # create a contest 
>       # from creating the contest we will need make a contest specific to our needs using SQL queries!
>       # add 3 different problems to the contest. 
>       # add 3 different users to the contest. 
>       # for each user add 3 submission to each problem. 
>       # for all of this we will need to manually call a SQL query unlike how we do this is PHP using DAO's. 
>  # run the plagiarism_detector.py using the --local-downloader-dir
>  # then check if there are correct amount of entries in the database for each contest
>        # will again use SQL queries. 
>  # then check if there are all values correctly in the database.
> ```
> 
> I had a talk with @carlosabcs on this and this python test are something not previously implemented in the codebase. Should we proceed with the above structure and the queries @lhchavez . If you have suggestions please let me know. Thanks.
> 
> Also, can we remove the `PlagiarismTest.php` from this PR and add it in a different PR.

that all sounds great. instead of running the script itself, unit tests normally just call functions. other than that, the rest of the plan sounds great!

2022-10-19 15:30 UTC, lhchavez commented on stuff/cron/testing/testdata/00/0000000000000000000000000000000000000001.cpp
> +#include "extremos.h"
these files shouldn't have extensions. otherwise the local downloader won't find them.

2022-10-19 15:39 UTC, MohitOhlyan commented
>

2022-10-19 15:40 UTC, lhchavez commented
try not to close PRs if the intention is to re-open them. let's keep working on this one to have all the history of the discussions.

2022-10-19 15:42 UTC, MohitOhlyan commented
> try not to close PRs if the intention is to re-open them. let's keep working on this one to have all the history of the discussions.

No. I did it by mistake. I was trying to comment but instead clicked close with comment.

2022-10-19 15:44 UTC, MohitOhlyan commented
> > For test_plagiarism_detector.py. I am thinkin of something like this:-
> > ```
> > # create a contest 
> >       # from creating the contest we will need make a contest specific to our needs using SQL queries!
> >       # add 3 different problems to the contest. 
> >       # add 3 different users to the contest. 
> >       # for each user add 3 submission to each problem. 
> >       # for all of this we will need to manually call a SQL query unlike how we do this is PHP using DAO's. 
> >  # run the plagiarism_detector.py using the --local-downloader-dir
> >  # then check if there are correct amount of entries in the database for each contest
> >        # will again use SQL queries. 
> >  # then check if there are all values correctly in the database.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I had a talk with @carlosabcs on this and this python test are something not previously implemented in the codebase. Should we proceed with the above structure and the queries @lhchavez . If you have suggestions please let me know. Thanks.
> > Also, can we remove the `PlagiarismTest.php` from this PR and add it in a different PR.
> 
> that all sounds great. instead of running the script itself, unit tests normally just call functions. other than that, the rest of the plan sounds great!

But to check the assertions and updation in the database we would need to run the script too right?

2022-10-19 15:47 UTC, MohitOhlyan commented
> > > > For test_plagiarism_detector.py. I am thinkin of something like this:-
> > > > ```
> > > > # create a contest 
> > > >       # from creating the contest we will need make a contest specific to our needs using SQL queries!
> > > >       # add 3 different problems to the contest. 
> > > >       # add 3 different users to the contest. 
> > > >       # for each user add 3 submission to each problem. 
> > > >       # for all of this we will need to manually call a SQL query unlike how we do this is PHP using DAO's. 
> > > >  # run the plagiarism_detector.py using the --local-downloader-dir
> > > >  # then check if there are correct amount of entries in the database for each contest
> > > >        # will again use SQL queries. 
> > > >  # then check if there are all values correctly in the database.
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > I had a talk with @carlosabcs on this and this python test are something not previously implemented in the codebase. Should we proceed with the above structure and the queries @lhchavez . If you have suggestions please let me know. Thanks.
> > > > Also, can we remove the `PlagiarismTest.php` from this PR and add it in a different PR.
> > > 
> > > 
> > > that all sounds great. instead of running the script itself, unit tests normally just call functions. other than that, the rest of the plan sounds great!
> > 
> > 
> > But to check the assertions and updation in the database we would need to run the script too right?
> 
> no, everything that can be done by running the script can be done (and simpler!) by just calling the functions of the directly. there is no scenario in which we _need_ to run the script.

Ohh you mean calling functions that are inside the plagiarism script? Got it.

2022-10-21 15:14 UTC, MohitOhlyan commented
I am trying to call the functions but they are giving no module error. I tried having the `__init__.py` file but still errors. Is there a setup.py file we using for imports? @lhchavez

2022-10-23 15:20 UTC, lhchavez commented
> I am trying to call the functions but they are giving no module error. I tried having the `__init__.py` file but still errors. Is there a setup.py file we using for imports? @lhchavez

can you push the code please? it's hard to diagnose what's happening without looking at the actual code _and_ the actual error without paraphrasing.

2022-10-23 18:27 UTC, lhchavez commented on stuff/cron/test_plagiarism_detector.py
> +
test files shouldn't have `main`.

2022-10-23 18:27 UTC, lhchavez commented on stuff/cron/test_plagiarism_detector.py
> +def test_get_contests(dbconn: lib.db.Connection) -> None:
```suggestion
@pytest.fixture(scope='session')
def dbconn() -> lib.db.Connection:
  # ...
  return dbconn


def test_get_contests(dbconn: lib.db.Connection) -> None:
```

this is how https://docs.pytest.org/en/6.2.x/fixture.html says the code should be structured.

2022-10-23 18:27 UTC, lhchavez commented on stuff/cron/test_plagiarism_detector.py
> +    lib.logs.init(parser.prog, args)
```suggestion
```

tests shouldn't have argument parsers.

2022-10-23 18:27 UTC, lhchavez commented on stuff/cron/test_plagiarism_detector.py
> +    dbconn = lib.db.connect(lib.db.DatabaseConnectionArguments.from_args(args))
```suggestion
    dbconn = lib.db.connect(lib.db.DatabaseConnectionArguments(
      host='localhost',
      port=...
      ...
    ))
```

in the test we should build the arguments directly instead of from arguments (that shouldn't be used in tests).

2022-10-23 18:27 UTC, lhchavez commented on stuff/cron/test_plagiarism_detector.py
> +from plagiarism_detector import get_contests # can only import if in the same directory.
if we need more directories we can tweak L16 so that it includes the directories we need.

2022-10-23 20:07 UTC, MohitOhlyan commented on stuff/cron/test_plagiarism_detector.py
> +from plagiarism_detector import get_contests # can only import if in the same directory.
Got it. For now is it fine if I do the tests in the same directory?

2022-10-23 20:07 UTC, MohitOhlyan commented on stuff/cron/test_plagiarism_detector.py
> +    dbconn = lib.db.connect(lib.db.DatabaseConnectionArguments.from_args(args))
Done.

2022-10-23 20:07 UTC, MohitOhlyan commented on stuff/cron/test_plagiarism_detector.py
> +    lib.logs.init(parser.prog, args)
Done.

2022-10-23 20:07 UTC, MohitOhlyan commented on stuff/cron/test_plagiarism_detector.py
> +def test_get_contests(dbconn: lib.db.Connection) -> None:
Done.

2022-10-23 20:07 UTC, MohitOhlyan commented on stuff/cron/test_plagiarism_detector.py
> +
Done.

2022-10-23 20:20 UTC, lhchavez commented on stuff/cron/test_plagiarism_detector.py
> +from plagiarism_detector import get_contests # can only import if in the same directory.
let's avoid that please

2022-10-23 20:27 UTC, MohitOhlyan commented on stuff/cron/test_plagiarism_detector.py
> +from plagiarism_detector import get_contests # can only import if in the same directory.
Okay. Got it.

2022-10-24 11:09 UTC, MohitOhlyan commented
I was creating a contest using the `omegaup.api.Client` but there I could not modify the`check_plagiarism` field because possibley  we don't have it in our omegaup create api. So, I made some changes in the `stuff/venv/lib/python3.8/site-packages/omegaup/api.py` to have those changes and it works. But it is not showing up the changes in the my `git status`. Should I make the revert the changes to the api.py? Or there is anothe way we update the `api.py`? @carlosabcs @lhchavez

2022-10-24 12:06 UTC, lhchavez commented
> I was creating a contest using the `omegaup.api.Client` but there I could not modify the`check_plagiarism` field because possibley we don't have it in our omegaup create api. So, I made some changes in the `stuff/venv/lib/python3.8/site-packages/omegaup/api.py` to have those changes and it works. But it is not showing up the changes in the my `git status`. Should I make the revert the changes to the api.py? Or there is anothe way we update the `api.py`? @carlosabcs @lhchavez

oh yeah, we need to automate the update of the pypi package. i just released v2.0.3 https://pypi.org/project/omegaup/, so we can update that from  stuff/requirements.txt and upgrade that with:

```shell
. stuff/venv/bin/activate
python3 -m pip install -r stuff/requirements.txt
```

_but_ turns out that we can't use `omegaup.api`: that requires a working instance of omegaUp, and we won't necessarily have that in the unit tests. this means that we need to insert the rows into the database by hand without the use of that python library.

2022-10-24 12:34 UTC, lhchavez commented
> after that If I try to update the contest using queries, it doesn't do that.

can you elaborate a bit more? what does "doesn't do that" mean? what code did you use to update the contest? what errors did you see? how did you confirm that the `UPDATE` did not work?

2022-10-24 12:36 UTC, MohitOhlyan commented
> > after that If I try to update the contest using queries, it doesn't do that.
> 
> can you elaborate a bit more? what does "doesn't do that" mean? what code did you use to update the contest? what errors did you see? how did you confirm that the `UPDATE` did not work?

I have created a contest using omegaup api. I am using the `mysql` ternmial to see the contest does get created. In the same script after the contest, I execute a query :-
```
 UPDATE Contests
                            SET check_plagiarism = 1
                            WHERE alias = %s;
```
I see in the mysql terminal the the value of `check_plagiarism` does not change. 
But if I run the same query in the mysql terminal it does change it.

2022-10-24 12:37 UTC, MohitOhlyan commented
> > > after that If I try to update the contest using queries, it doesn't do that.
> > 
> > 
> > can you elaborate a bit more? what does "doesn't do that" mean? what code did you use to update the contest? what errors did you see? how did you confirm that the `UPDATE` did not work?
> 
> I have created a contest using omegaup api. I am using the `mysql` ternmial to see the contest does get created. In the same script after the contest, I execute a query :-
> 
> ```
>  UPDATE Contests
>                             SET check_plagiarism = 1
>                             WHERE alias = %s;
> ```
> 
> I see in the mysql terminal the the value of `check_plagiarism` does not change. But if I run the same query in the mysql terminal it does change it.

There were no errors.

2022-10-24 13:36 UTC, MohitOhlyan commented
> > > > > after that If I try to update the contest using queries, it doesn't do that.
> > > > 
> > > > 
> > > > can you elaborate a bit more? what does "doesn't do that" mean? what code did you use to update the contest? what errors did you see? how did you confirm that the `UPDATE` did not work?
> > > 
> > > 
> > > I have created a contest using omegaup api. I am using the `mysql` ternmial to see the contest does get created. In the same script after the contest, I execute a query :-
> > > ```
> > >  UPDATE Contests
> > >                             SET check_plagiarism = 1
> > >                             WHERE alias = %s;
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I see in the mysql terminal the the value of `check_plagiarism` does not change. But if I run the same query in the mysql terminal it does change it.
> > 
> > 
> > There were no errors.
> 
> it _could_ be that there is a second instance of MySQL that is running and the script is picking that up instead of the one that we expect. can you push the PR with all the changes? that way we don't need to be wondering what was going on.
> 
> also, when the script was run, was it run inside the container?

Yea. Sure pushing. Yes it was run inside the container. Another strange thing is that when we run the `get_contests()` we are getting the contest in the results (which should not be the case if the check_plagiarism did not get update). So it seems it is getting updated.

2022-10-25 13:01 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +        cur.execute(UPDATE_CHECK_PLAGIARISM, (alias,))
```suggestion
        cur.execute(UPDATE_CHECK_PLAGIARISM, (alias,))
        dbconn.commit()
```

note that python's sql implementation does not autocommit, so we need to do that manually every time!

2022-10-25 13:37 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +        cur.execute(UPDATE_CHECK_PLAGIARISM, (alias,))
Ohhh yess!!! Thanks for making me remember.

2022-10-25 13:37 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +    client = omegaup.api.Client(api_token=test_constants.API_TOKEN,
Yes. Working on those. I was just testing with it for now. Removing the client code.

2022-10-27 01:11 UTC, MohitOhlyan commented
@lhchavez I have added the python tests. Can you see if the test are what was needed and what else I have to assert? 
Thanks!!!

2022-10-27 12:57 UTC, lhchavez reviewed
we're getting closer!

2022-10-27 12:57 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +LOCAL_DOWNLOADER_DIR = os.path.join(_OMEGAUP_ROOT, "testdata", "")
```suggestion
LOCAL_DOWNLOADER_DIR = os.path.join(_OMEGAUP_ROOT, "testdata")
```

the last component is unneeded

2022-10-27 12:57 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> -                                INNER JOIN Contests c ON c.problemset_id = s.problemset_id
we do want to have these joins be `INNER` , because only contests are supported.

2022-10-27 12:57 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +        # add to the database.
can this be restored?
```suggestion
    # add to the database.
```

2022-10-27 12:57 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +        lang = submission['language']
this is not doing anything since `lang` is not read after this point.

2022-10-27 12:57 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +    acl_id: int = 65551 # Maybe create a New ACL
it's better to avoid randomness in tests (at least for IDs). can all the random IDs be deleted? if they refer to another table (foreign indices) the record in the other table should be created first.

mysql returns the ID of recently created tables so that we don't even need to query it.

2022-10-27 12:57 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +GUID = [
this can be replaced with `f'{i:040x}` (where `i` is a variable that holds a number)

2022-10-27 12:57 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +                    GUID[guid],
```suggestion
                    f'{guid:040x}',
```

2022-10-27 12:57 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +        assert plag
this is only asserting that the set is non-empty, but is there something more we can assert? like do we know that a couple of files are definitely plagiarized? do we know of one file that was not plagiarized? we should assert the existence of the former, and the absence of the latter.

2022-10-27 13:09 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +        assert plag
Should I make a the `run_plagiarism_detector` have a return type which contains the result from copydetect that way we can assert directly all the information? Or it doesn't need to be that way and I can just assert by units.

2022-10-27 13:17 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +        assert plag
Like the count of rows = 5? Can you explain the query with a simple example please?

2022-10-27 13:19 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        # add to the database.
Done. I was testing something, didn't revert it back.

2022-10-27 13:21 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> -                                INNER JOIN Contests c ON c.problemset_id = s.problemset_id
Done. Yea same testing thing happened. I was actually not getting the exact result for a particular problemset. Thanks for reminding.

2022-10-27 13:21 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +LOCAL_DOWNLOADER_DIR = os.path.join(_OMEGAUP_ROOT, "testdata", "")
Done.

2022-10-27 13:21 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        lang = submission['language']
Done.

2022-10-27 13:23 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +    acl_id: int = 65551 # Maybe create a New ACL
So, the problem here is with just `problemset_id` and `alias` right?

2022-10-27 13:25 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +GUID = [
It should be 32 right? or 31? the length of guid is 32

2022-10-27 13:30 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +    acl_id: int = 65551 # Maybe create a New ACL
Can I just assign a particular  `problemset_id` like problemset_id = 10 or does it have to be something else. Because I made sure to have all the other table link up with problemset_id.

2022-10-27 13:39 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +    acl_id: int = 65551 # Maybe create a New ACL
just the `_id`s. ideally let's avoid hardcoding ids: if we add more tests later we need to ensure that there are no conflicts between tests. also, if we re-run the test it will fail because that id has already been used.

2022-10-27 13:39 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +GUID = [
errr, yes, 32

2022-10-27 13:40 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +        assert plag
no, grab all the rows and assert that the guids are the ones that were involved in plagiarism. that way if the detector makes a mistake and flags the wrong guid, the test will fail (correctly) even if it's still 5 rows.

2022-10-27 13:49 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +        assert plag
Okay. We already have that query! I just need to assert it

2022-10-27 13:49 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +GUID = [
Done.

2022-10-27 13:57 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +                    GUID[guid],
Done.

2022-10-27 14:20 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +    acl_id: int = 65551 # Maybe create a New ACL
ah! good point. then we _do_ need to copy the files to a temporary directory at runtime after all.

2022-10-27 14:23 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +    acl_id: int = 65551 # Maybe create a New ACL
I think we are already doing that! Or did you mean the something else? Like the testdata files?

2022-10-27 14:32 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +    acl_id: int = 65551 # Maybe create a New ACL
Also, if we try to run the test on the same database with the `--purge` then it will return multiple `Contests`. I which case we cannot store the `alias` of the contest that was ran `previously`.

2022-10-28 04:43 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +    acl_id: int = 65551 # Maybe create a New ACL
yes, that's why we do need to use random guids instead of sequential. another option is to use `REPLACE` instead of `INSERT`.

2022-10-28 07:11 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +    acl_id: int = 65551 # Maybe create a New ACL
Okay. I'll try with random guid's. I'll make the changes to the script as well for that. Will also try `REPLACE`.

2022-10-28 22:57 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +        assert plag
I have added some assertion! Let me know if we need more for this PR. I can continue adding more tests that I can think of like having adding some non-AC submission being included as well When creating the submission so that we can assert that those are not involved also.

2022-10-28 22:57 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +    acl_id: int = 65551 # Maybe create a New ACL
I used the REPLACE and we can now run the tests again and again! Thanks!

2022-10-29 15:43 UTC, MohitOhlyan commented
@lhchavez I have done the suggested changes. It good for a review. Thanks.

2022-10-29 16:05 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +        assert p not in bad_sub_ids
```suggestion
    for submission_id in good_submission_ids:
        assert submission_id not in plagiarized_submission_ids
    for submission_id in bad_submission_ids:
        assert submission_id in plagiarized_submission_ids
```

2022-10-29 16:19 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +no_of_problems: int = 3  # same as above case
Okay.

2022-10-29 16:19 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +'''
Okay. On it.

2022-10-29 16:21 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +        problemsets_id: List[List[int]] = typing.cast(List[List[int]],
Done.

2022-10-29 16:21 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +    problemset_id = problemsets_id[0][0]
Done.

2022-10-29 16:22 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +        dbconn.conn.commit()
Done.

2022-10-29 16:26 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +
Done.

2022-10-29 16:26 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +    """
Done.

2022-10-29 16:43 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +'''
Done.

2022-10-29 16:53 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +                GUID.append(f'{guid:032x}')
Done.

2022-10-29 16:54 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +                    bad_sub_ids.add((sub_id_2, sub_id_1), )
Yes. I was thinking maybe we need to increase the no of users and no. of problems later of for tests. But yes I will hardcode them for now.

2022-10-29 16:54 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +                    ))
Sure.

2022-10-29 17:14 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +                    ))
It throws a error:- `Cannot delete or update a parent row: a foreign key constraint fails (`omegaup`.`Plagiarisms`, CONSTRAINT `fk_ps_submission_id_1` FOREIGN KEY (`submission_id_1`) REFERENCES `Submissions` (`submission_id`))`

2022-10-29 17:19 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        updated_result.append(
No, it only return one pair. Only (1,2) will be returned.

2022-10-29 17:20 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        updated_result.append(
But is very random, sometimes the highest is first sometimes the lowest.

2022-10-29 17:21 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +    assert plag
Done.

2022-10-29 17:23 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +    assert get_contests_detector
So, should remove this right?

2022-10-29 17:23 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +        updated_result.append(
let's remove the randomness: let's swap the IDs if they are out of order

2022-10-29 17:27 UTC, MohitOhlyan commented on stuff/cron/plagiarism_detector.py
> +        updated_result.append(
Got it.

2022-10-29 17:52 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +    assert get_contests_detector
not remove it but move it to another function. each `test_` function should test just one piece of functionality and follow the Arrange, Act, Assert pattern.

2022-10-29 17:54 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +                    ))
gotcha, in that case let's try running the following in the dbconn fixture:

```sql
TRUNCATE TABLE Plagiarisms;
TRUNCATE TABLE Submissions;
```

and so on for all tables that complain until the errors stop happening.

2022-10-29 23:17 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +    # any better idea how we can get the current contest_id apart from executing a sql query?
Done.

2022-10-30 02:37 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +                    ))
When I try to truncate Submissions, it gives this error :-
```
 Cannot truncate a table referenced in a foreign key constraint (`omegaup`.`Submission_Log`, CONSTRAINT `fk_slr_submission_id`)
 ```
And if I try to truncate `Submission_Log` too, it still gives the error. 
This is how I am truncating:-
```
with dbconn.cursor() as cur:
        cur.execute('''
                TRUNCATE TABLE Submissions;
                ''')
```

2022-10-30 02:49 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +                    ))
keep going until you reach a table that doesn't throw errors. you'll need to truncate the dependent tables before.

if there is a dependency cycle (e.g. Runs and Submissions depend on each other), we may need to disable foreign checks: https://github.com/omegaup/omegaup/blob/d3bd377aa025a0686f0576067f4cb52a68d941fd/frontend/tests/Utils.php#L276

2022-10-30 03:19 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +                    ))
If I disable the foreign key check then we don't need to truncate right? 
I can re-enable the foreign key check after the transaction!

2022-10-30 03:21 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +                    ))
no, we need to reenable it immediately after truncating. otherwise we leave the database in a terrible state and certain classes of bugs won't be picked up by the tests, making them useless up to a certain point.

2022-10-30 03:28 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +        assert p not in bad_sub_ids
Done.

2022-10-30 03:35 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +                    ))
Got it. First disable foreign key check, then truncate then ,enable and then transaction.

2022-10-30 04:01 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +                    ))
It's working fine till I truncate`Submissions_Log` But as soon as I truncate `Submissions`, The entire terminal get's freeze up. Maybe just truncate `Plagiarisms`, `Submission_Log` does the job?

2022-10-30 04:53 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +no_of_problems: int = 3  # same as above case
Done.

2022-10-30 04:54 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +                    bad_sub_ids.add((sub_id_2, sub_id_1), )
I have hardcoded the ids. and did as you suggested. Also, we need to do this for pair of matches. Should I hardcode those too?

2022-10-30 08:35 UTC, MohitOhlyan commented
Getting a error by linter  for `lastrowid` as :-
[mypy] error: "MySQLCursor" has no attribute "lastrowid" 
@lhchavez

2022-10-30 13:59 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +                    bad_sub_ids.add((sub_id_2, sub_id_1), )
can you elaborate why we need to do this for pairs of matches? the suggestions already consider converting the pairs into a flat set to know which submission IDs are present at least once in the plagiarism graph so that we don't need to do this for pairs.

2022-10-30 14:00 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +                    ))
> Getting a error by linter for `lastrowid` as :- [mypy] error: "MySQLCursor" has no attribute "lastrowid" @lhchavez

add the `--no-verify` flag for now to let GitHub push the change to see the errors.

2022-10-30 14:57 UTC, lhchavez commented
> Getting a error by linter for `lastrowid` as :- [mypy] error: "MySQLCursor" has no attribute "lastrowid" @lhchavez

you can run `git apply` and paste this:

```diff
diff --git a/stuff/mysql/connector/cursor.pyi b/stuff/mysql/connector/cursor.pyi
index 8c3372378..d9fa04e01 100644
--- a/stuff/mysql/connector/cursor.pyi
+++ b/stuff/mysql/connector/cursor.pyi
@@ -3,6 +3,8 @@ from typing import Any, Iterator, Iterable, Mapping, Optional, Sequence, Text, T
 
 
 class BaseCursor:
+    lastrowid: int
+
     def close(self) -> None:
         ...
```

and then press <Enter> followed by Ctrl+D.

2022-10-30 15:51 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +                    bad_sub_ids.add((sub_id_2, sub_id_1), )
Okay. We want to assert the pair because, let's say we have 5 matches (1, 4), (2, 5), (3.6) (3, 9), (6,9). so, in the flat set we will have the flat set as :- [1,2,3,4,5,6,9] and that works for each guid. But we want to also check that (1,5) is not in the matches. Similarily we want to assert that we don't have plagiarism match for submission in different problems. 
That's why we will have pairs of expected submission id pairs and we will assert if those pairs are present.

2022-10-30 15:51 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +                    ))
Okay.

2022-10-30 16:31 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +                    bad_sub_ids.add((sub_id_2, sub_id_1), )
it's fine if (1, 5) is not in the set for now. the only thing that matters is that both 1 and 5 were implicated in the plagiarism graph, although maybe not plagiarized directly. what we do want to assert is that 7 and 8 are completely innocent.

same thing happens for submissions of another problem: we just assert that the set of plagiarized ids is _exactly_ the set `set(1, 2, 3, 4, 5, 6, 9)`. this implies that the innocent submissions of the same problem and submissions of another problem can never be considered plagiarized!

one implication of this: we need to translate the hardcoded GUIDs into the inserted submission ids and use that mapping to build the set of expected plagiarized submissions.

in a different PR we can tweak this logic to translate the plagiarism graph into disjoint sets, so that we test that the plagiarism graph now becomes `set(set(1,4), set(2,5), set(3,6,9))`. we can add a `# TODO: convert to disjoint sets for better testing` comment so that we don't forget to do this in the future.

2022-10-30 18:36 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +            temp_submission_id_1, temp_submission_id_2 = temp_submission_id_2, temp_submission_id_1
```suggestion
        submission_id_1 = guid_and_submission_id_dict[os.path.splitext(
            os.path.basename(result.test_filename))[0]]
        submission_id_2 = guid_and_submission_id_dict[os.path.splitext(
            os.path.basename(result.reference_filename))[0]]
        score_1 = result.test_score
        score_2 = result.reference_score
        code_1 = result.highlighted_test_code
        code_2 = result.highlighted_reference_code
        if submission_id_1 > submission_id_2):
            submission_id_1, submission_id_2 = submission_id_2, submission_id_1
            score_1, score_2 = score_2, score_1
            code_1, code_2 = code_2, code_1
```

2022-10-30 18:36 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +                }),
```suggestion
                score_1=int(100 * score_1),
                score_2=int(100 * score_2),
                submission_id_1=submission_id_1,
                submission_id_2=submission_id_2,
                contents=json.dumps({
                    'file1': get_range(code_1.split('\n')),
                    'file2': get_range(code_2.split('\n'))
                }),
```

2022-10-30 18:36 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +    global GUID  # needed for assertions
```suggestion
```

we shouldn't use globals. it's better to declare a [`@dataclasses.dataclass`](https://docs.python.org/3/library/dataclasses.html) and return that.

2022-10-30 18:36 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +
```suggestion
```

global variables are widely considered to be an [anti-pattern](https://softwareengineering.stackexchange.com/a/148109) that should be avoided.

2022-10-30 18:36 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +    submission_id: int = random.randint(100, 500)  # counter for submission_id
```suggestion
```

let's avoid randomness for ids.

2022-10-30 18:36 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +    global contest_id
```suggestion
```

2022-10-30 18:36 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +                ''')
```suggestion
    with dbconn.cursor() as cur:
        cur.execute('''
                SET foreign_key_checks = 0;
                TRUNCATE TABLE Plagiarisms;
                TRUNCATE TABLE Submission_Log;
                SET foreign_key_checks = 1;
                ''')
```

we can run this in a single transaction.

2022-10-30 18:36 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +    global contest_id
```suggestion
    create_contest(dbconn)
```

all tests should be independent of each other and should be able to be run independently.

2022-10-30 18:36 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +    global first_submission_id
```suggestion
```

2022-10-30 18:36 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +        assert match not in plagiarized_matches
```suggestion
    # TODO: Convert the graph of plagiarized submissions into disjoint sets and
    # check groups of plagiarized submissions instead of only whether a submission
    # was plagiarized or not.
    assert plagiarized_matches == set((
      submission_ids[f'{0:032x}'],
      submission_ids[f'{1:032x}'],
      submission_ids[f'{2:032x}'],
      submission_ids[f'{3:032x}'],
      submission_ids[f'{4:032x}'],
      submission_ids[f'{5:032x}'],
      submission_ids[f'{8:032x}'],
    ))
```

where `submission_ids` is a mapping from GUIDs to submission_ids.

2022-10-30 18:36 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +    first_submission_id = submission_ids_for_contest[0]
in the Arrange, Act, Assert pattern, what is this testing? where are the assertions?

2022-10-31 05:40 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +                    bad_sub_ids.add((sub_id_2, sub_id_1), )
Okay. Got it.

2022-10-31 05:43 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +
Yes. I was thinking not to use too. I just wrote them so that you can give a better solution :). I wasn't able to think of the dataclass.

2022-10-31 05:43 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +    submission_id: int = random.randint(100, 500)  # counter for submission_id
Ohh, we are not using this. I think it might have just stayed in. Thanks I didn't notice

2022-10-31 05:47 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +    first_submission_id = submission_ids_for_contest[0]
Okay, this was just so that we could get the first submission Id and pass it to other function but we won't need it now.

2022-10-31 13:43 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +        if submission_id_1 > submission_id_2):
```suggestion
        if submission_id_1 > submission_id_2:
```

note that Python conditionals don't use parentheses.

2022-10-31 22:47 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +                ''')
This gives a error. 
`mysql.connector.errors.OperationalError: MySQL Connection not available.`

2022-10-31 22:47 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +                ''')
And the old code works.

2022-10-31 23:16 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +    global GUID  # needed for assertions
I used a dataclass now but if I return that class object to test_get_contest then only that test can have access to that. 
Do have to declare a object of the class outside the test_get_contest to access the object in other tests?

2022-10-31 23:18 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +    global contest_id
Understood.

2022-10-31 23:18 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +        assert match not in plagiarized_matches
Done.

2022-11-01 01:53 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +def test_plagiarism_detector(dbconn: lib.db.Connection) -> None:
can this be split again in two smaller tests? each can call `create_contest` to create a brand new contest. truncate any table that complains about alias unique collisions.

2022-11-01 01:54 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +                ''')
can we at least have all of the `cur.execute` inside the same `with` block?

2022-11-01 01:55 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +    global GUID  # needed for assertions
you should be able to call that once per test!

2022-11-01 01:55 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +def test_plagiarism_detector(dbconn: lib.db.Connection) -> None:
yes. But then how would I be able to access the contest_id and GUID in the other tests? I would have to create a `Contest` class object on a global level to access that object.

2022-11-01 01:56 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +def test_plagiarism_detector(dbconn: lib.db.Connection) -> None:
you should be able to call `create_contest` in both.

2022-11-01 01:58 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +    global GUID  # needed for assertions
Okay. If I call the make a object in `def create_contest` and return it. Then in `test_create_contest`. I can have the object but that object doesn't work in `test_submission_id`. Or is that I don't have to create a object Since it is a dataclass and can be called?

2022-11-01 02:01 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +def test_plagiarism_detector(dbconn: lib.db.Connection) -> None:
Updating soon.

2022-11-01 02:01 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +    global GUID  # needed for assertions
why doesn't it work in the other test? in theory they are independent contests, so one should not prevent the other from working.

also, what does "doesn't work" entail? can you push that code so that we see the exact error in GitHub? (paraphrasing errors is suboptimal. if possible, next time copy and paste the full error so that we both see exactly the same thing to avoid guesswork).

2022-11-01 02:02 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +                ''')
Yes  but it throws the error when I do that.

2022-11-01 02:06 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +    global GUID  # needed for assertions
Okay so it's solved now. I was creating a object of the class Which I shouldn't have since it's a dataclass.

2022-11-01 02:06 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +                ''')
Yea sure. Just give me 2 mins please.

2022-11-01 02:29 UTC, lhchavez reviewed
can you also revert the changes to `stuff/hook_tools`?

```shell
(cd stuff/hook_tools && git reset --hard 52223530bba28552e5ed935b068a7858420822a7) && git commit stuff/hook_tools -m "revert hook_tools"
```

2022-11-01 02:29 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +    GUID: List[str] = dataclasses.field(default_factory=list)
small nit:

```suggestion
    guids: List[str] = dataclasses.field(default_factory=list)
```

fields are normally lowercase. lists also are in plural.

2022-11-01 02:29 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +    # contest = Contest()
```suggestion
    guids: List[str] = []
    contest = Contest()
```

2022-11-01 02:29 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +    Contest.GUID = GUID
```suggestion
    contest.guids = guids
    return contest
```

2022-11-01 02:29 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +    GUID = Contest.GUID
```suggestion
    contest = create_contest(dbconn)
```

2022-11-01 02:29 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +    assert contest_id in contests
```suggestion
    assert contest.contest_id in contests
```

2022-11-01 02:29 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +        contest['contest_id'] for contest in get_contests_detector
```suggestion
        c['contest_id'] for c in get_contests_detector
```

otherwise this will overwrite the other `contest`.

2022-11-01 02:29 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +    submission_ids = Contest.submission_ids
```suggestion
    contest = create_contest(dbconn)
```

2022-11-01 02:29 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +        dbconn, Contest.contest_id)
```suggestion
    contest = create_contest(dbconn)
    submissions = cron.plagiarism_detector.get_submissions_for_contest(
        dbconn, contest.contest_id)
```

2022-11-01 02:29 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +    Contest.submission_ids = submission_ids
```suggestion
        assert submission['guid'] in contest.guids
```

2022-11-01 02:31 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +                ''')
```suggestion
        cur.execute('SET foreign_key_checks = 0;')
        cur.execute('TRUNCATE TABLE Plagiarisms;')
        cur.execute('TRUNCATE TABLE Submission_Log;')
        cur.execute('SET foreign_key_checks = 1;')
```

ooh sorry, this is what i meant: share the `with`, but unshare the `cur.execute`.

2022-11-01 02:33 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +        dbconn.conn.commit()
```suggestion
```

we probably don't need this if we truncate the table above.

2022-11-01 02:33 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +    global GUID  # needed for assertions
hmm you _should_ be able to create objects of that class. left a bunch of comments as to how to achieve that.

2022-11-01 03:00 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +                ''')
Done.

2022-11-01 14:25 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +        dbconn.conn.commit()
Done.

2022-11-01 14:48 UTC, MohitOhlyan commented
@lhchavez the python tests are not passing or even begin cancelled after hours of running. I have pulled from the main repository and still the same thing. Can you please see what is causing this?

2022-11-02 03:56 UTC, MohitOhlyan commented
> @lhchavez the python tests are not passing or even begin cancelled after hours of running. I have pulled from the main repository and still the same thing. Can you please see what is causing this?

It's being happening after reverting the hook tools.

2022-11-02 12:45 UTC, lhchavez commented
> > @lhchavez the python tests are not passing or even begin cancelled after hours of running. I have pulled from the main repository and still the same thing. Can you please see what is causing this?
> 
> It's being happening after reverting the hook tools.

it's extremely unlikely that it's related. the first commits in this PR used to have the current hook tools and they had no issues. other commits that have the current hook tools also have no issue.

2022-11-02 12:50 UTC, MohitOhlyan commented
> > > @lhchavez the python tests are not passing or even begin cancelled after hours of running. I have pulled from the main repository and still the same thing. Can you please see what is causing this?
> > 
> > 
> > It's being happening after reverting the hook tools.
> 
> it's extremely unlikely that it's related. the first commits in this PR used to have the current hook tools and they had no issues. other commits that have the current hook tools also have no issue.

Okay. It's only after we revereted by back that it started to happen. And I see that the python tests get's struck on `test_plagiarism_detector`. Maybe it's a infinite loop so I tried to search for it in local system but couldn't locate it as the tests pass in my system.

2022-11-02 14:11 UTC, lhchavez commented
> > > > @lhchavez the python tests are not passing or even begin cancelled after hours of running. I have pulled from the main repository and still the same thing. Can you please see what is causing this?
> > > 
> > > 
> > > It's being happening after reverting the hook tools.
> > 
> > 
> > it's extremely unlikely that it's related. the first commits in this PR used to have the current hook tools and they had no issues. other commits that have the current hook tools also have no issue.
> 
> Okay. It's only after we revereted by back that it started to happen. And I see that the python tests get's struck on `test_plagiarism_detector`. Maybe it's a infinite loop so I tried to search for it in local system but couldn't locate it as the tests pass in my system.

yeah, it's one of those [spurious correlations](https://www.tylervigen.com/spurious-correlations), where two things just happen to occur at the same time that have no relationship between each other.

what happens is that we were using the main database instead of the test databse, so MySQL got stuck because it couldn't correctly fix its own state. after using the test database things look a lot better.

2022-11-02 14:16 UTC, lhchavez reviewed
ok i think we're almost done with this PR! to minor things more and we can merge it :tada:

2022-11-02 14:16 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +        assert submission['guid'] in contest.guids
```suggestion
    guids = set(submission['guid'] for submission in submissions)
    assert guids == set(contest.guids)
```

this is more robust because it also checks that there are no unexpected GUIDs.

2022-11-02 14:36 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +    ))
Yes I am already working on those.

2022-11-02 14:36 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +        assert submission['guid'] in contest.guids
Got it!!

2022-11-02 14:37 UTC, MohitOhlyan commented on stuff/cron/testing/test_plagiarism_detector.py
> +    ))
Should I include those in this PR only?

2022-11-02 14:38 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +    ))
yes please. the bare minimum to test the functionality for this PR, we can make it better later.

2022-11-02 14:38 UTC, MohitOhlyan commented
> 

Understood. I didn't knew we had a test database.

2022-11-03 13:26 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +        cur.execute(
can we make a single query to this table that gathers all the columns? we can build all the necessary variables and sets from that (it also helps with the linter error above).

2022-11-03 13:27 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +        assert json.loads(content['contents'])['file1'] in expected_ranges_1
can we convert all lists to tuples so that we can do `==` instead of `in`? that way we have way stronger results.

2022-11-03 13:30 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +    expected_ranges_1 = [[0, 41], [0, 33, 33, 39, 39, 76],
hmm this is going to be a bit confusing. how should we interpret the ranges in the second case? (`[0, 33, 33, 39, 39, 76]`?) is it ranges [0, 33], [33, 39], [39, 76]? if so, can we make the output match that expectation? in other words

```python
expected_ranges = set((
  ((0, 41), ),
  ((0, 33), (33, 39), (39, 76)),
  ...,
))
```

2022-11-03 13:30 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +    # notice both ranges are same due to exact same files being present
if  both ranges are the same, let's just declare them once.

2022-11-07 06:24 UTC, MohitOhlyan commented
@lhchavez Any more tests to add?

2022-11-07 08:12 UTC, lhchavez commented on stuff/cron/testing/test_plagiarism_detector.py
> +        for i in range(0, len(range_of_lines), 2):
is there any way in which we can do this before saving the list to the database?

2022-11-09 02:04 UTC, lhchavez approved these changes
🎉 there's still one more thing left, but let's merge it now that it's in good shape!

thanks for persevering!

2022-11-09 02:04 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +        if END in line:
ideally instead of adding the numbers to a flat list, we should keep track of the last region start as a variable, and when the `END` is found, we can call

```python
code_range_list.append((last_start_line, line_number))
```

but let's add that as a `TODO` for now just to be able to merge this PR!

2022-11-09 02:04 UTC, lhchavez commented on stuff/cron/plagiarism_detector.py
> +        # We have to check for END separetly so that there is always a end for a start
```suggestion
        # TODO: replace this with
        # code_range_list.append((last_start_line, line_number))
```

2022-11-09 02:18 UTC, merged