Parental Token Verification
omegaup/omegaup pull request #6773
Opened 2022-09-30 06:28 UTC by anmode

# Descripción
Create an entrypoint to verify the parent token.

# Checklist:

- [x] El código sigue la [guía de
      estilo](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) de
      omegaUp.
- [x] Se corrieron todas las pruebas y pasaron.
- [x] Si se está agregando funcionalidad nueva, se agregaron pruebas.
- [x] Si el cambio es grande (> 200 líneas), hay que intentar partirlo en
      varios pull requests. De preferencia uno para los controladores + phpunit
      y luego otro para la interfaz.

2022-09-30 06:40 UTC, pabo99 commented on frontend/server/src/Controllers/User.php
>  }
This function should be placed in the `\OmegaUp\DAO\Users.php` file

2022-10-07 06:05 UTC, pabo99 commented on frontend/server/src/Controllers/User.php
> +                $user->parent_email_id = $r->user->main_email_id;
Here we have missmatched types, `main_email_id` is an integer and `parent_email_id` is a string. 

I am affraid we need to fix the type in a new script. I have already create the PR #6781, now you have to wait until this new PR is approved and merged with main branch.

2022-10-07 16:21 UTC, anmode commented on frontend/server/src/Controllers/User.php
> +                $user->parent_email_id = $r->user->main_email_id;
Ohh Okay!! I have implemented all the suggestions. and got the points

2022-10-10 16:08 UTC, lhchavez commented on frontend/server/src/Controllers/User.php
> +            'token',
```suggestion
            'parental_verification_token',
```

"token" can mean a lot of things, so let's try to be explicit about its purpose.

2022-10-10 16:08 UTC, lhchavez commented on frontend/server/src/Controllers/User.php
> +                self::$log->info(
```suggestion
                self::$log->error(
```

although we shouldn't be catching exceptions in the code! that makes the request succeed even if it shouldn't have. can the `try`/`catch` be removed?

2022-10-10 16:08 UTC, lhchavez commented on frontend/server/src/DAO/Users.php
> +    public static function getUserDataByParentalToken(string $token): ?int {
nit:

```suggestion

    public static function getUserDataByParentalToken(string $token): ?int {
```

2022-10-10 16:08 UTC, lhchavez commented on frontend/tests/controllers/UserRegistrationTest.php
> +
```suggestion
```

we don't use `use`: every reference should be fully qualified.

2022-10-10 16:08 UTC, lhchavez commented on frontend/www/users/verification_parental_token.php
> +    fn (\OmegaUp\Request $r) => \OmegaUp\Controllers\User::getIndexDetailsForTypeScript(
this shouldn't re-use the index details. can this instead render a new view that only has the parental verification token field (and whatever else it needs to perform the validation)?

2022-10-11 13:09 UTC, anmode commented on frontend/www/users/verification_parental_token.php
> +    fn (\OmegaUp\Request $r) => \OmegaUp\Controllers\User::getIndexDetailsForTypeScript(
Sure!!

2022-10-12 15:40 UTC, anmode commented
I tried to addressed all suggestions! Got some pslam errors.

2022-10-13 05:10 UTC, pabo99 commented on frontend/server/src/Controllers/User.php
> +                throw new \OmegaUp\Exceptions\NotFoundException('userNotExist');
It still remains the exception `NotFoundException`, it should be `UnauthorizedException`

2022-10-13 05:10 UTC, pabo99 commented on frontend/server/src/Controllers/User.php
> +            $user = \OmegaUp\DAO\Users::getByPK($userId);
You didn't add this condition yet

2022-10-13 05:10 UTC, pabo99 commented on frontend/tests/controllers/UserRegistrationTest.php
> +
This line should be removed

2022-10-13 05:23 UTC, anmode commented
Oops! Sorry... Now i have implemented all the suggestions

2022-10-13 05:24 UTC, pabo99 reviewed
This PR requires some unit tests, but you should wait for PR https://github.com/omegaup/omegaup/pull/6781 is approved

2022-10-13 05:24 UTC, pabo99 commented on frontend/server/src/Controllers/User.php
> +     * @omegaup-request-param string $token
The name of this param has changed, so you need update the declaration:
```suggestion
     * @omegaup-request-param string $parental_verification_token
```

2022-10-13 05:24 UTC, pabo99 commented on frontend/server/src/Controllers/User.php
> +    public static function getVerificationParentalTokenDetailsScript(
Nit:
```suggestion
    public static function getVerificationParentalTokenDetailsForTypeScript(
```

2022-10-13 05:24 UTC, pabo99 commented on frontend/server/src/Controllers/User.php
> +        );
Now this param shouldn't be optional, so you can use the function `ensureString` instead:
```suggestion
        $token = $r->ensureString(
            'parental_verification_token',
            validator: fn (string $token) => preg_match(
                '/^[a-zA-Z0-9]{25}$/',
                $token
            ) === 1
        );
```

2022-10-13 05:24 UTC, pabo99 commented on frontend/server/src/Controllers/User.php
> +        if (!is_null($token)) {
This consition could be removed because now the token is not optional:
```suggestion
```

2022-10-13 05:24 UTC, pabo99 commented on frontend/server/src/Controllers/User.php
> +                    'omegaupTitleParentalVerificationToken'
You need add this translation in the localization files:
`en.lang`:
```
omegaupTitleParentalVerificationToken = "Parental verification token"
```
`es.lang`:
```
omegaupTitleParentalVerificationToken = "Token de verificación parental"
```
`pt.lang`:
```
omegaupTitleParentalVerificationToken = "Token de verificação dos pais"
```

2022-10-16 14:22 UTC, lhchavez requested changes
can a test be added? seems like there's a way to verify arbitrary users without having the token.

2022-10-16 14:22 UTC, lhchavez commented on frontend/server/src/Controllers/User.php
> +        }
let's remove this. otherwise if there is an exception we just ignore them and keep moving!

also, the code in the `try` will never throw this exception, so this `catch` is not doing anything.

2022-10-16 14:22 UTC, lhchavez commented on frontend/server/src/Controllers/User.php
> +            $user = \OmegaUp\DAO\Users::getByPK($userId);
```suggestion
        $user = \OmegaUp\DAO\Users::getByPK($userId);
```

2022-10-16 14:22 UTC, lhchavez commented on frontend/server/src/Controllers/User.php
> +            $userId = \OmegaUp\DAO\Users::getUserDataByParentalToken($token);
```suggestion
        $userId = \OmegaUp\DAO\Users::getUserDataByParentalToken($token);
```

2022-10-16 14:22 UTC, lhchavez commented on frontend/server/src/Controllers/User.php
> +        $parentalVerificationToken = false;
```suggestion
        $hasParentalVerificationToken = false;
```

let's use boolean-sounding names for booleans.

2022-10-16 14:22 UTC, lhchavez commented on frontend/server/src/Controllers/User.php
> +                    'parentalVerificationToken' => $parentalVerificationToken,
```suggestion
                    'hasParentalVerificationToken' => $hasParentalVerificationToken,
```

2022-10-16 14:22 UTC, lhchavez commented on frontend/server/src/Controllers/User.php
> +            \OmegaUp\DAO\Users::update($user);
where is the verification happening? this looks like the verification is happening unconditionally, so anybody that opens this page can "verify" someone.

2022-10-19 23:33 UTC, anmode commented
> can a test be added? seems like there's a way to verify arbitrary users without having the token.

Okay but the test requires #6743 to be merged first.

2022-10-19 23:35 UTC, anmode commented on frontend/server/src/Controllers/User.php
> +            \OmegaUp\DAO\Users::update($user);
At L4631.....with the received token. are more validation required??

2022-10-20 00:07 UTC, lhchavez commented on frontend/server/src/DAO/Users.php
> +    public static function getUserDataByParentalToken(string $token): ?int {
```suggestion
    public static function findByParentalToken(string $token): ?\OmegaUp\DAO\VO\Users {
```

2022-10-20 00:07 UTC, lhchavez commented on frontend/server/src/DAO/Users.php
> +                      u.user_id
```suggestion
        $fields = join(
            ', ',
            array_map(
                fn (string $field): string => "u.{$field}",
                array_keys(
                    \OmegaUp\DAO\VO\Users::FIELD_NAMES
                )
            )
        );                   
        $sql = "SELECT
                      {$fields}
```

this way we can use the same technique used by `findByUsername` above to avoid two database roundtrips.

2022-10-20 00:07 UTC, lhchavez commented on frontend/server/src/Controllers/User.php
> +            \OmegaUp\DAO\Users::update($user);
oops, you're right. that should be enough.

2022-10-20 04:52 UTC, anmode commented on frontend/server/src/DAO/Users.php
> +                      u.user_id
ohh yes yes!

2022-10-26 17:22 UTC, heduenas commented
@anmode seems like you are unblocked now to add the test?

2022-10-30 04:07 UTC, anmode commented
> @anmode seems like you are unblocked now to add the test?

I am creating that!!

2022-11-02 14:24 UTC, lhchavez commented
> > @anmode seems like you are unblocked now to add the test?
> 
> I am creating that!! but This PR test failed needs a review.

you should be able to fix the linter errros before a review happens (although if you have specific questions, don't hesitate to ask!)

2022-11-02 17:17 UTC, anmode commented
> Member

Sure!! I will keep in mind this thing. I try to solve lint errors

2022-11-15 16:35 UTC, lhchavez commented on frontend/server/src/Controllers/User.php
> + * @psalm-type VerificationParentalTokenDetailsPayload=array{hasparentalVerificationToken: bool}
```suggestion
 * @psalm-type VerificationParentalTokenDetailsPayload=array{hasParentalVerificationToken: bool}
```

2022-11-15 16:35 UTC, lhchavez commented on frontend/server/src/Controllers/User.php
> +    \OmegaUp\Controllers\User::$urlHelper = new \OmegaUp\UrlHelper();
```suggestion
\OmegaUp\Controllers\User::$urlHelper = new \OmegaUp\UrlHelper();
```

this doesn't seem related

2022-11-15 16:35 UTC, lhchavez commented on frontend/tests/controllers/UserRegistrationTest.php
> +     * User 13 and it's account link to the parent account
```suggestion
     * User 13 and its account link to the parent account 
```

2022-11-15 16:35 UTC, lhchavez commented on frontend/www/js/omegaup/common/index.ts
> +  if (parentPayload.hasparentalVerificationToken) {
```suggestion
  if (parentPayload.hasParentalVerificationToken) {
```

2022-11-18 17:06 UTC, anmode commented on frontend/server/src/Controllers/User.php
> +    \OmegaUp\Controllers\User::$urlHelper = new \OmegaUp\UrlHelper();
Ig my editor does these linting error or when i run /stuff/lint.sh. I'll undo all lint changes asap

2022-11-24 23:49 UTC, pabo99 commented on frontend/server/src/Controllers/User.php
> +                '/^[a-zA-Z0-9]{25}$/',
```suggestion
                '/^[a-zA-Z0-9]{24}$/',
```
(I don't know why the generated token only contains 24 characters)

2022-11-24 23:49 UTC, pabo99 commented on frontend/server/src/Controllers/User.php
> +        $userId = \OmegaUp\DAO\Users::findByParentalToken($token);
Here you are getting the whole User object, not only `userId`
```suggestion
        $user = \OmegaUp\DAO\Users::findByParentalToken($token);
```

2022-11-24 23:49 UTC, pabo99 commented on frontend/server/src/Controllers/User.php
> +        if (is_null($userId)) {
Nit:
```suggestion
        if (is_null($user)) {
```

2022-11-24 23:49 UTC, pabo99 commented on frontend/server/src/Controllers/User.php
> +        }
You have already the User information, so it could be removed
```suggestion
```

2022-11-24 23:49 UTC, pabo99 commented on frontend/server/src/Controllers/User.php
> +            return [
This could be fixed with the linter, anyways, you could fix it manually
```suggestion
        $user->parent_email_id = $r->user->main_email_id;
        $user->parent_verified = true;
        $user->parental_verification_token = null;

        \OmegaUp\DAO\Users::update($user);

        $hasParentalVerificationToken = true;

        return [
```

2022-11-24 23:49 UTC, pabo99 commented on frontend/server/src/Controllers/User.php
> +            ];
Nit:
```suggestion
        ];
```

2022-11-24 23:49 UTC, pabo99 commented on frontend/tests/controllers/UserRegistrationTest.php
> +            $this->assertEquals('mailInUse', $e->getMessage());
Nit:
```suggestion
            $this->assertSame('mailInUse', $e->getMessage());
```

2022-11-24 23:49 UTC, pabo99 commented on frontend/tests/controllers/UserRegistrationTest.php
> +        $this->assertEquals($email, $email_user->email);
```suggestion
        $this->assertSame($identity->username, $username);
        $this->assertSame($email, $email_user->email);
```

2022-11-24 23:49 UTC, pabo99 commented on frontend/tests/controllers/UserRegistrationTest.php
> +            $this->assertEquals('mailInUse', $e->getMessage());
```suggestion
            $this->assertSame('mailInUse', $e->getMessage());
```

2022-11-24 23:49 UTC, pabo99 commented on frontend/server/src/DAO/Users.php
> +                    LIMIT 1';";
Nit:
```suggestion
                    LIMIT 1;";
```

2022-11-24 23:49 UTC, pabo99 commented on frontend/server/src/DAO/Users.php
> +        return \OmegaUp\MySQLConnection::getInstance()->GetOne(
This function should return the whole object for User, so you can use the function `GetRow` instead of `GetOne`
```suggestion
        $result = \OmegaUp\MySQLConnection::getInstance()->GetRow(
```

2022-11-24 23:49 UTC, pabo99 commented on frontend/tests/controllers/UserRegistrationTest.php
> +        ['identity' => $identity] = \OmegaUp\Test\Factories\User::createUser(
Here you could use `User` object instead of `Identity`
```suggestion
        ['user' => $user] = \OmegaUp\Test\Factories\User::createUser(
```

2022-11-24 23:49 UTC, pabo99 commented on frontend/tests/controllers/UserRegistrationTest.php
> +        $login = self::login($identity);
The parent is the user who will verify the token, so you could create a new account for that new user, and login with this one:
```suggestion
        [
            'user' => $parentUser,
            'identity' => $parentIdentity,
        ] = \OmegaUp\Test\Factories\User::createUser();

        $login = self::login($parentIdentity);
```

2022-11-24 23:49 UTC, pabo99 commented on frontend/tests/controllers/UserRegistrationTest.php
> +        //verify token belongs to child accounts ---?
This function should receive the token, so you need to add it in the request:
```suggestion
        $payload = \OmegaUp\Controllers\User::getVerificationParentalTokenDetailsForTypeScript(
            new \OmegaUp\Request([
                'auth_token' => $login->auth_token,
                'parental_verification_token' => $user->parental_verification_token,
            ])
        )['templateProperties']['payload'];

```

2022-11-24 23:49 UTC, pabo99 commented on frontend/tests/controllers/UserRegistrationTest.php
> +        );
The field `hasParentalVerificationToken` should return a boolean, so you could use the following assertion:
```suggestion
        $this->assertTrue($payload['hasParentalVerificationToken']);
```

Also you could add a new assertion, where both users are linked by `email_id`:
```php

        $updatedUser = \OmegaUp\DAO\Users::getByPK($user->user_id);

        // Assert both accounts are linked by email_id
        $this->assertSame(
            $updatedUser->parent_email_id,
            $parentUser->main_email_id
        );
```

2022-11-24 23:49 UTC, pabo99 commented on frontend/www/js/omegaup/common/index.ts
> +import * as ui from '../ui';
The changes in this file should be moved to a new entrypoint.
```suggestion
import * as ui from '../ui';
```

If you have doubts on how to create it, don't hesitate to ask in slack. It could be added in a new PR

2022-11-25 16:50 UTC, anmode commented on frontend/tests/controllers/UserRegistrationTest.php
> +        //verify token belongs to child accounts ---?
oh yess! I forgot to add. got that!

2022-11-25 16:51 UTC, anmode commented on frontend/tests/controllers/UserRegistrationTest.php
> +        );
Oh yes! Okay done.

2022-11-25 16:55 UTC, anmode commented on frontend/server/src/DAO/Users.php
> +        return \OmegaUp\MySQLConnection::getInstance()->GetOne(
okay!! I have returned whole object for User.

2022-11-29 15:34 UTC, lhchavez reviewed
can the `stuff/hook_tools` be removed? we never want to see it again!

2022-11-29 15:34 UTC, lhchavez commented on frontend/server/src/DAO/Users.php
> +                    LIMIT 1;";
```suggestion
                    LIMIT 1
                    FOR UPDATE;";
```

not _entirely_ sure where the the [`FOR UPDATE`](https://dev.mysql.com/doc/refman/5.6/en/innodb-locking-reads.html) should go, though.

2022-11-29 15:34 UTC, lhchavez commented on frontend/tests/controllers/UserRegistrationTest.php
> +        //assert the message.
```suggestion
```

this comment is re-stating what can be read from the code in the next line, so it's better to leave it out: it's not conveying any new information.

for an example of a great comment, look at L223: the fact that the user is 10yo is not immediately visible from just reading that line, one needs to go look at the surrounding code and make some mental math.

2022-11-29 16:25 UTC, anmode commented on frontend/server/src/Controllers/User.php
> +        \OmegaUp\DAO\Users::update($user);
Sure!

2022-11-30 13:45 UTC, lhchavez reviewed
last thing!

2022-11-30 13:45 UTC, lhchavez commented on frontend/server/src/Controllers/User.php
> +            'entrypoint' => 'user_verification_parental_token',
this block needs to be indented one level, so that it's consistent with the indenting in the rest of the codebase.

2023-01-27 15:12 UTC, anmode commented on frontend/server/src/Controllers/User.php
> +            'entrypoint' => 'user_verification_parental_token',
So Sorry! I for the late response. As I took off exams and holidays :). Now come back to work. Horizontal indentation is ok ig. as this block is inside `try block` so according to it looks ok. please could you clarify? so I'll make the necessary indent then

2023-02-16 14:01 UTC, pabo99 commented on frontend/server/src/Controllers/User.php
> +            ];
```suggestion
            return [
                'templateProperties' => [
                    'payload' => [
                        'hasParentalVerificationToken' => $hasParentalVerificationToken,
                    ],
                    'title' => new \OmegaUp\TranslationString(
                        'omegaupTitleParentalVerificationToken'
                    ),
                ],
                'entrypoint' => 'user_verification_parental_token',
            ];
```

2023-02-16 14:03 UTC, pabo99 commented on frontend/server/src/Controllers/User.php
> +            'entrypoint' => 'user_verification_parental_token',
The problem is inside the `return` statement. See the comment to fix this indentation please

2023-02-18 12:00 UTC, anmode commented on frontend/server/src/Controllers/User.php
> +            'entrypoint' => 'user_verification_parental_token',
Ohh okay! Got that. Thanke.

2023-02-18 12:03 UTC, anmode commented
Done! Please have a last review if needed @lhchavez @pabo99. Thanks!

2023-03-06 05:02 UTC, heduenas approved these changes
@lhchavez can we merge this PR?

2023-03-11 21:19 UTC, merged