Fix: selenium flake
omegaup/omegaup pull request #6956
Opened 2023-03-24 16:31 UTC by ShivamJhaa

# Descripción

Por favor incluye la descripción de lo que cambiaste. Lo que pongas en esta
sección se va a utilizar como commit message cuando se haga merge.

Si tu cambio toca la interfaz, hay que incluir una captura de pantalla.

Fixes: #6931 

# Comentarios

Si hay comentarios para los reviewers (por ejemplo, dónde hay que empezar a
revisar, algo a lo que hay que poner atención adicional, etc.), todo eso se
puede poner en esta sección.

También si faltan cosas por hacer, se puede hacer un checklist en esta sección.

Si no se utiliza, esta sección se puede eliminar.

# Checklist:

- [x] El código sigue la [guía de
      estilo](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) de
      omegaUp.
- [x] Se corrieron todas las pruebas y pasaron.
- [x] Si se está agregando funcionalidad nueva, se agregaron pruebas.
- [x] Si el cambio es grande (> 200 líneas), hay que intentar partirlo en
      varios pull requests. De preferencia uno para los controladores + phpunit
      y luego otro para la interfaz.

2023-03-24 17:49 UTC, pabo99 commented
I'm not sure that this change is enough to fix the flaky test, because I'm getting the same error when I run
```bash
/usr/bin/python3 -m pytest ./frontend/tests/ui/test_course.py --browser=chrome -s --disable-headless
```

```bash
====================================================================================== test session starts ======================================================================================
platform linux -- Python 3.10.6, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/juan/Desarrollo/omegaup
plugins: forked-1.4.0, timeout-2.1.0, mock-3.10.0, stub-1.1.0, shutil-1.7.0, xdist-2.5.0, flaky-3.7.0
collected 2 items                                                                                                                                                                               

frontend/tests/ui/test_course.py .F

=========================================================================================== FAILURES ============================================================================================
___________________________________________________________________________ test_create_identities_for_course[chrome] ___________________________________________________________________________

driver = <ui.conftest.Driver object at 0x7faee8a183a0>

    def test_create_identities_for_course(driver):
        '''Adding some identities into a course and associating one of them to
        specific user
        '''
    
        run_id = driver.generate_id()
        course_alias = 'ut_rank_course_%s' % run_id
        school_name = 'ut_rank_school_%s' % run_id
        assignment_alias = 'ut_rank_hw_%s' % run_id
        problem = 'Sumas'
        username = 'ut_user_%s' % driver.generate_id()
        password = 'p@ssw0rd'
        driver.register_user(username, password)
    
        # Admin creates a course with one assignment and one problem, and then
        # creates some identities associated with the course group
        associated: Optional[util.Identity] = None
        unassociated: Optional[util.Identity] = None
        with driver.login_admin():
            create_course(driver, course_alias, school_name)
            add_assignment_with_problem(driver, assignment_alias, problem)
            # The function require the group alias. We are assuming that it is the
            # same as the course alias, since that is the default
            unassociated, associated = util.add_identities_group(driver,
                                                                 course_alias)[:2]
    
        # Unassociated identity joins the course which it was created for and
        # creates a new run
>       with driver.login(unassociated.username,
                          unassociated.password,
                          is_main_user_identity=False):
E                         AttributeError: 'NoneType' object has no attribute 'username'

frontend/tests/ui/test_course.py:200: AttributeError
==================================================================================== short test summary info ====================================================================================
FAILED frontend/tests/ui/test_course.py::test_create_identities_for_course[chrome] - AttributeError: 'NoneType' object has no attribute 'username'
============================================================================ 1 failed, 1 passed in 101.22s (0:01:41) ============================================================================
```

2023-03-24 18:41 UTC, ShivamJhaa commented
> I'm not sure that this change is enough to fix the flaky test, because I'm getting the same error when I run
> 
> ```shell
> /usr/bin/python3 -m pytest ./frontend/tests/ui/test_course.py --browser=chrome -s --disable-headless
> ```
> 
> ```shell
> ====================================================================================== test session starts ======================================================================================
> platform linux -- Python 3.10.6, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
> rootdir: /home/juan/Desarrollo/omegaup
> plugins: forked-1.4.0, timeout-2.1.0, mock-3.10.0, stub-1.1.0, shutil-1.7.0, xdist-2.5.0, flaky-3.7.0
> collected 2 items                                                                                                                                                                               
> 
> frontend/tests/ui/test_course.py .F
> 
> =========================================================================================== FAILURES ============================================================================================
> ___________________________________________________________________________ test_create_identities_for_course[chrome] ___________________________________________________________________________
> 
> driver = <ui.conftest.Driver object at 0x7faee8a183a0>
> 
>     def test_create_identities_for_course(driver):
>         '''Adding some identities into a course and associating one of them to
>         specific user
>         '''
>     
>         run_id = driver.generate_id()
>         course_alias = 'ut_rank_course_%s' % run_id
>         school_name = 'ut_rank_school_%s' % run_id
>         assignment_alias = 'ut_rank_hw_%s' % run_id
>         problem = 'Sumas'
>         username = 'ut_user_%s' % driver.generate_id()
>         password = 'p@ssw0rd'
>         driver.register_user(username, password)
>     
>         # Admin creates a course with one assignment and one problem, and then
>         # creates some identities associated with the course group
>         associated: Optional[util.Identity] = None
>         unassociated: Optional[util.Identity] = None
>         with driver.login_admin():
>             create_course(driver, course_alias, school_name)
>             add_assignment_with_problem(driver, assignment_alias, problem)
>             # The function require the group alias. We are assuming that it is the
>             # same as the course alias, since that is the default
>             unassociated, associated = util.add_identities_group(driver,
>                                                                  course_alias)[:2]
>     
>         # Unassociated identity joins the course which it was created for and
>         # creates a new run
> >       with driver.login(unassociated.username,
>                           unassociated.password,
>                           is_main_user_identity=False):
> E                         AttributeError: 'NoneType' object has no attribute 'username'
> 
> frontend/tests/ui/test_course.py:200: AttributeError
> ==================================================================================== short test summary info ====================================================================================
> FAILED frontend/tests/ui/test_course.py::test_create_identities_for_course[chrome] - AttributeError: 'NoneType' object has no attribute 'username'
> ============================================================================ 1 failed, 1 passed in 101.22s (0:01:41) ============================================================================
> ```

Strange, tests passes on my device:
![Screenshot from 2023-03-25 00-10-26](https://user-images.githubusercontent.com/86483059/227612150-e1bdaf95-a0eb-4e96-86e8-356fa2c236b4.png)

2023-03-24 18:51 UTC, pabo99 commented
Yes you are right,  this is strange because when we run the tests in firefox they pass , but when we run in chrome a test fails. Could you try run the test with the flag `--browser-chrome` instead of `--browser-firefox` please?

2023-03-24 19:07 UTC, ShivamJhaa commented
> Yes you are right, this is strange because when we run the tests in firefox they pass , but when we run in chrome a test fails. Could you try run the test with the flag `--browser-chrome` instead of `--browser-firefox` please?

When I run the tests in chrome, all of the test fails in this test suite with the following error: 
![Screenshot from 2023-03-25 00-36-38](https://user-images.githubusercontent.com/86483059/227617455-d2f00993-067e-4b4c-ad5d-8c7d0a721d7c.png)

Do you have any idea why this is happening?

2023-03-24 19:09 UTC, heduenas commented on stuff/pipelines/test_client_contest.py
> -@pytest.mark.skip(reason="Disabled temporarily because it's flaky")
To re-enable the test we have to do the opposite of what we did in https://github.com/omegaup/omegaup/commit/0f994f6c39446a78b5f149a8f01e6e4f265251a8
That means that we do have to remove this line.

2023-03-24 19:15 UTC, heduenas commented
> > Yes you are right, this is strange because when we run the tests in firefox they pass , but when we run in chrome a test fails. Could you try run the test with the flag `--browser-chrome` instead of `--browser-firefox` please?
> 
> When I run the tests in chrome, all of the test fails in this test suite with the following error: ![Screenshot from 2023-03-25 00-36-38](https://user-images.githubusercontent.com/86483059/227617455-d2f00993-067e-4b4c-ad5d-8c7d0a721d7c.png)
> 
> Do you have any idea why this is happening?

It seems that on github actions they run on chrome. So if they pass there we should be fine.

2023-03-24 19:21 UTC, pabo99 commented on stuff/pipelines/test_client_contest.py
> -@pytest.mark.skip(reason="Disabled temporarily because it's flaky")
> > Yes you are right, this is strange because when we run the tests in firefox they pass , but when we run in chrome a test fails. Could you try run the test with the flag `--browser-chrome` instead of `--browser-firefox` please?
> 
> When I run the tests in chrome, all of the test fails in this test suite with the following error: ![Screenshot from 2023-03-25 00-36-38](https://user-images.githubusercontent.com/86483059/227617455-d2f00993-067e-4b4c-ad5d-8c7d0a721d7c.png)
> 
> Do you have any idea why this is happening?

Oh, yes. There are some errors in the login page that are affecting the selenium tests. But, we fixed them yesterday. Perhaps you need to update your branch with the main branch.

```
git fetch upstream main:main 
git merge upstream/main
```

2023-03-24 19:40 UTC, heduenas commented on stuff/pipelines/test_client_contest.py
> -@pytest.mark.skip(reason="Disabled temporarily because it's flaky")
Actually, the errors in the screenshot have nothing to do with the Google log in. I ran into this error the other day, we need to add `checked: boolean = false;` in [frontend/www/js/omegaup/components/login/Signup.vue](https://github.com/omegaup/omegaup/blob/3a75b4728c37470d8a23e1a23528f66c1a6695c4/frontend/www/js/omegaup/components/login/Signup.vue#L126). That gets rid of this specific error.

2023-03-24 20:08 UTC, heduenas approved these changes
I'm going to trigger the python tests again to make sure they are no longer flaky. If it passes then it looks good to go. Thank you @ShivamJhaa for fixing this!

2023-03-24 20:13 UTC, heduenas commented
> I'm going to trigger the python tests again to make sure they are no longer flaky. If it passes then it looks good to go. Thank you @ShivamJhaa for fixing this!

Actually, @ShivamJhaa are you trying to fix the flaky python test or the flaky selenium tests. Becuse you are making changes to a selenium test but re-enabling a python test.

2023-03-24 20:25 UTC, heduenas requested changes
Disapproving until we fully understand the intent of the changes.

2023-03-25 04:58 UTC, ShivamJhaa commented
> Disapproving until we fully understand the intent of the changes.

This PR tries to fix the selenium flake mentioned in this issue https://github.com/omegaup/omegaup/issues/6931. I was actually confused by this comment https://github.com/omegaup/omegaup/issues/6931#issuecomment-1473188850, I thought this selenium test was disabled by these changes but now I have removed that from this PR.
Thanks!

2023-03-25 18:48 UTC, ShivamJhaa commented
@pabo99, @heduenas There was multiple issues in this tests, the first one was with `driver.typeahead_helper`(please look [here](https://github.com/omegaup/omegaup/issues/6931#issuecomment-1475383680) for more details), so after fixing this issue the test was passing in Mozilla but in Chrome the issue was https://github.com/omegaup/omegaup/blob/main/frontend/tests/ui/util.py#L536 here, actually we are already present on the `Members` tab but as we are at the down of the page, selenium was not able to click on the button and throwing error. I removed the click call as this was unnecessary (we are already on Members tab) and this makes the code works correctly. I tried running it couple of times and it passed.

![Screenshot from 2023-03-26 00-01-07](https://user-images.githubusercontent.com/86483059/227735771-3350255b-a52a-400d-8184-81e2199b9c3a.png)

2023-03-25 18:51 UTC, ShivamJhaa commented on stuff/pipelines/test_client_contest.py
> -@pytest.mark.skip(reason="Disabled temporarily because it's flaky")
> This decorator skips failing tests in Python, not in Selenium. Can you please undo the changes made to this file?

Done, actually, I was a little bit confused. Sorry for the inconvenience .

2023-03-26 19:44 UTC, heduenas commented
> > Disapproving until we fully understand the intent of the changes.
> 
> This PR tries to fix the selenium flake mentioned in this issue #6931. I was actually confused by this comment [#6931 (comment)](https://github.com/omegaup/omegaup/issues/6931#issuecomment-1473188850), I thought this selenium test was disabled by these changes but now I have removed that from this PR. Thanks!

Sorry about the confusion. I mixed up the python and selenium tests.

2023-03-29 08:10 UTC, heduenas commented on frontend/tests/ui/test_course.py
> -    school_name = 'ut_rank_school_%s' % run_id
This test failed in the previous selenium run https://github.com/omegaup/omegaup/actions/runs/4526337776/jobs/7971436603. Does that mean this change doesn't fix it?

2023-03-29 21:35 UTC, pabo99 commented on frontend/tests/ui/test_course.py
> -    school_name = 'ut_rank_school_%s' % run_id
All the tests are passing now. The error displayed in previous selenium runs is fixed with this change.

Thanks, @ShivamJhaa

2023-03-29 21:36 UTC, pabo99 approved these changes

2023-03-30 08:54 UTC, ShivamJhaa commented on frontend/tests/ui/test_course.py
> -    school_name = 'ut_rank_school_%s' % run_id
> This test failed in the previous selenium run https://github.com/omegaup/omegaup/actions/runs/4526337776/jobs/7971436603. Does that mean this change doesn't fix it?

That's weird, I am not able to reproduce this locally now.
![Screenshot from 2023-03-30 14-23-04](https://user-images.githubusercontent.com/86483059/228783509-fc26762c-4aaa-4f27-a3fc-77d00b5d2523.png)

2023-03-31 07:15 UTC, pabo99 commented on frontend/tests/ui/test_course.py
> -    school_name = 'ut_rank_school_%s' % run_id
You can't reproduce the error because you're fixing it right here in this PR. Maybe you could try running the test on your main branch to verify that the error does indeed occur.

2023-04-01 06:10 UTC, ShivamJhaa commented on frontend/tests/ui/test_course.py
> -    school_name = 'ut_rank_school_%s' % run_id
Yes, that's true but the faliure pointed out by @heduenas was on this branch only https://github.com/omegaup/omegaup/pull/6956/commits/a0a80d009aecadc586e085309eb75258bb6f234b  after I added the fix. Which means the test is passing locally but it fails sometimes on Cl.

2023-04-01 19:56 UTC, heduenas approved these changes

2023-04-01 19:57 UTC, merged