Agregando Login al navbar de la plataforma
omegaup/omegaup pull request #7018
Opened 2023-05-29 14:58 UTC by IngridRB

# Descripción

Ahora el login se muestra en la barra del nacbar.

![image](https://github.com/omegaup/omegaup/assets/110271913/a63f6a96-2951-48d2-8728-41f137a40d4f)

Fixes: #7014

# Checklist:

- [x] El código sigue la [guía de
      estilo](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) de
      omegaUp.
- [x] Se corrieron todas las pruebas y pasaron.
- [x] Si se está agregando funcionalidad nueva, se agregaron pruebas.
- [x] Si el cambio es grande (> 200 líneas), hay que intentar partirlo en
      varios pull requests. De preferencia uno para los controladores + phpunit
      y luego otro para la interfaz.

2023-05-29 21:56 UTC, carlosabcs requested changes
El cambio se ve bien, salvo por una pequeña corrección. Sin embargo, me parece que podrías agregarle una prueba unitaria en el archivo `Navbar.test.ts`, simplemente puedes evaluar que el texto se pueda ver cuando `isLoggedIn = true` y no se puede ver en caso contrario.

2023-05-29 21:56 UTC, carlosabcs commented on frontend/www/js/omegaup/components/common/Navbar.vue
> +          <ul v-if="!isLoggedIn" class="navbar-nav navbar-right d-lg-flex">
Ya que el elemento hermano que está antes de este elemento tiene un `v-if="isLoggedIn"`, sería más correcto que uses `v-else` aquí.

2023-06-04 01:28 UTC, carlosabcs requested changes
Solo cambios muy menores y listo!

2023-06-04 01:28 UTC, carlosabcs commented on frontend/www/js/omegaup/components/common/Navbar.test.ts
> +      propsData: { ...propsData },
```suggestion
      propsData,
```

Así quedaría más simple.

2023-06-04 01:28 UTC, carlosabcs commented on frontend/www/js/omegaup/components/common/Navbar.test.ts
> +    const wrapper = mount(common_Navbar, {
```suggestion
    const wrapper = shallowMount(common_Navbar, {
```

`shallowMount` es más ligero que `mount`, ya que no renderiza los componentes hijos del componente actual. Prueba si corriendo `shallowMount` aquí basta, sino lo dejas con el `mount`.

2023-06-04 01:28 UTC, carlosabcs commented on frontend/www/js/omegaup/components/common/Navbar.vue
> +          <ul v-if="isLoggedIn" class="navbar-nav navbar-right align-items-end">
Solo por curiosidad, para qué usaste `align-items-end`? Esa propiedad sirve para alinear los componentes alrededor del cross-axis de flexbox (que en este caso es el eje Y).

2023-06-06 02:02 UTC, carlosabcs approved these changes

2023-06-06 02:20 UTC, carlosabcs commented
@heduenas LGTM.

2023-06-07 16:59 UTC, heduenas commented
@IngridRB, puedes agregar un screenshot de la vista desktop? Nadamas para asegurarnos de que no sea afectada por este cambio. Fuera de eso el cambio se ve bien!

2023-06-09 16:59 UTC, IngridRB commented
> @IngridRB, puedes agregar un screenshot de la vista desktop? Nadamas para asegurarnos de que no sea afectada por este cambio. Fuera de eso el cambio se ve bien!

Si claro, en el descripción del PR lo acabo de agregar.

2023-06-09 18:02 UTC, heduenas approved these changes

2023-06-12 01:10 UTC, merged