Milestone 1.1: Write test for contest.spec.ts
omegaup/omegaup pull request #7036
Opened 2023-06-03 13:14 UTC by ShivamJhaa

# Descripción

Por favor incluye la descripción de lo que cambiaste. Lo que pongas en esta
sección se va a utilizar como commit message cuando se haga merge.

Si tu cambio toca la interfaz, hay que incluir una captura de pantalla.

Fixes: #(issue)

# Comentarios

Si hay comentarios para los reviewers (por ejemplo, dónde hay que empezar a
revisar, algo a lo que hay que poner atención adicional, etc.), todo eso se
puede poner en esta sección.

También si faltan cosas por hacer, se puede hacer un checklist en esta sección.

Si no se utiliza, esta sección se puede eliminar.

# Checklist:

- [x] El código sigue la [guía de
      estilo](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) de
      omegaUp.
- [x] Se corrieron todas las pruebas y pasaron.
- [x] Si se está agregando funcionalidad nueva, se agregaron pruebas.
- [x] Si el cambio es grande (> 200 líneas), hay que intentar partirlo en
      varios pull requests. De preferencia uno para los controladores + phpunit
      y luego otro para la interfaz.

2023-06-03 13:23 UTC, ShivamJhaa commented
@heduenas @carlosabcs This PR contains more than 200 lines because I also have to write several helper functions that are needed in a single test only.

2023-06-04 18:54 UTC, Mau-MD commented
Your PR description could be a little bit more descriptive. Removing the template boilerplate, the only thing you wrote is 

> Fixes: Added cypress test for contest.spec.ts

However, down below you are saying that you had to write several helper functions. That should be inside the description too to make it a little bit easier for reviewers

2023-06-04 19:22 UTC, Mau-MD requested changes
overall really hard to review. commits are way too large and unorganized. please consider to divide commits into smaller chunks

https://www.freecodecamp.org/news/git-best-practices-commits-and-code-reviews/

2023-06-04 19:22 UTC, Mau-MD commented on cypress/integration/contest.spec.ts
> +        const userLoginOptions: LoginOptions = {
You are creating the userLoginOptions here, but you are not using them until down below. Either group all `...Options` together at the beginning of the function or declare the object just before using it

2023-06-04 19:22 UTC, Mau-MD commented on cypress/integration/contest.spec.ts
> +        const userLoginOptions: LoginOptions = {
We want this to improve readability. You don't know who is gonna take a look at the code in the next few months or years

2023-06-04 19:22 UTC, Mau-MD commented on cypress/integration/contest.spec.ts
> +        }
I don't like the enum being declared here. Seems like you are imposing a new type system. If you are going to do that, then refactor `ContestOptions` to also receive an enum by default (and all other references that uses it)

If you think a refactor is needed, then do it; otherwise, just leave it as is

2023-06-04 19:22 UTC, Mau-MD commented on frontend/tests/ui/test_contest.py
> +        sleep(200)
forgot to remove?

2023-06-04 19:22 UTC, Mau-MD commented on frontend/tests/ui/util.py
> +    print(group_alias)
forgot to remove?

2023-06-04 19:22 UTC, Mau-MD commented on frontend/tests/ui/util.py
> +    sleep(10)
same here

2023-06-04 19:22 UTC, Mau-MD commented on cypress/support/utils/common.ts
> +   // Click on the button to create a new group
Ideally, you shouldn't write any comments to explain what you are doing. You code should be self-documented.  https://medium.com/@bpnorlander/stop-writing-code-comments-28fef5272752

For example, I would rewrite it like this:
```ts
const newGroupButtonSelector = '[href="/group/new/"]'
cy.get(newGroupButtonSelector).click()
```

2023-06-04 19:22 UTC, Mau-MD commented on cypress/support/utils/common.ts
> + * Creates a group as an admin and returns a generated group alias.
nothing is getting returned

2023-06-04 19:22 UTC, Mau-MD commented on cypress/support/utils/common.ts
> +      uploadedPasswords.concat(Cypress.$.makeArray($els).map((el) => el.innerText));
huh

2023-06-04 19:22 UTC, Mau-MD commented on cypress/integration/basic_commands.spec.ts
>          fixturePath: 'main.cpp',
Again, I'm pretty sure you are doing more than adding a clarification function

2023-06-04 19:22 UTC, Mau-MD commented on cypress/integration/contest.spec.ts
> +        // updateScoreboardForContest(contestOptions.contestAlias);
forgot to remove?

2023-06-04 19:22 UTC, Mau-MD commented on cypress/integration/contest.spec.ts
> +        cy.pause();
why pausing

2023-06-04 19:22 UTC, Mau-MD commented on cypress/support/commands.ts
> +    }status
forgot to remove?

2023-06-04 19:22 UTC, Mau-MD commented on cypress/support/utils/common.ts
> +      Cypress.$.makeArray($els).forEach(element => {
`const contestansArray = Cypess.$.makeArray($els)`

you should also rename `$els` to something like `rawHTMLElements` or something clearer

2023-06-04 19:22 UTC, Mau-MD commented on cypress/integration/contest.spec.ts
> +      const userLoginOptions = registerMultileUsers(2);
registerMultipleUsers*

2023-06-04 19:22 UTC, Mau-MD commented on cypress/integration/contest.spec.ts
> +      };
i think it's the third time i'm seeing you creating this. at this point is better to have a util function that creates groupOptions

2023-06-04 19:22 UTC, Mau-MD commented on cypress/support/commands.ts
> +Cypress.Commands.add('loginAdmin', () => {
You started using this function two commits ago, but you just declared it here. This makes it really hard to review. Ideally you should commit sequentially. First you create the util function, then you use it

2023-06-04 19:22 UTC, Mau-MD commented on cypress/support/utils/common.ts
> + */
the function name is clear enough. or maybe
`createContestAsAdmin()`

2023-06-04 19:22 UTC, Mau-MD commented on cypress/support/utils/common.ts
> +export const registerMultileUsers = (noOfUsers: number): LoginOptions[] => {
same with `loginAdmin()`, you used this function one commit ago

2023-06-04 19:22 UTC, Mau-MD commented on cypress/support/utils/common.ts
> +   for(let i=0;i<noOfUsers;i++) {
i think you are missing formatting here

2023-06-04 19:22 UTC, Mau-MD commented on cypress/support/utils/common.ts
> +
same here, you are using this object multiple times already, create a util function, so you don't have to redefine it each time

2023-06-04 19:22 UTC, Mau-MD commented on cypress/support/utils/common.ts
> + */
useless comment

2023-06-04 19:22 UTC, Mau-MD commented on cypress/support/utils/common.ts
> +   }
you are redefining the enum again. Again, if you want to change it, then change it inside `ContestOptions` and do not define `ScoreMode` every time you want to set `ContestOptions`. If you don't want to refactor `ContestOptions` to accept an enum, then make this enum global and exportable inside a `types` file

2023-06-04 19:23 UTC, Mau-MD commented
re-request my review once the feedback has been addressed

2023-06-04 20:11 UTC, ShivamJhaa commented
@Mau-MD sorry for messing up the commits, I will try to not repeat this again. But most if the comments you have made are on the changes that i have reverted. Can you please review my last commit. 
Sorry for inconvenience.

2023-06-04 20:12 UTC, ShivamJhaa commented
Or if possible you can review from the files changed tab.

2023-06-05 13:35 UTC, ShivamJhaa commented on cypress/support/utils/common.ts
> +   }
Done.

2023-06-05 13:42 UTC, ShivamJhaa commented on cypress/integration/contest.spec.ts
> +        const userLoginOptions: LoginOptions = {
Done.

2023-06-05 13:43 UTC, ShivamJhaa commented on cypress/integration/contest.spec.ts
> +        }
Removed.

2023-06-05 13:43 UTC, ShivamJhaa commented on frontend/tests/ui/test_contest.py
> +        sleep(200)
Removed.

2023-06-05 13:43 UTC, ShivamJhaa commented on frontend/tests/ui/util.py
> +    print(group_alias)
Removed.

2023-06-05 13:43 UTC, ShivamJhaa commented on frontend/tests/ui/util.py
> +    sleep(10)
Done.

2023-06-05 13:44 UTC, ShivamJhaa commented on cypress/support/utils/common.ts
> +   // Click on the button to create a new group
Removed comments.

2023-06-05 13:44 UTC, ShivamJhaa commented on cypress/support/utils/common.ts
> + * Creates a group as an admin and returns a generated group alias.
Removed.

2023-06-05 13:45 UTC, ShivamJhaa commented on cypress/integration/contest.spec.ts
> +        // updateScoreboardForContest(contestOptions.contestAlias);
Removed.

2023-06-05 13:45 UTC, ShivamJhaa commented on cypress/integration/contest.spec.ts
> +        cy.pause();
Removed.

2023-06-05 13:45 UTC, ShivamJhaa commented on cypress/support/commands.ts
> +    }status
removed.

2023-06-05 13:47 UTC, ShivamJhaa commented on cypress/support/utils/common.ts
> +      Cypress.$.makeArray($els).forEach(element => {
Done.

2023-06-05 13:50 UTC, ShivamJhaa commented on cypress/integration/contest.spec.ts
> +      const userLoginOptions = registerMultileUsers(2);
Done.

2023-06-05 13:50 UTC, ShivamJhaa commented on cypress/integration/contest.spec.ts
> +      };
Done.

2023-06-05 13:51 UTC, ShivamJhaa commented on cypress/support/commands.ts
> +Cypress.Commands.add('loginAdmin', () => {
Sorry for messing up the commits, will remember this from next time.

2023-06-05 13:52 UTC, ShivamJhaa commented on cypress/support/utils/common.ts
> + */
Done.

2023-06-05 13:52 UTC, ShivamJhaa commented on cypress/support/utils/common.ts
> +   for(let i=0;i<noOfUsers;i++) {
Done.

2023-06-05 13:52 UTC, ShivamJhaa commented on cypress/support/utils/common.ts
> +
Done.

2023-06-05 13:52 UTC, ShivamJhaa commented on cypress/support/utils/common.ts
> + */
removed.

2023-06-05 14:09 UTC, ShivamJhaa commented on cypress/integration/contest.spec.ts
> +        }
Declared it globally inside the contestPage.ts so that we will not need to declare it again and again.

2023-06-05 14:10 UTC, ShivamJhaa commented
@Mau-MD Can you please review it again? Thanks!

2023-06-06 05:13 UTC, Mau-MD approved these changes
Looks better and the commits are a bit cleaner. They can still be improved

https://css-tricks.com/creating-the-perfect-commit-in-git/

2023-06-07 12:09 UTC, ShivamJhaa commented
@heduenas Please take a look,
thanks!

2023-06-09 08:00 UTC, heduenas commented
This PR was expectedly large and a little hectic since it's the first one and introduces several pieces of code that will be re-used in follow up CLs. Thank you @ShivamJhaa for writing these tests and thank you @Mau-MD for providing such valuable feedback.

2023-06-09 08:01 UTC, heduenas approved these changes

2023-06-10 14:58 UTC, merged