Modificando la altura del carrusel de testimonios
omegaup/omegaup pull request #7039
Opened 2023-06-04 00:48 UTC by IngridRB

# Descripción

Se definió la altura para el carrusel cuando esté en vista móvil.

Fixes: #7020

# Checklist:

- [x] El código sigue la [guía de
      estilo](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) de
      omegaUp.
- [x] Se corrieron todas las pruebas y pasaron.
- [x] Si se está agregando funcionalidad nueva, se agregaron pruebas.
- [x] Si el cambio es grande (> 200 líneas), hay que intentar partirlo en
      varios pull requests. De preferencia uno para los controladores + phpunit
      y luego otro para la interfaz.

2023-06-04 01:39 UTC, carlosabcs requested changes
Por favor prueba el cambio que te propuse y si está todo bien mandas commit.

2023-06-04 01:39 UTC, carlosabcs commented on frontend/www/js/omegaup/components/homepage/Testimonials.vue
> +}
```suggestion
min-height: 31rem;
@media only screen and (min-width: 767px) {
  .carousel-inner {
    min-height: auto;
  }
}
```

2023-06-06 04:06 UTC, carlosabcs approved these changes
@heduenas, LGTM.

2023-06-09 07:45 UTC, heduenas approved these changes

2023-06-11 00:20 UTC, merged