Cambiando el tamaño de la letra de sponsor.
omegaup/omegaup pull request #7041
Opened 2023-06-07 21:06 UTC by IngridRB

# Descripción

![image](https://github.com/omegaup/omegaup/assets/110271913/f230af9a-7e69-4595-bb48-ebd5ae447000)

Fixes: #7022

# Checklist:

- [x] El código sigue la [guía de
      estilo](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) de
      omegaUp.
- [x] Se corrieron todas las pruebas y pasaron.
- [x] Si se está agregando funcionalidad nueva, se agregaron pruebas.
- [x] Si el cambio es grande (> 200 líneas), hay que intentar partirlo en
      varios pull requests. De preferencia uno para los controladores + phpunit
      y luego otro para la interfaz.

2023-06-07 22:06 UTC, carlosabcs requested changes
Para respetar el [mobile first](https://desarrolloweb.com/articulos/mobile-first-responsive.html), por favor cambia estas sentencias para usar `min-width` en lugar de `max-width`.

2023-06-07 22:07 UTC, carlosabcs commented
Por favor, no olvides mandar captura de cómo se ve en versión desktop para estar seguros de que todo anda bien.

2023-06-08 04:46 UTC, IngridRB commented
> Por favor, no olvides mandar captura de cómo se ve en versión desktop para estar seguros de que todo anda bien.

Esta bien, ahora lo agrego

2023-06-12 03:21 UTC, heduenas approved these changes

2023-06-12 03:54 UTC, carlosabcs approved these changes

2023-06-14 04:30 UTC, merged