Courses Homepage Changes
omegaup/omegaup pull request #7055
Opened 2023-06-14 18:41 UTC by galovdev

# Descripción

- Los botones tienen el mismo tamano
- Los titulos de las secciones estan centrados, son mas grandes y tienen mas espaciado
- Los bullet points tienen mas tamano y espaciado (esto cambiara con el cambio que hare en el Markdown, pero lo pongo porque en la captura se vera reflejado.
- Las imagenes no son tan grandes
- Elimino el boton doble de Ver Cursos

Fixes: #7026

![Group 1COURSESHOMEPAGE](https://github.com/omegaup/omegaup/assets/107520089/857c0ae1-645e-40f3-b374-c15eb5c5ce00)

2023-06-14 20:09 UTC, pabo99 commented
¿Puedes ejecutar el comando que te sugiere el liniter?
```
./stuff/lint.sh fix -- frontend/www/js/omegaup/components/course/Homepage.vue
```
con eso se debería de arreglar el check de `CI / lint`

2023-06-15 19:21 UTC, pabo99 requested changes
El PR se ve bien. Sólo te dejé algunas sugerencias.

2023-06-15 19:21 UTC, pabo99 commented on frontend/www/js/omegaup/components/Markdown.vue
> +    margin-bottom: 0.6em;
Esto afectaría los estilos de todos los lugares donde se mande llamar el componente de Markdown y se utilicen listas ordenadas (ol) o listas desordenadas (ul) en el texto a mostrar.

¿Qué te parece si el cambio lo agregas en el componente padre `Homepage.vue`?

2023-06-15 21:40 UTC, galovdev commented on frontend/www/js/omegaup/components/Markdown.vue
> +    font-size: 1.06rem;
Es correcto, parece que no cambia nada. Creo que lo puse primero y luego ya vi que lo podia cambiar sin cambiar todas las del markdown

2023-06-16 18:38 UTC, pabo99 reviewed
Ya casi, tengo un par de comentarios. 

Por cierto, hay que ejecutar  el comando:
```
./stuff/lint.sh
```
para que se arreglen todos los espacios y líneas en blanco en automático, si no el error se va a mostrar acá en github y después vas a tener que empujar otro commit con las correcciones

2023-06-16 18:38 UTC, pabo99 commented on frontend/www/js/omegaup/components/course/Homepage.vue
> +[data-homepage-course] [data-markdown-statement] {
Faltaría agregar este `data-attribute` en el div pricipal del template en la línea 2

2023-06-16 18:38 UTC, pabo99 commented on frontend/www/js/omegaup/components/Markdown.vue
> +    margin-left: 0.2;
Este cambio para que se estaria haciendo? es muy similar al original.

2023-06-29 04:13 UTC, tvanessa commented
@galovdev hay algun problema para que resuelvas los comentarios de Juan Pablo?

2023-07-01 18:34 UTC, heduenas commented
@galovdev puedes correr el comando del linter para arreglar ese check?

2023-07-01 19:26 UTC, galovdev commented
> @galovdev puedes correr el comando del linter para arreglar ese check?

No me esta dejando, en cuanto encuentre como lo hago

2023-07-06 19:53 UTC, pabo99 commented on frontend/www/js/omegaup/components/course/Homepage.vue
> +
nit:
```suggestion
```

2023-07-06 19:54 UTC, pabo99 approved these changes

2023-07-06 20:06 UTC, pabo99 commented
Se ve bien el cambio. 

Parece que sólo faltaba quitar una línea al final del archivo `Homepage.vue` pero ya está

2023-07-08 20:46 UTC, merged