homepage style
omegaup/omegaup pull request #7056
Opened 2023-06-14 22:16 UTC by galovdev

# Descripción

- Titulo Slides ahora es mas pequeno, tiene mas espaciado y tiene mas distancia con las descripcion
- La descripcion tiene menos max width, mas espaciado.
- Los botones tienen mas padding
- Hay mas distancia entre la personas que diop el testimonio y el testimonio, el tamano de la letra tambien cambio
- Los titulos de las secciones son menores y con mas espaciado, se ven mas claros
- Las descripciones tienen mas espacio entre si y mas tamano
- Los botones son iguales que los demas y el padding igual, ya no tienen diferentes tamanos de font
- Gracias a nuestro patrocinador es del mismo tamano que el de un titulo de una seccion y el logo no es enorme

Fixes: #7024

![Group 1landingpage](https://github.com/omegaup/omegaup/assets/107520089/278c2da3-887b-4298-a04a-f23ec2e97beb)

2023-06-16 17:35 UTC, heduenas commented
puedes meter a mano un registro a la tabla `School_of_the_month` para ver como se ve con eso?
Tambien incluye screenshots de como se ve en mobile antes y despues?

2023-06-16 21:36 UTC, galovdev commented
> puedes meter a mano un registro a la tabla `School_of_the_month` para ver como se ve con eso? Tambien incluye screenshots de como se ve en mobile antes y despues?

Añadí ambos a la info del Pull

2023-06-17 17:41 UTC, heduenas commented on frontend/www/js/omegaup/components/homepage/Slide.vue
> +    height: 500px;
por que cambiar de rem a px?

2023-06-18 02:34 UTC, galovdev commented on frontend/www/js/omegaup/components/homepage/Slide.vue
> +    height: 500px;
Mmm no me acuerdo, dejame lo cambio

2023-06-18 13:30 UTC, carlosabcs requested changes
Le he dado una primera revisada, trata de cumplir los criterios que comenté y aplicarlos en todos los cambios de este PR. Luego le doy una segunda revisión.

Gracias por mejorar el Landing!!

2023-06-18 13:30 UTC, carlosabcs commented on frontend/www/js/omegaup/components/homepage/SchoolOfTheMonth.vue
> +        class="card-header-help max-w-8 !mportant"
Idealmente, evitamos usar el `important!`, además creo que lo escribiste mal. Me parece que es mejor quitarlo.

2023-06-18 13:30 UTC, carlosabcs commented on frontend/www/js/omegaup/components/homepage/Section.vue
> +  font-weight: 500;
Para esto, no te sirve: https://getbootstrap.com/docs/5.0/utilities/text/#font-weight-and-italics ?

2023-06-18 13:30 UTC, carlosabcs commented on frontend/www/js/omegaup/components/homepage/Section.vue
> +  font-weight: 500;
Lo mismo para las clases de abajo.

2023-06-18 13:30 UTC, carlosabcs commented on frontend/www/js/omegaup/components/homepage/Slide.vue
> +      <div style="max-width: 640px">
No recomendamos usar el atributo `style` para poner los estilos, en todo caso, si es necesario, ponle una clase y aplicale los estilos abajo en la sección de estilos.

2023-06-18 13:30 UTC, carlosabcs commented on frontend/www/js/omegaup/components/homepage/Slide.vue
> +          style="max-width: 480px"
Aquí tampoco deberías estar usando `style=`

2023-06-20 22:25 UTC, tvanessa reviewed
En la primer imagen (donde se ve todo el homepage en desktop) desaparecen las cajas de escuela del mes/coder del mes. Y no se nota el espacio de los testimonios. 
Puedes actualizar la imagen para entender mejor los cambios?

2023-06-21 03:49 UTC, galovdev commented
> En la primer imagen (donde se ve todo el homepage en desktop) desaparecen las cajas de escuela del mes/coder del mes. Y no se nota el espacio de los testimonios. Puedes actualizar la imagen para entender mejor los cambios?

An

> En la primer imagen (donde se ve todo el homepage en desktop) desaparecen las cajas de escuela del mes/coder del mes. Y no se nota el espacio de los testimonios. Puedes actualizar la imagen para entender mejor los cambios?

Añadi otra captura hasta abajo donde se ven las escuelas y la quote

2023-06-21 03:59 UTC, galovdev commented on frontend/www/js/omegaup/components/homepage/Section.vue
> +  font-weight: 500;
Para estas si sirve, pero las demas son muy especificas no las encuentro en el rango de bootstrap

2023-06-23 17:37 UTC, heduenas commented
@carlosabcs y @tvanessa me parece que Galo ya resolvio todos sus comentarios, por favor vuelvan a revisar.

2023-06-23 21:08 UTC, carlosabcs reviewed
Nada más un cambio menor y listo.

2023-06-23 21:08 UTC, carlosabcs commented on frontend/www/js/omegaup/components/homepage/SchoolOfTheMonth.vue
> +        class="card-header-help max-w-8"
Ese `max-w-8` sirve para algo ahora? No lo encuentro como una clase de Bootstrap y tampoco veo que hayas agregado una regla de estilos en `.scss`.

2023-06-24 07:37 UTC, tvanessa approved these changes

2023-06-25 18:40 UTC, heduenas commented on frontend/www/js/omegaup/components/homepage/SchoolOfTheMonth.vue
> +        class="card-header-help max-w-8"
@galovdev puedes resolver este comentario? Para ya darle merge a este PR :)

2023-06-25 19:42 UTC, galovdev commented on frontend/www/js/omegaup/components/homepage/SchoolOfTheMonth.vue
> +        class="card-header-help max-w-8"
> @galovdev puedes resolver este comentario? Para ya darle merge a este PR :)

Buenas lo he intentado, pero ocurrió un detallito con Git que veré mañana con JP

2023-06-26 17:25 UTC, galovdev commented on frontend/www/js/omegaup/components/homepage/SchoolOfTheMonth.vue
> +        class="card-header-help max-w-8"
> 
Ya quedo el cambio :)

2023-06-27 17:02 UTC, merged