Ajustando el login para pantallas móviles
omegaup/omegaup pull request #7073
Opened 2023-06-27 16:19 UTC by IngridRB

# Descripción

Para pantallas más pequeñas de 385px, se redujo el tamaño de la letra de "Iniciar sesión / Registrarse" de 16px a 14px. Se eliminaron los paddings para aprovechar mejor el espacio, y ahora se puede ver correctamente incluso en pantallas de 345px.

Vista en iPhone SE:
![image](https://github.com/omegaup/omegaup/assets/110271913/702875e2-3656-42c3-869c-e8ee102ec802)

Vista Samsung Galaxy A51/71
![image](https://github.com/omegaup/omegaup/assets/110271913/240c70bd-5fd6-4b92-a1ca-e8262db06fc6)

Vista en pantallas de 345px:
![image](https://github.com/omegaup/omegaup/assets/110271913/83251c61-41e6-4b78-9b8a-29f02253216a)

# Checklist:

- [X] El código sigue la [guía de
      estilo](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) de
      omegaUp.
- [X] Se corrieron todas las pruebas y pasaron.
- [X] Si se está agregando funcionalidad nueva, se agregaron pruebas.
- [X] Si el cambio es grande (> 200 líneas), hay que intentar partirlo en
      varios pull requests. De preferencia uno para los controladores + phpunit
      y luego otro para la interfaz.

2023-06-28 14:34 UTC, carlosabcs requested changes
Cambios menores y listo!

2023-06-28 16:10 UTC, IngridRB commented on frontend/www/js/omegaup/components/common/Navbar.vue
> +                class="nav-link text-navLogIn"
Ya hice el cambio, gracias.

2023-07-02 18:34 UTC, heduenas approved these changes

2023-07-02 18:34 UTC, heduenas commented on frontend/www/js/omegaup/components/common/Navbar.vue
> +                class="nav-link text-navLogIn"
@carlosabcs ya nadamas falta que apruebes para que se haga merge.

2023-07-03 02:47 UTC, carlosabcs approved these changes

2023-07-03 02:59 UTC, merged