Clarifications
omegaup/omegaup pull request #7083
Opened 2023-06-30 05:13 UTC by IngridRB

# Descripción

**MODO PROFESOR** 

. Versión desktop
![image](https://github.com/omegaup/omegaup/assets/110271913/13612c11-327a-453b-a955-7b8f334b82a3)
![image](https://github.com/omegaup/omegaup/assets/110271913/d09ea3c3-92d3-489f-abff-4c58b80305f0)

. Versión móvil
![image](https://github.com/omegaup/omegaup/assets/110271913/f19f5beb-4a68-468b-b19b-20b6c1648b53)
![image](https://github.com/omegaup/omegaup/assets/110271913/a79f225d-afe8-4c95-be14-da185b4606c6)

. Versión desktop
![image](https://github.com/omegaup/omegaup/assets/110271913/1bc89b50-851f-439c-a058-4ac0347e6a2c)
![image](https://github.com/omegaup/omegaup/assets/110271913/72c6beac-45a0-4b33-8f8b-8df2a9ee50cc)

. Versión móvil
![image](https://github.com/omegaup/omegaup/assets/110271913/f8595e3b-fb74-4da6-8f41-2ceb5e33749c)

**MODO ALUMNO**
. Versión desktop
![image](https://github.com/omegaup/omegaup/assets/110271913/f8ba1f29-9853-4513-bc89-f5334960325e)
![image](https://github.com/omegaup/omegaup/assets/110271913/a7ecd869-527e-4699-8953-8b906bf602ac)

. Versión móvil
![image](https://github.com/omegaup/omegaup/assets/110271913/6c51744f-5545-47e6-9533-74a2aa833d85)

Fixes: #7074 

# Checklist:

- [x] El código sigue la [guía de
      estilo](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) de
      omegaUp.
- [x] Se corrieron todas las pruebas y pasaron.
- [x] Si se está agregando funcionalidad nueva, se agregaron pruebas.
- [x] Si el cambio es grande (> 200 líneas), hay que intentar partirlo en
      varios pull requests. De preferencia uno para los controladores + phpunit
      y luego otro para la interfaz.

2023-07-02 18:49 UTC, heduenas commented
<img width="364" alt="Screenshot 2023-07-02 at 11 47 32 AM" src="https://github.com/omegaup/omegaup/assets/597815/9bc68103-41cf-4271-9105-0e451de8a27c">

@IngridRB  @carlosabcs @tvanessa que opinan de juntar las las primeras 3 columnas (para concursos) o 4 columnas (para cursos) en una misma columna? Esas primeras columnas estan muy vacias mientras la de la pregunta tiene casi toda la informacion.

2023-07-05 17:31 UTC, IngridRB commented
> <img alt="Screenshot 2023-07-02 at 11 47 32 AM" width="364" src="https://user-images.githubusercontent.com/597815/250392257-9bc68103-41cf-4271-9105-0e451de8a27c.png">
> @IngridRB @carlosabcs @tvanessa que opinan de juntar las las primeras 3 columnas (para concursos) o 4 columnas (para cursos) en una misma columna? Esas primeras columnas estan muy vacias mientras la de la pregunta tiene casi toda la informacion.

@heduenas se ve mejor como lo propones

2023-07-08 04:24 UTC, carlosabcs commented
@heduenas yo también creo que el cambio que sugieres está bien.

@IngridRB por favor en cuanto subas los commits con el cambio me etiquetas o algo para saber que tengo que revisar de nuevo este PR.

2023-07-20 16:44 UTC, carlosabcs requested changes
Cuando tengas estos cambios listos, asegúrate de corregir las pruebas unitarias para que ya no estén fallando y aprobaré el PR.

2023-07-20 16:44 UTC, carlosabcs commented on frontend/www/js/omegaup/components/arena/Clarification.vue
> +    </td> -->
Por favor, borra este comentario.

2023-07-20 16:44 UTC, carlosabcs commented on frontend/www/js/omegaup/components/arena/ClarificationList.vue
> +            </slot> -->
Si este comentario ya no es necesario, bórralo. No deberían haber comentarios en el código. Salvo extremas excepciones.

2023-07-20 16:44 UTC, carlosabcs commented on frontend/www/js/omegaup/components/arena/ClarificationList.vue
> +            <th class="text-center" scope="col">{{ T.wordsTime }}</th> -->
Igual aquí

2023-07-20 16:44 UTC, carlosabcs commented on frontend/www/js/omegaup/components/course/Clarifications.vue
> +      <th class="text-center" scope="col">{{ T.wordsProblem }}</th> -->
Igual aquí

2023-07-21 03:37 UTC, IngridRB commented
@carlosabcs te dejo capturas de como se ve ahora la tabla de clarificaciones con los cambios sugeridos

**Tabla de clarificaciones en Concurso**

![image](https://github.com/omegaup/omegaup/assets/110271913/5cd1383c-ac52-47a3-b0a5-bc73bd42e204)

**Tabla de clarificaciones en Cursos**

![image](https://github.com/omegaup/omegaup/assets/110271913/5a5d64b1-71f0-447d-a43c-69211daa1045)

**Tabla de clarificaciones para alumnos**

![image](https://github.com/omegaup/omegaup/assets/110271913/87c41e22-c143-4e50-a644-84b56dd2e0d0)

2023-07-21 17:52 UTC, carlosabcs approved these changes
Gracias por aplicar los nuevos cambios.

2023-07-23 17:42 UTC, heduenas approved these changes

2023-07-23 17:53 UTC, merged