Ordenando el contenido horizontalmente en Problemas por Autor
omegaup/omegaup pull request #7140
Opened 2023-07-25 04:25 UTC by IngridRB

# Descripción

![image](https://github.com/omegaup/omegaup/assets/110271913/8816a68a-b771-45ee-96f1-f5726cfaab6d)

# Versión desktop

![image](https://github.com/omegaup/omegaup/assets/110271913/19753d85-3916-4a33-a212-781eaeca3ec1)

Fixes: #7139

# Checklist:

- [x] El código sigue la [guía de
      estilo](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) de
      omegaUp.
- [x] Se corrieron todas las pruebas y pasaron.
- [x] Si se está agregando funcionalidad nueva, se agregaron pruebas.
- [x] Si el cambio es grande (> 200 líneas), hay que intentar partirlo en
      varios pull requests. De preferencia uno para los controladores + phpunit
      y luego otro para la interfaz.

2023-07-27 13:00 UTC, carlosabcs requested changes

2023-07-27 13:00 UTC, carlosabcs commented on frontend/www/js/omegaup/components/problem/BaseList.vue
> +            <th scope="col" class="text-right align-middle text-nowrap">
Considero que los títulos de las columnas sí deben estar TODOS centrados, por fa déjale el `text-center` aquí.

2023-07-27 13:00 UTC, carlosabcs commented on frontend/www/js/omegaup/components/problem/BaseList.vue
> +              class="text-right align-middle text-nowrap"
Igual aquí, centrado.

2023-07-27 13:00 UTC, carlosabcs commented on frontend/www/js/omegaup/components/problem/BaseList.vue
> +            <th scope="col" class="text-right align-middle text-nowrap">
...Y aquí

2023-07-27 13:00 UTC, carlosabcs commented on frontend/www/js/omegaup/components/problem/FilterAuthors.vue
> +  <div class="mx-auto card col-12 col-sm-5 col-lg-12">
Pregunta, los `col-12 col-sm-5 col-lg-12` realmente están haciendo una diferencia aquí? En teoría, para que funcionen **correctamente**, el elemento debe ser hijo directo de un elemento con clase `row`.

2023-07-27 13:00 UTC, carlosabcs commented on frontend/www/js/omegaup/components/problem/FilterAuthors.vue
> +  <div class="mx-auto card col-12 col-sm-5 col-lg-12">
Lo mismo para `FilterDifficulty` y `FilterQuality`

2023-08-08 13:47 UTC, carlosabcs commented on frontend/www/js/omegaup/components/problem/FilterAuthors.vue
> +  <div class="mx-auto card col-12 col-sm-5 col-lg-12">
@IngridRB solo faltaría atender a este comentario.

2023-08-12 17:29 UTC, heduenas approved these changes

2023-08-14 17:33 UTC, merged