[ DESKTOP ] IntroJS - Como creo un curso
omegaup/omegaup pull request #7173
Opened 2023-08-11 18:36 UTC by galovdev

# Descripción

*Como nuevo usuario, quiero saber como creo un curso*

- La guia interaciva solo aparecera la primera ves que el usuario entra a esa seccion, y lo puede saltar si asi lo decide con la X.

Fixes: #7135

# Comentarios

Si hay comentarios para los reviewers (por ejemplo, dónde hay que empezar a
revisar, algo a lo que hay que poner atención adicional, etc.), todo eso se
puede poner en esta sección.

También si faltan cosas por hacer, se puede hacer un checklist en esta sección.

Si no se utiliza, esta sección se puede eliminar.

# Checklist:

- [ ] El código sigue la [guía de
      estilo](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) de
      omegaUp.
- [ ] Se corrieron todas las pruebas y pasaron.
- [ ] Si se está agregando funcionalidad nueva, se agregaron pruebas.
- [ ] Si el cambio es grande (> 200 líneas), hay que intentar partirlo en
      varios pull requests. De preferencia uno para los controladores + phpunit
      y luego otro para la interfaz.

2023-08-23 02:42 UTC, pabo99 reviewed
Te dejé un comentario con el cual se puede arreglar la prueba

2023-08-23 02:42 UTC, pabo99 commented on frontend/www/js/omegaup/components/course/Form.vue
> +  @Prop() hasVisitedSection!: boolean;
Creo que ya vi a que se debe el error de las pruebas de Cypress. 

Resulta que el componente donde estás mostrando el introJS se utiliza para 2 cosas:

- Para crear un curso
- Para editar un curso

Entonces, parece que el modal se está mostrando también cuando se edita un curso.

La forma más sencilla que se me ocurre para arreglar la falla es agregarle un valor por defecto a esta prop:
```suggestion
  @Prop({ default: true }) hasVisitedSection!: boolean;
```
si lo configuramos como `true`, en los lugares donde no lo envíes explícitamente no mostrará el modal, en este caso en la vista de "Editar curso"

2023-08-23 06:03 UTC, pabo99 reviewed
Hay código que agregaste, pero no tiene muho sentido meterlo en este PR, lo puedes quitar porfa? para revisar si ahora si ya pasan las pruebas

2023-08-23 06:03 UTC, pabo99 commented on cypress/integration/basic_commands.spec.ts
> +    );
¿Esto por qué se agregó? Se supone que esas validaciones ya las hace la función de `verifyCourseOptions`
```suggestion
```

2023-08-23 06:03 UTC, pabo99 commented on cypress/integration/basic_commands.spec.ts
> +    );
Mismo comentario que el anterior
```suggestion
```

2023-08-23 20:42 UTC, pabo99 approved these changes
Excelente. Se ve bien el cambio

2023-08-23 20:43 UTC, pabo99 commented
@tvanessa ¿Nos puedes apoyar a revisar las redacciones de la guía interactiva?

2023-08-28 04:14 UTC, heduenas approved these changes

2023-08-30 01:53 UTC, tvanessa requested changes

2023-08-30 01:53 UTC, tvanessa commented on frontend/templates/en.lang
> +createCourseInteractiveGuideLevel = "Select course level"
```suggestion
createCourseInteractiveGuideLevel = "Select course level of difficulty"
```

2023-08-30 01:53 UTC, tvanessa commented on frontend/templates/en.lang
> +createCourseInteractiveGuideAskInformation = "Select if you want to request information from participants."
```suggestion
createCourseInteractiveGuideAskInformation = "Select if you want to request personal information from students."
```

2023-08-30 01:53 UTC, tvanessa commented on frontend/templates/es.lang
> +createCourseInteractiveGuideBasicInformation = "Selecciona si se requerirá información básica del participante."
```suggestion
createCourseInteractiveGuideBasicInformation = "Selecciona si es obligatorio que cada estudiante comparta su información personal."
```

2023-08-30 01:53 UTC, tvanessa commented on frontend/templates/en.lang
> +createCourseInteractiveGuideBasicInformation = "Select if basic participant information will be required."
```suggestion
createCourseInteractiveGuideBasicInformation = "Select if it is mandatory for each student to share their personal information."
```

2023-08-30 01:53 UTC, tvanessa commented on frontend/templates/es.lang
> +createCourseInteractiveGuideAskInformation = "Selecciona si deseas solicitar información de los participantes."
```suggestion
createCourseInteractiveGuideAskInformation = "Selecciona si deseas solicitar información personal de cada estudiante."
```

2023-08-30 01:53 UTC, tvanessa commented on frontend/templates/es.lang
> +createCourseInteractiveGuideLanguage = "Selecciona los lenguajes de programación permitidos."
```suggestion
createCourseInteractiveGuideLanguage = "Selecciona los lenguajes de programación permitidos en tu curso."
```

2023-08-30 01:53 UTC, tvanessa commented on frontend/templates/es.lang
> +createCourseInteractiveGuideLevel = "Seleccione el nivel del curso"
```suggestion
createCourseInteractiveGuideLevel = "Selecciona el nivel de dificultad del curso"
```

2023-08-30 01:53 UTC, tvanessa commented on frontend/templates/en.lang
> +createCourseInteractiveGuideSubmit = "Submit course"
```suggestion
createCourseInteractiveGuideSubmit = "Schedule course"
```

2023-08-30 01:53 UTC, tvanessa commented on frontend/templates/es.lang
> +createCourseInteractiveGuideWelcome = "Bienvenido, vamos a crear un curso."
```suggestion
createCourseInteractiveGuideWelcome = "Te damos la bienvenida, vamos a crear un curso."
```

2023-08-30 01:53 UTC, tvanessa commented on frontend/templates/pt.lang
>  courseUnarchivedSuccess = "Curso desarquivado exitosamente."
Puedes usar un traductor para corregir las traducciones al portugués?

2023-08-31 19:29 UTC, galovdev commented on frontend/templates/pt.lang
>  courseUnarchivedSuccess = "Curso desarquivado exitosamente."
Listo

2023-09-11 03:29 UTC, galovdev commented
Ya quedaron los cambios solicitados en este PR

2023-09-11 20:58 UTC, tvanessa approved these changes

2023-09-14 17:20 UTC, merged