Cambiando los strings "usuario" por "coder" o "cuenta" en es.lang
omegaup/omegaup pull request #7208
Opened 2023-08-25 20:18 UTC by Karyme-Nava

# Descripción

Se cambiaron todas las cadenas que contenían las palabras "usuario" o "usuarios" por "coder" o "cuenta" dependiendo del contexto de cada cadena.

Part of: #6045 

# Comentarios

Para este PR sólo se cambiaron las cadenas del archivo es.lang para después hacer las traducciones con las correcciones que se soliciten.

También, al ir cambiando las cadenas me di cuenta de algunas cosas:

- Hay ocasiones en las que cambiar la palabra "usuario" hace que la cadena pierda su significado o no se entienda tan bien, por ejemplo: 
![image](https://github.com/omegaup/omegaup/assets/78821834/2d660407-4b14-4745-870c-4bf835f49281)
- Hay algunas cadenas en las que a pesar de usar la palabra "coder", la frase no se puede hacer gender-free (los coders, este coder, el coder, etc).

# Checklist:

- [x] El código sigue la [guía de estilo](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) de omegaUp.
- [ ] Se corrieron todas las pruebas y pasaron.
- [ ] Si se está agregando funcionalidad nueva, se agregaron pruebas.
- [x] Si el cambio es grande (> 200 líneas), hay que intentar partirlo en varios pull requests. De preferencia uno para los controladores + phpunit y luego otro para la interfaz.

2023-08-29 02:49 UTC, tvanessa requested changes

2023-08-29 02:49 UTC, tvanessa commented on frontend/templates/es.lang
> +courseListSubmissionsByGroup = "Envíos realizados por coders de este curso"
```suggestion
courseListSubmissionsByGroup = "Envíos realizados por estudiantes de este curso"
```

2023-08-29 02:49 UTC, tvanessa commented on frontend/templates/es.lang
> +courseRegistrationPreAcceptedDescription = "El coder ha sido invitado explícitamente al curso"
```suggestion
courseRegistrationPreAcceptedDescription = "Esta cuenta ha sido invitada explícitamente al curso"
```

2023-08-29 02:49 UTC, tvanessa commented on frontend/templates/es.lang
> +demotionProblemEmailBannedBody = "<p>Estimado <strong>%(user_name)</strong>:</p><p>El acceso a tu problema <strong>%(problem_name)</strong> en omegaup.com ha sido restringido debido a que ha sido rep
```suggestion
demotionProblemEmailBannedBody = "<p>Estimado <strong>%(user_name)</strong>:</p><p>El acceso a tu problema <strong>%(problem_name)</strong> en omegaup.com ha sido restringido debido a que ha sido reportado como un problema inapropiado. El equipo de omegaUp revisó este reporte y confirmó que el problema no es apropiado debido a que <em>%(reason)<em>.</p><p>Para desbloquear el problema y que vuelva a mostrarse en la lista de problemas, por favor sigue los siguientes pasos:</p><p><ol><li>Revisa y edita tu problema, asegurate que describa un problema, no sea ofensivo ni spam.</li><li>Una vez que hayas resuelto la razón por la que tu problema fue bloqueado, manda un email a <a href=\"mailto:quality@omegaup.com\" target=\"_top\">quality@omegaup.com</a> para que sea revisado y reactivado.</li></ol></p><p>De no seguirse los pasos mencionados arriba, el problema no se volverá a mostrar en la lista de problemas ni se podrá utilizar en concursos. En caso de reincidir 3 veces, omegaUp se reserva el derecho de suspender tu cuenta.</p><p>omegaUp es una plataforma para ayudar a las personas a mejorar sus habilidades en ingeniería de software resolviendo problemas de código y compitiendo en concursos de programación. omegaUp da la bienvenida a todos los problemas que ayuden a cumplir esa meta.</p><p>Gracias,</p><p>Equipo omegaUp</p>"
```

2023-08-29 02:49 UTC, tvanessa commented on frontend/templates/es.lang
> +demotionProblemEmailWarningBody = "<p>Estimado %(user_name):</p><p>El acceso a tu problema %(problem_name) en omegaup.com ha sido marcado con una advertencia debido a que ha sido reportado por los co
```suggestion
demotionProblemEmailWarningBody = "<p>Estimado %(user_name):</p><p>El acceso a tu problema %(problem_name) en omegaup.com ha sido marcado con una advertencia debido a que ha sido reportado por otras cuentas. El equipo de omegaUp revisó este reporte y confirmó que el problema tiene aspectos mejorables debido a que %(reason).</p><p>Para retirar la notificación de advertencia del problema y que vuelva a mostrarse de manera normal, por favor sigue los siguientes pasos:</p><p><ol><li>Revisa y edita tu problema.</li><li>Una vez que hayas resuelto la razón por la que tu problema fue marcado con una advertencia, manda un email a quality@omegaup.com para que sea revisado.</li></lo></p><p>De no seguirse los pasos mencionados arriba, el problema mostrará una advertencia a quienes intenten resolverlo y/o verlo.</p><p>omegaUp es una plataforma para ayudar a las personas a mejorar sus habilidades en ingeniería de software resolviendo problemas de código y compitiendo en concursos de programación. omegaUp da la bienvenida a todos los problemas que ayuden a cumplir esa meta.</p><p>Gracias,</p><p>Equipo omegaUp</p>"
```

2023-08-29 02:49 UTC, tvanessa commented on frontend/templates/es.lang
> +groupsCsvHelp = "<p>Agrega rápidamente múltiples identidades a este grupo. Las identidades no son cuentas reales y no necesitan tener un correo electrónico o validar su cuenta.</p>\n<p>Las identidade
```suggestion
groupsCsvHelp = "<p>Agrega rápidamente múltiples identidades a este grupo. Las identidades no son cuentas normales y no necesitan tener un correo electrónico o validar su cuenta.</p>\n<p>Las identidades deben estar en un archivo <code>.csv</code> con el siguiente formato:\n<samp><pre>username,name,country_id,state_id,gender,school_name\nusername-1,Developer Diana,MX,AGU,female,Best School\nusername-2,Danny Dev,MX,AGU,male,Best School</pre></samp></p>"
```

2023-08-29 02:49 UTC, tvanessa commented on frontend/templates/es.lang
> +invalidUser = "Nombre de la cuenta no válido."
```suggestion
invalidUser = "Nombre de cuenta no válido."
```

2023-08-29 02:49 UTC, tvanessa commented on frontend/templates/es.lang
> +loginDisabled = "Tu cuenta es muy vieja y por tu seguridad ha sido deshabilitado. Para logguearte de nuevo contacta a omegaup-soporte@googlegroups.com"
Creo que las cuentas "viejas" y activas si funcionan. @heduenas me confirmas esto? o realmente se desactivan por tener mucho tiempo?
```suggestion
loginDisabled = "Tu cuenta ha estado inactiva por mucho tiempo y por tu seguridad ha sido deshabilitada. Para ingresar de nuevo contacta a omegaup-soporte@googlegroups.com"
```

2023-08-29 02:49 UTC, tvanessa commented on frontend/templates/es.lang
> +mustLoginToFilterUsers = "Para filtrar los coders del ranking debes iniciar sesión."
```suggestion
mustLoginToFilterUsers = "Para filtrar a coders del ranking debes iniciar sesión."
```

2023-08-29 02:49 UTC, tvanessa commented on frontend/templates/es.lang
> +mustUpdateBasicInfoToFilterUsers = "Para filtrar los coders del ranking debes actualizar tu información básica."
```suggestion
mustUpdateBasicInfoToFilterUsers = "No puedes usar los filtros del ranking si la información de tu perfil no está completa."
```

2023-08-29 02:49 UTC, tvanessa commented on frontend/templates/es.lang
> +parameterUsernameInUse = "El nombre de cuenta ya fue tomado"
```suggestion
parameterUsernameInUse = "El nombre de cuenta no esta disponible"
```

2023-08-29 02:49 UTC, tvanessa commented on frontend/templates/es.lang
> +profileAddIdentitiesTooltip = "Agrega identidades utilizando el nombre de su cuenta de omegaUp"
```suggestion
profileAddIdentitiesTooltip = "Agrega identidades utilizando el nombre de cuenta de omegaUp"
```

2023-08-29 02:49 UTC, tvanessa commented on frontend/templates/es.lang
> +teamsGroupsCsvHelp = "## Agrega rápidamente múltiples identidades como equipo a este grupo. Las identidades no son cuentas reales y no necesitan tener un correo electrónico o validar su cuenta.\n\n##
```suggestion
teamsGroupsCsvHelp = "## Agrega rápidamente múltiples identidades como equipo a este grupo. Las identidades no son cuentas normales y no necesitan tener un correo electrónico o validar su cuenta.\n\n## Las identidades deben estar en un archivo `.csv` con el siguiente formato:\n```\nusername,name,country_id,state_id,gender,school_name\nteam-1,Team 1,MX,AGU,decline,Best School\nteam-2,Teams 2,MX,AGU,other,Best School\n```"
```

2023-08-29 02:49 UTC, tvanessa commented on frontend/templates/es.lang
> +userAlreadyAcceptedPrivacyPolicy = "El coder ya había aceptado la política de privacidad"
```suggestion
userAlreadyAcceptedPrivacyPolicy = "Esta cuenta ya había aceptado la política de privacidad"
```

2023-08-29 02:49 UTC, tvanessa commented on frontend/templates/es.lang
> +userAlreadyHasSelectedRole = "El coder ya cuenta con rol seleccionado"
```suggestion
userAlreadyHasSelectedRole = "Esta cuenta ya tiene asignado el rol seleccionado"
```

2023-08-29 02:49 UTC, tvanessa commented on frontend/templates/es.lang
> +userDoesNotHaveAnyPasswordChangeRequest = "El coder no ha realizado la solicitud de cambio de contraseña en las últimas 24 horas."
```suggestion
userDoesNotHaveAnyPasswordChangeRequest = "La cuenta no ha realizado la solicitud de cambio de contraseña en las últimas 24 horas."
```

2023-08-29 02:49 UTC, tvanessa commented on frontend/templates/es.lang
> +userEndTimeUpdatedSuccessfully = "El tiempo de finalización del concurso para el coder se ha actualizado correctamente."
```suggestion
userEndTimeUpdatedSuccessfully = "El tiempo de finalización del concurso se ha actualizado correctamente."
```

2023-08-29 02:49 UTC, tvanessa commented on frontend/templates/es.lang
> +userNotExist = "Coder no existe"
```suggestion
userNotExist = "La cuenta no existe"
```

2023-08-29 02:49 UTC, tvanessa commented on frontend/templates/es.lang
> +userNotInListOfRequests = "Este coder no tiene una solicitud pendiente."
```suggestion
userNotInListOfRequests = "Esta cuenta no tiene una solicitud pendiente."
```

2023-08-29 02:49 UTC, tvanessa commented on frontend/templates/es.lang
> +userOrMailNotFound = "Nombre de cuenta o mail no encontrado"
```suggestion
userOrMailNotFound = "Nombre de cuenta o correo electrónico no encontrado"
```

2023-08-29 02:49 UTC, tvanessa commented on frontend/templates/es.lang
> +userProfileIsPrivate = "El perfil de este coder está marcado como privado; alguna información no se mostrará"
```suggestion
userProfileIsPrivate = "El perfil de esta cuenta está marcado como privado; alguna información no se mostrará"
```

2023-08-29 02:49 UTC, tvanessa commented on frontend/templates/es.lang
> +userRankOfTheMonthHeader = "Los mejores %(count) coders con mayor puntaje del mes"
```suggestion
userRankOfTheMonthHeader = "%(count) coders con mayor puntaje del mes"
```

2023-08-29 02:49 UTC, tvanessa commented on frontend/templates/es.lang
> +usersCanNotBeAddedInContestForTeams = "No se pueden agregar coders en concursos para equipos"
```suggestion
usersCanNotBeAddedInContestForTeams = "No se pueden agregar cuentas individuales en concursos para equipos"
```

2023-08-29 02:49 UTC, tvanessa commented on frontend/templates/es.lang
> +userRemoveSuccess = "Coder exitosamente eliminado."
```suggestion
userRemoveSuccess = "Cuenta exitosamente eliminada."
```

2023-08-29 02:49 UTC, tvanessa commented on frontend/templates/es.lang
> +wordsMultipleUser = "Múltiples coders (Separados por comas o nueva línea)"
```suggestion
wordsMultipleUser = "Múltiples cuentas (separados por comas o nueva línea)"
```

2023-08-29 02:49 UTC, tvanessa commented on frontend/templates/es.lang
> +wordsUsersFeedback = "Opiniones de los coders"
```suggestion
wordsUsersFeedback = "Opiniones de coders"
```

2023-08-29 02:49 UTC, tvanessa commented on frontend/templates/es.lang
> +wordsUser = "Coder"
puedes buscar en que componente/s se usa esta cadena?

2023-08-30 00:56 UTC, Karyme-Nava commented on frontend/templates/es.lang
> +wordsUser = "Coder"
Hay algunos casos en donde se refiere al usuario de varias formas y se ve algo raro como en esta:
![Captura desde 2023-08-29 18-21-54](https://github.com/omegaup/omegaup/assets/78821834/61b748f1-0123-4e78-9e9f-a58289b2c6c3)
Ahí se hace referencia a concursante, cuenta y coder, ¿debería de cambiar algunas cadenas para que todas digan lo mismo?
Antes estaba así:
![Captura desde 2023-08-29 18-22-18](https://github.com/omegaup/omegaup/assets/78821834/4d1183a1-dddc-4082-a32e-284fc204358f)

2023-09-05 20:34 UTC, tvanessa commented on frontend/templates/es.lang
> +wordsUser = "Coder"
![264196921-61b748f1-0123-4e78-9e9f-a58289b2c6c3](https://github.com/omegaup/omegaup/assets/13296248/ff4ace09-923b-493e-a6e6-2e8a616ab72b)

Dejemos `cuentas` y `concursante`. Es probable que tengamos que crear nuevas cadenas para dejar de usar `wordsUser`

2023-09-12 06:01 UTC, heduenas commented on frontend/templates/en.lang
> +wordsAccountName = "Account name"
```suggestion
wordsAddContestantEditContest = "Account name"
```

2023-09-12 19:49 UTC, tvanessa commented on frontend/templates/en.lang
> +wordsAccountName = "Account name"
Entonces se deben crear cadenas para cada caso.

2023-09-12 19:52 UTC, tvanessa commented on frontend/templates/en.lang
> +wordsAccountName = "Account name"
usar un formato parecido a:
```
contestEdit = "Edit contest"
contestEditAddProblemSearchByAlias = "Alias"
contestEditAddProblemSearchByAll = "All"
contestEditAddProblemSearchById = "Id"
contestEditAddProblemSearchByTitle = "Title"
contestEditAdministrativeLinks = "Administrative Links"
contestEditArchive = "Archive"
contestEditArchiveConfirmText = "Are you sure you want to perform this action?"
contestEditArchiveContest = "Archive contest" ```

2023-09-18 19:36 UTC, tvanessa approved these changes

2023-09-19 07:55 UTC, heduenas approved these changes

2023-09-19 15:35 UTC, merged