Cambios agregados
omegaup/omegaup pull request #7249
Opened 2023-09-15 06:11 UTC by OmarGO1

# Descripción

1. Se agregaron las nuevas columnas e iconos.
2. Se agregó un paginador.
3. Se agregaron filtros a la vista de administrador en cursos.
4. Se eliminaron/corrigieron algunas pruebas

Vista de problema:
![image](https://github.com/omegaup/omegaup/assets/107278679/6a27061d-1786-49ce-8116-92895c5633e1)

Vista de problema en concurso:
![image](https://github.com/omegaup/omegaup/assets/107278679/0edbd96b-2bc9-48fe-a973-fff141673434)

Vista de problema en curso:
![image](https://github.com/omegaup/omegaup/assets/107278679/b1c5c104-0e5d-4100-bf7a-6ad5eb284cd2)

Vista administrador de concurso:
![image](https://github.com/omegaup/omegaup/assets/107278679/fffeac80-908d-4800-8a93-94aa8bdcf9a7)

Vista administrador curso:
![image](https://github.com/omegaup/omegaup/assets/107278679/e39196db-6424-4eb1-9209-c5536c1aec61)

Si tu cambio toca la interfaz, hay que incluir una captura de pantalla.

Fixes: #6795 
Fixes: #6796 
Fixes: #6797

2023-09-26 14:09 UTC, carlosabcs requested changes
Hay cambios menores por hacer, pero a grandes rasgos está muy bien ejecutado este cambio :)

2023-09-26 14:09 UTC, carlosabcs commented on frontend/www/js/omegaup/components/arena/RunDetailsPopup.vue
> +            <tt>{{ data.guid.substring(0, 8) }}</tt>
Quizás sea bueno crear un método como `getShortGuid(guid)`, para que quede claro por qué es que haces `substring(0, 8)`.

2023-09-26 14:09 UTC, carlosabcs commented on frontend/www/js/omegaup/components/arena/Runs.vue
> +              <th hidden>GUID</th>
Esto debería ser una cadena de traducción, a pesar de que está en `hidden`.

2023-09-26 14:09 UTC, carlosabcs commented on frontend/www/js/omegaup/components/arena/Runs.vue
>                    <tt>{{ run.guid.substring(0, 8) }}</tt>
Igual aquí, podrías reutilizar el método.

2023-09-26 14:09 UTC, carlosabcs commented on frontend/www/js/omegaup/components/arena/Runs.vue
> +                v-show="contestAlias != null && !isCourse"
Aquí no basta con `contestAlias && !isCourse`?

2023-09-26 14:09 UTC, carlosabcs commented on frontend/www/js/omegaup/components/arena/Runs.vue
> +    if (run.status !== 'ready' || run.status_memory === 'MEMORY_NOT_AVAILABLE')
Estos `status_memory` mejor ponlos en un enum más arriba y utilizas esa variable para hacer las comparaciones.

2023-09-26 14:09 UTC, carlosabcs commented on frontend/www/js/omegaup/components/arena/Runs.vue
> +      run.status_runtime === 'RUNTIME_NOT_AVAILABLE'
Lo mismo con este `status_runtime`

2023-09-26 14:09 UTC, carlosabcs commented on frontend/www/js/omegaup/components/arena/Runs.vue
> +      case 'EXECUTION_JUDGE_ERROR':
Lo mismo para estos `execution`

2023-09-26 14:09 UTC, carlosabcs commented on frontend/www/js/omegaup/components/arena/Runs.vue
> +      case 'OUTPUT_EXCEEDED':
Y lo mismo para los `output`.

2023-09-30 19:27 UTC, heduenas approved these changes
Queda aprobado de mi parte, solo quiero esperar a ver que funcionan bien tus ultimos cambios al backend en produccion.

2023-10-17 06:53 UTC, pabo99 reviewed
Un par de cambios para empezar. Aún me falta ver si podemos simplificar los cambios en el archivo de `Runs.vue`

2023-10-17 06:53 UTC, pabo99 commented on frontend/www/js/omegaup/components/arena/RunDetailsPopup.vue
> +  }
Acá bien se podría utilizar una propiedad computada en lugar de un método:
```suggestion
  get shortGuid(): string {
    return this.data.guid.substring(0, 8);
  }
```
Y al utilizarla ya lo podrías hacer sin necesidad de colocar los paréntesis

2023-10-17 06:53 UTC, pabo99 commented on frontend/www/js/omegaup/components/arena/Runs.vue
> +  @Prop({ default: false }) isCourse!: boolean;
¿Se te ocurre algún otro nombre para esta propiedad? Pensando en que en un fututro esto también se utilice en otra vista que no sea de cursos y no haya necesifdad de cambiarle el nombre.

2023-10-17 20:13 UTC, OmarGO1 commented on frontend/www/js/omegaup/components/arena/Runs.vue
> +  @Prop({ default: false }) isCourse!: boolean;
Que tal algo como basicView, userFriendlyView, simplifiedView ?

2023-10-17 20:31 UTC, pabo99 commented on frontend/www/js/omegaup/components/arena/Runs.vue
> +  @Prop({ default: false }) isCourse!: boolean;
Si, `simplifiedView` me agrada. El siguiente paso sería intentar meterlo en slots todo el contenido que varía entre cada una d elas 2 vistas, pero eso vamos a dejarlo para otro cambio. Porque eso haría que este se volviera aún mas grande

2023-10-18 06:27 UTC, pabo99 reviewed
Además de los cometnarios, encontré un par de errores en el componente de `omegaup-user-username`. Estaría bien que se pudieran corrgir en este PR:

- Cuando se selecciona un usuario dando clic en su username se quita el hash de  la url. La forma de solucionarlo es agregando una nueva propiedad en el componente llamada `href` y que por defecto tenga el valor `#` para que todo siga funcionando como hasta ahora. Sólo en el componente de `Runs.vue` habrá que mandar esa propiedad con el valor: `"#runs"`.

- La bandera del pais de cada usuario no se muestra. Eso se debe a que se está mandando un atributo que no existe en el objeto `run`. El atributo correcto debería ser `country` en lugar de `country_id`.

Otra cosa que noté es que los dropdowns de Execution y Output no muestran correctamente el breadcrums. ¿Puedes revisar si es fácil implementarlo? Fíjate como funciona cuando seleccionas el lenguaje, veredicto, etc.

2023-10-18 06:27 UTC, pabo99 commented on frontend/www/js/omegaup/components/arena/Runs.vue
> +                  @click.prevent="filterProblem.key = run.alias"
Esto no va a funcionar correctamente. Tendrías que llenar el objeto completo, eso lo puedes lograr con el método `onEmitFilterChanged` de la siguiente forma:
```suggestion
                  @click="
                    onEmitFilterChanged({
                      filter: 'problem',
                      value: run.alias,
                    })
                  "
```

2023-10-18 06:27 UTC, pabo99 commented on frontend/www/js/omegaup/components/arena/Runs.vue
> +      return NumericOutputStatus.Incorrect;
Guard clause pattern:
```suggestion
    if (run.output !== StringOutputStatus.Incorrect) {
      return NumericOutputStatus.Correct;
    }
    return NumericOutputStatus.Incorrect;
```

2023-10-18 06:28 UTC, pabo99 commented
> Un par de cambios para empezar. Aún me falta ver si podemos simplificar los cambios en el archivo de `Runs.vue`

Me hubiera gustado `slots` para no moverle tanto al componente de `Runs`, pero este PR crecería demasiado. Así que mejor lo dejamos para otro PR

2023-10-18 09:09 UTC, OmarGO1 commented on frontend/www/js/omegaup/components/arena/Runs.vue
> +              <th hidden>{{ T.runGUID }}</th>
Aunque creo que si voy a dejar esa parte, lo mejor sería dejarlo completo y usar el v-show

2023-10-18 10:20 UTC, OmarGO1 commented on frontend/www/js/omegaup/components/arena/Runs.vue
> +      return NumericOutputStatus.Incorrect;
Listo, solo que mis últimos cambios no están pasando una prueba de Cypress, más tarde la reviso

2023-10-18 16:59 UTC, pabo99 commented
Creo saber a que se debe el error.

En la función:
https://github.com/omegaup/omegaup/blob/3ac61bca826b563512111b717813545079d0a684/cypress/support/pageObjects/problemPage.ts#L47-L51

vas a encontrar el selector `a[href="#runs"]` al que se le dispara un evento clic:
```ts
cy.get('a[href="#runs"]').click(); 
```
Pero ahora acabamos de agregar ese mismo hash para todos los registros de envíos (en el nombre del usuario). Así que habrá que ser más específicos en el selector anterior. Yo creo que con que le indiquemos que su contenedor directo es un `li`, por el momento sería suficiente:

```ts
cy.get('li>a[href="#runs"]').click(); 
```

2023-10-18 19:20 UTC, pabo99 approved these changes
LGTM

2023-10-18 19:32 UTC, merged