Agregando un selector de fecha en el formulario de registro.
omegaup/omegaup pull request #7255
Opened 2023-09-21 15:57 UTC by IngridRB

# Descripción

Se agrego un selector de fecha en el formulario de registro. Y si es menor de 13 años, se solicita la dirección de correo electrónico de su figura parental en lugar de su propia dirección de correo electrónico.

![image](https://github.com/omegaup/omegaup/assets/110271913/2057b5f8-3b11-426d-a0d3-1fae3a038616)

![image](https://github.com/omegaup/omegaup/assets/110271913/b61653a6-9a0e-4437-a013-3f9a1548760e)

Fixes: #7252 

# Checklist:

- [x] El código sigue la [guía de
      estilo](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) de
      omegaUp.
- [x] Se corrieron todas las pruebas y pasaron.
- [x] Si se está agregando funcionalidad nueva, se agregaron pruebas.
- [x] Si el cambio es grande (> 200 líneas), hay que intentar partirlo en
      varios pull requests. De preferencia uno para los controladores + phpunit
      y luego otro para la interfaz.

2023-09-21 16:20 UTC, carlosabcs requested changes
Por ahora, por favor aplica los cambios sugeridos, además considero que es mejor que cuando se muestre solo lo de la fecha de nacimiento, lo pongas alineada hacia la izquierda.

2023-09-21 16:20 UTC, carlosabcs commented on frontend/www/js/omegaup/components/login/Signup.vue
> +          <div v-if="userAge" class="col-md-4">
yo usaría aquí `v-show` y creo que es mejor ponerle un nombre más intuitivo a la bandera, algo como `isUnder13User`

2023-09-21 16:20 UTC, carlosabcs commented on frontend/www/js/omegaup/components/login/Signup.vue
> +  get userAge() {
Aquí a esta variable tocaría que le cambies el nombre a `isUnder13User`.

2023-09-21 16:21 UTC, carlosabcs commented
@heduenas puedes darle una revisada también a cómo se ve la UI?

2023-09-26 04:16 UTC, carlosabcs reviewed
Nada más cambios menores y ya estaría.

2023-09-26 04:16 UTC, carlosabcs commented on frontend/templates/es.lang
> +loginParentEmail = "Correo electrónico del padre"
@heduenas, @tvanessa, aquí funciona del "padre o madre"?

2023-09-26 04:16 UTC, carlosabcs commented on frontend/templates/pt.lang
> +loginParentEmail = "E-mail do pai"
Aquí lo ajustas también de acuerdo a lo que comenten Hugo y Vane

2023-09-27 00:16 UTC, tvanessa commented on frontend/templates/es.lang
> +loginParentEmail = "Correo electrónico del padre"
```suggestion
loginParentEmail = "Correo electrónico de figura parental"
```

2023-09-27 00:19 UTC, tvanessa commented
Puedes agregar un `checkbox` para cambiar los textos de las cadenas?
y si es posible alinea a la izquierda el campo que queda solo
Te dejo unos ejemplos:
![Screen Shot 2023-09-26 at 4 53 00 PM](https://github.com/omegaup/omegaup/assets/13296248/079e7043-727d-4005-b9b3-ce754a9fa8e1)
![Screen Shot 2023-09-26 at 4 53 39 PM](https://github.com/omegaup/omegaup/assets/13296248/c279f3ba-b004-41ee-9e6c-abc16c47cbdc)

El default del checkbox seria vacio.

2023-09-28 21:57 UTC, IngridRB commented on frontend/templates/es.lang
> +loginParentEmail = "Correo electrónico del padre"
@tvanessa "de figura parental" lo uso para español y portugués?

2023-09-28 22:03 UTC, IngridRB commented
> Puedes agregar un `checkbox` para cambiar los textos de las cadenas? y si es posible alinea a la izquierda el campo que queda solo Te dejo unos ejemplos: ![Screen Shot 2023-09-26 at 4 53 00 PM](https://user-images.githubusercontent.com/13296248/270824814-079e7043-727d-4005-b9b3-ce754a9fa8e1.png) ![Screen Shot 2023-09-26 at 4 53 39 PM](https://user-images.githubusercontent.com/13296248/270824819-c279f3ba-b004-41ee-9e6c-abc16c47cbdc.png)
> 
> El default del checkbox seria vacio.

@tvanessa agregaría el `checkbox` en lugar de pedir la fecha de nacimiento?? o para cambiar que cadenas?

2023-10-02 05:04 UTC, tvanessa commented on frontend/templates/es.lang
> +loginParentEmail = "Correo electrónico del padre"
si, para español y portugués. Gracias

2023-10-14 15:54 UTC, IngridRB commented
@tvanessa @carlosabcs Añado, que ahora que se agregó el checkbox, las condiciones del tipo de E-mail que pide y la fecha de nacimiento dependen de que si esta seleccionado o no el checkbox (como lo esplique en la descripción). Antes dependía de la fecha ingresada,  si era menor o mayor de trece años se cambiaba el tipo de E-mail que pedía, esa condición aun no la borre, hasta que elijan si prefieren con el checkbox o no??

2023-10-16 15:31 UTC, carlosabcs commented on frontend/www/js/omegaup/components/login/Signup.vue
> +    }
```suggestion
    if (this.over13Checked) {
      this.email = '';
      this.isUnder13 = true;
      return;
    }
    this.parentEmail = '';
    this.isUnder13 = false;
```
Así nos evitamos el usar el `else`.

2023-10-16 15:32 UTC, carlosabcs reviewed
Nada más el cambio menor y este PR estaría aprobado de mi parte, nada más quedarían los comentarios de Vanessa.

2023-10-16 22:54 UTC, tvanessa commented
De mi lado queda aprobado. Gracias

2023-11-01 22:19 UTC, tvanessa commented
@IngridRB tienes dudas sobres los cambios que pidio de Carlos?

2023-11-02 14:18 UTC, IngridRB commented
> @IngridRB¿Tienes dudas sobre los cambios que pidio de Carlos?

@tvanessa @carlosabcs ya genere el cambio que me sugirió Carlos

2023-11-02 21:19 UTC, tvanessa commented
@heduenas  este ya quedo listo

2023-11-07 15:17 UTC, carlosabcs reviewed
El error que marcan las pruebas unitarias es por ese bug que te dejé comentado en el código.

2023-11-07 15:17 UTC, carlosabcs commented on frontend/www/js/omegaup/components/login/Signup.vue
> +          <div v-show="!isUnder13" class="col-md-4 offset-md-2">
Este bloque SOLO debería mostrarse si el usuario ES menor de 13 años.

2023-11-07 15:17 UTC, carlosabcs commented on frontend/www/js/omegaup/components/login/Signup.vue
> +          <div v-show="isUnder13" class="col-md-4 offset-md-2 introjs-email">
... y este bloque debería mostrarse SOLO si el usuario NO es menor de 13 años.

2023-11-13 14:03 UTC, carlosabcs commented on frontend/www/js/omegaup/components/login/Signup.vue
> +            />
```suggestion
            <input
              v-model="over13Checked"
              type="checkbox"
              @change="updateDateRestriction"
              data-over-13-checkbox
            />
```

Agrégale ese data-attribute para poder seleccionar al checkbox desde Cypress.

2023-11-18 03:26 UTC, tvanessa commented on frontend/templates/en.lang
> +loginDisabled = "Your account is too old and it has been disabled for your security. Please contact omegaup-soporte@googlegroups.com to login again."
Puedes dejar esta como estaba? Igual en español y portugues.
```suggestion
loginDisabled = "Your account has been inactive for a long time and has been disabled for your security. Please contact omegaup-soporte@googlegroups.com to login again."
```

2023-11-25 04:43 UTC, pabo99 reviewed
Te dejé unos comentarios para arreglar el error que te ocurría al registrar usuarios menores a 13 años

2023-11-25 04:43 UTC, pabo99 commented on frontend/www/js/omegaup/login/signin.ts
> +              parentEmail?: string;
Ya encontré el motivo por el cual no te permite registrar usuarios menores a 13 años. Los parámetros que recibe la API son los  siguientes:
```suggestion
              birth_date: Date;
              parent_email?: string;
```

2023-11-25 04:43 UTC, pabo99 commented on frontend/www/js/omegaup/login/signin.ts
> +              dateOfBirth,
Acá esto fdebería quedar así:
```suggestion
              birth_date: dateOfBirth,
```

2023-11-25 04:43 UTC, pabo99 commented on frontend/www/js/omegaup/login/signin.ts
> +              request.parentEmail = parentEmail;
Y acá sería de esta forma:
```suggestion
              request.parent_email = parentEmail;
```

2023-11-28 22:09 UTC, carlosabcs commented
@heduenas esto ya fue resuelto y aprobado, cuando puedas le das merge.

2024-02-16 07:55 UTC, heduenas approved these changes

2024-02-16 07:56 UTC, heduenas commented
@pabo99 puedes revisar por que esta fallando el test de cypress de registar usuario?

2024-02-16 08:03 UTC, pabo99 commented
Hay un par de detalles que faltaba corregir, con los últimos cambios ya deberían pasar las pruebas

2024-02-16 17:13 UTC, merged