Bloqueando el Crear Concurso desde el backend para usuarios U13.
omegaup/omegaup pull request #7285
Opened 2023-10-05 20:55 UTC by carlosabcs

# Descripción

Parte de los cambios de cuentas para niños

# Checklist:

- [x] El código sigue la [guía de
      estilo](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) de
      omegaUp.
- [x] Se corrieron todas las pruebas y pasaron.
- [x] Si se está agregando funcionalidad nueva, se agregaron pruebas.
- [x] Si el cambio es grande (> 200 líneas), hay que intentar partirlo en
      varios pull requests. De preferencia uno para los controladores + phpunit
      y luego otro para la interfaz.

2023-10-05 20:55 UTC, carlosabcs commented
@tvanessa si puedes, porfa échale un ojo a las cadenas de traducción que agregué para la excepción cuando hagan peticiones las cuentas para niños.

2023-10-11 20:19 UTC, tvanessa requested changes

2023-10-11 20:19 UTC, tvanessa commented on frontend/templates/es.lang
> +under13UserException = "No puedes acceder a este sitio desde una cuenta para niños"
```suggestion
under13UserException = "No puedes acceder a este sitio desde una cuenta para menores de 13 años"
```

2023-10-11 20:19 UTC, tvanessa commented on frontend/templates/en.lang
> +under13UserException = "You can't access this site using a children account"
Me parece mejor decirlo explícito.
```suggestion
under13UserException = "You can't access this site from an account for children under 13 years of age"
```

2023-10-20 20:35 UTC, tvanessa approved these changes

2023-10-21 19:08 UTC, heduenas approved these changes

2023-10-21 20:29 UTC, merged