My dependents
omegaup/omegaup pull request #7313
Opened 2023-10-30 16:31 UTC by IngridRB

# Descripción

Fixes: #7292 

# Checklist:

- [x] El código sigue la [guía de
      estilo](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) de
      omegaUp.
- [x] Se corrieron todas las pruebas y pasaron.
- [x] Si se está agregando funcionalidad nueva, se agregaron pruebas.
- [x] Si el cambio es grande (> 200 líneas), hay que intentar partirlo en
      varios pull requests. De preferencia uno para los controladores + phpunit
      y luego otro para la interfaz.

2023-11-02 16:00 UTC, carlosabcs requested changes
En líneas generales el PR está bien, nada más algunos cambios que son necesarios.

2023-11-02 16:00 UTC, carlosabcs commented on frontend/server/src/Controllers/User.php
> +            'entrypoint' => 'user_dependents', // FIXME: Update this to the right entrypoint
```suggestion
            'entrypoint' => 'user_dependents',
```
Ese "FIXME" ya puede irse, porque era para indicar que se tenía que cambiar acorde una vez hagas precisamente este cambio.

2023-11-02 16:00 UTC, carlosabcs commented on frontend/www/js/omegaup/components/user/Dependents.vue
> +          <th scope="col" class="text-center">Usuario</th>
Aquí debes usar una cadena de traducción

2023-11-02 16:00 UTC, carlosabcs commented on frontend/www/js/omegaup/components/user/Dependents.vue
> +      Acceso parental
Aquí debes usar una cadena de traducción

2023-11-02 16:00 UTC, carlosabcs commented on frontend/www/js/omegaup/components/user/Dependents.vue
> +//   import * as ui from '../../ui';
Por favor elimina este comentario si no usarás ese `import`.

2023-11-04 13:32 UTC, carlosabcs commented on frontend/templates/pt.lang
> +dependentsUser = "Do utilizador"
```suggestion
dependentsUser = "Usuário"
```

2023-11-06 17:44 UTC, IngridRB commented on frontend/templates/pt.lang
> +dependentsUser = "Do utilizador"
@carlosabcs realice todas las correcciones sugeridas.

2023-11-07 14:10 UTC, carlosabcs approved these changes

2023-11-07 18:34 UTC, merged