Added verdict colors for [WA,TLE,MLE]
omegaup/omegaup pull request #7475
Opened 2024-03-09 21:36 UTC by HNOONa-0

# Description

Added extra styling classes that color verdicts [WA,TLE,MLE]. I added these classes locally to each of the three pages/components that lists the submissions. I did not want to add it to any sass files or to existing sass files such as `_variables.sass` because I believe sass files are managed by the authors only.

Fixes: #7472

# Comments

# Checklist:

- [x] The code follows the [coding guidelines](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) of omegaUp.
- [x] The tests were executed and all of them passed.

2024-03-10 07:55 UTC, pabo99 reviewed
One suggestion only!

Thank you for adding this missing verdict colors

2024-03-10 07:55 UTC, pabo99 commented on frontend/www/js/omegaup/components/arena/RunsForCourses.vue
> +  background: #e74c3c;
Could you please add all of these colors to the frontend/www/sass/base/_variables.scss file?

This will help us when implementing the dark mode, as it prevents hardcoding colors inside the components.

2024-03-10 09:34 UTC, HNOONa-0 commented on frontend/www/js/omegaup/components/arena/RunsForCourses.vue
> +  background: #e74c3c;
Done!
I would just like to add a small note, I noticed there is some redundant styling like these two variables `--arena-submissions-list-verdict-ac-background-color` and `--arena-runs-table-status-ac-background-color`, different names but are referring to same color value.

2024-03-11 18:40 UTC, pabo99 approved these changes
Great!

2024-03-19 17:26 UTC, HNOONa-0 commented
It failed because it couldn't download the Cypress binary?

2024-03-24 14:42 UTC, HNOONa-0 commented
Hello @tvanessa. Can you check this pr 🥺?

2024-03-25 21:45 UTC, tvanessa requested changes

2024-03-25 21:45 UTC, tvanessa commented on frontend/www/sass/base/_variables.scss
>    --arena-runs-table-status-ac-background-color: #cf6;
```suggestion
  --arena-runs-table-status-ac-background-color: #8d5;
```

2024-03-25 21:45 UTC, tvanessa commented on frontend/www/sass/base/_variables.scss
> +  --arena-runs-table-status-wa-background-color: #e74c3c;
```suggestion
  --arena-runs-table-status-wa-background-color: #d58;
```

2024-03-25 21:45 UTC, tvanessa commented on frontend/www/sass/base/_variables.scss
> +  --arena-runs-table-status-mle-background-color: #a569bd;
```suggestion
  --arena-runs-table-status-mle-background-color: #85d;
```

2024-03-25 21:45 UTC, tvanessa commented on frontend/www/sass/base/_variables.scss
> +  --arena-runs-table-status-tle-background-color: #f5b041;
```suggestion
  --arena-runs-table-status-tle-background-color: #fd0;
```

2024-03-25 21:45 UTC, tvanessa commented on frontend/www/sass/base/_variables.scss
>    --arena-runs-table-status-ac-background-color: #cf6;
Reference: https://github.com/omegaup/media.
Thanks!

2024-03-26 21:58 UTC, tvanessa approved these changes

2024-03-26 23:47 UTC, merged