Issue#7532 | Added Infinite Scroll
omegaup/omegaup pull request #7553
Opened 2024-04-10 21:13 UTC by Ashish-003

# Description
This Pull request is in development.
Please include a description of the changes you have made. The text you put in this section will be used as the **commit message** when this PR is merged.

If you modify the **User Interface**, please include a screenshot or a video.

Fixes: #(issue)

# Comments

Add any comments for the reviewers (e.g., indicating the beginning of the revision, something where the reviewer needs to pay special attention, etc.). If  there are no extra comments this section can be deleted.

# Checklist:

- [ ] The code follows the [coding guidelines](https://github.com/omegaup/omegaup/wiki/Coding-guidelines) of omegaUp.
- [ ] The tests were executed and all of them passed.
- [ ] If you are creating a feature, the new tests were added.
- [ ] If the change is large (> 200 lines), this PR was split into various Pull Requests. It's preferred to create one PR for changes in controllers + unit tests in PHPUnit,  and then another Pull Request for UI + tests in Jest, Cypress or both.

2024-04-17 08:19 UTC, pabo99 reviewed
This PR will be blocked until PR #7555 or #7558 is approved and merged with main branch.

2024-04-17 08:19 UTC, pabo99 commented on frontend/www/js/omegaup/components/submissions/List.vue
> +          :value.sync="searchedUsernameLocal"
What is the reason for modifing this variable name? If there's no reason, could you please restore it as originally was

2024-04-17 10:05 UTC, Ashish-003 commented on frontend/www/js/omegaup/components/submissions/List.vue
> +          :value.sync="searchedUsernameLocal"
Yeah I was trying something, but forgot to restore it back

2024-05-15 21:06 UTC, pabo99 requested changes
With all the changes proposed in your PR, we have encountered an issue that can be easily resolved. Let me explain:

Previously, we rendered the submission list once, which was fine. However, now we render it every time we reach the bottom of the page and the API returns more submissions. Consequently, the iterator has a key. The purpose of using the key attribute is to assist Vue.js in efficiently updating the DOM when the underlying data changes.

Currently, we are using an index that starts from 0 every time we retrieve more data from the API.

The solution is to use an identifier for this key. Currently, we have a GUID for every submission created, which is passed from the server. All we need to do is include it in the type declarations to ensure it is recognized by TypeScript.

Don't forget to run the command:
```
./stuff/lint.sh
```
to make the changes visible in TypeScript.

2024-06-14 02:51 UTC, Ashish-003 commented on frontend/www/js/omegaup/components/submissions/List.vue
> +    v-infinite-scroll="() => $emit('fetch-more-data')"
I thought we used arrow function when an event was triggered otherwise it takes it to be a method and invokes it when template is rendered

2024-06-18 15:52 UTC, pabo99 commented on frontend/www/js/omegaup/components/submissions/List.vue
> +    v-infinite-scroll="() => $emit('fetch-more-data')"
You are right, the way you are doing it is correct. So let me mark this conversation as resolved.

2024-06-18 16:40 UTC, Ashish-003 commented
> With all the changes proposed in your PR, we have encountered an issue that can be easily resolved. Let me explain:
> 
> Previously, we rendered the submission list once, which was fine. However, now we render it every time we reach the bottom of the page and the API returns more submissions. Consequently, the iterator has a key. The purpose of using the key attribute is to assist Vue.js in efficiently updating the DOM when the underlying data changes.
> 
> Currently, we are using an index that starts from 0 every time we retrieve more data from the API.
> 
> The solution is to use an identifier for this key. Currently, we have a GUID for every submission created, which is passed from the server. All we need to do is include it in the type declarations to ensure it is recognized by TypeScript.
> 
> Don't forget to run the command:
> 
> ```
> ./stuff/lint.sh
> ```
> 
> to make the changes visible in TypeScript.

2024-06-18 16:43 UTC, Ashish-003 commented
> With all the changes proposed in your PR, we have encountered an issue that can be easily resolved. Let me explain:
> 
> Previously, we rendered the submission list once, which was fine. However, now we render it every time we reach the bottom of the page and the API returns more submissions. Consequently, the iterator has a key. The purpose of using the key attribute is to assist Vue.js in efficiently updating the DOM when the underlying data changes.
> 
> Currently, we are using an index that starts from 0 every time we retrieve more data from the API.
> 
> The solution is to use an identifier for this key. Currently, we have a GUID for every submission created, which is passed from the server. All we need to do is include it in the type declarations to ensure it is recognized by TypeScript.
> 
> Don't forget to run the command:
> 
> ```
> ./stuff/lint.sh
> ```
> 
> to make the changes visible in TypeScript.

The PR still shows 1 requested change. Can you mark the comment as resolved

2024-06-19 01:05 UTC, pabo99 reviewed
I noticed that there were still some suggestions to be resolved. I added a few comments; with them, it seems like my part is done.

Thank you for working on this issue.

2024-06-19 01:05 UTC, pabo99 commented on frontend/www/js/omegaup/submissions/list.ts
> +              username: this.searchedUsername,
Here we could directly obtain the username from the `payload`:
```suggestion
              username: payload.username,
```
For this, it would be necessary for you to add this data in the `getLatestUserSubmissionsForTypeScript` function right where the `payload` object is.

Additionally, you need to add this new field to the `SubmissionsListPayload` type declaration. The field to add should be something like: `username?: string`.

2024-06-19 03:58 UTC, Ashish-003 commented on frontend/www/js/omegaup/components/submissions/List.vue
> +    v-infinite-scroll="() => $emit('fetch-more-data', submissions[0].username)"
My bad for carelessness, 
I overlooked this.
Resolved it though

2024-06-19 04:00 UTC, Ashish-003 commented
> I noticed that there were still some suggestions to be resolved. I added a few comments; with them, it seems like my part is done.
> 
> Thank you for working on this issue.

Did it, I just couldn't leave things halfway.

2024-06-19 05:24 UTC, pabo99 commented
> > I noticed that there were still some suggestions to be resolved. I added a few comments; with them, it seems like my part is done.
> > Thank you for working on this issue.
> 
> Did it, I just couldn't leave things halfway.

We really appreciate it! Thank you so much!

2024-06-19 05:30 UTC, pabo99 reviewed
One more suggestion!

2024-06-19 05:30 UTC, pabo99 commented on frontend/server/src/Controllers/Submission.php
> + * @psalm-type SubmissionsListPayload=array{includeUser: bool, username: string|null, submissions: list<Submission>}
Ok, it looks like there's an error in the type declaration that was just added. Let me explain the reason:

There is a difference between the type `username: string|null` and the type `username?: string`. While the first indicates that it will always be present even if its value is `null`, the second indicates that the element may or may not exist.

In this case, the `SubmissionsListPayload` declaration is shared between the two methods we've been using. In `getLatestSubmissionsForTypeScript`, the `username` is not present, but in `getLatestUserSubmissionsForTypeScript`, the `username` is sent.

There are two possible solutions:

Add `'username' => null` in the first function.
Declare this type as `username?: string`.

Both solutions should work.

2024-06-19 05:35 UTC, Ashish-003 commented on frontend/server/src/Controllers/Submission.php
> + * @psalm-type SubmissionsListPayload=array{includeUser: bool, username: string|null, submissions: list<Submission>}
Jinxed, I was just changing that

2024-06-19 05:42 UTC, pabo99 approved these changes
LGTM!

2024-08-24 21:03 UTC, heduenas approved these changes

2024-08-24 21:03 UTC, merged